### ISSUE TITLE
Don't exit the daemon on an error sending a transaction

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#1001]
## Current Behavior

Right now, we exit the daemon if a transaction is invalid because the account balance of the sender is too low.

## Desired Behavior

What we should do instead is report that the transaction is invalid error back to the client, and `exit 1` on the client instead.

## Code to change

The daemon exits inside [coda_main.ml](https://github.com/CodaProtocol/coda/tree/3ca2b00d73b70ca5dab2b1cd14e85dc2bb07d8a3/src/app/cli/src/coda_main.ml) when this branch is hit inside `schedule_transaction`:

```ocaml
let schedule_transaction log t txn =
    let open Deferred.Let_syntax in
    if not (is_valid_transaction t txn) then (
      Core.Printf.eprintf "Invalid transaction: account balance is too low" ;
      Core.exit 1 ) ;
   (* ... *)
```

Instead, `schedule_transaction` should return a `unit Or_error.t` and not `unit`. When the bad branch is taken we return an explicit error.

This can be forwarded in `send_txn`, and you can adjust the RPC response type in `Send_transactions` within [client_lib.ml](https://github.com/CodaProtocol/coda/tree/3ca2b00d73b70ca5dab2b1cd14e85dc2bb07d8a3/src/lib/client_lib/client_lib.ml). And handle the `unit Or_error.t` when it pops out of the RPC call inside [client.ml](https://github.com/CodaProtocol/coda/tree/3ca2b00d73b70ca5dab2b1cd14e85dc2bb07d8a3/src/app/cli/src/client.ml) inside the body of `send_txn`.

**Comment by jkrauska** [comment]
Fixes #568
