### ISSUE TITLE
Public key Quickcheck generators easily produce duplicates

### ISSUE THREAD

**Issue by psteckler** [CodaProtocol/coda#1078]
Running `Quickcheck.list_with_length` on `Public_key.gen` or `Public_key.Compress.gen` produces duplicates with a length as short as 10. With a list of 1000 or so, I've observed around 20 duplicates.

**Comment by enolan** [comment]
fixed in #2847. You want `gen_uniform_incl` instead of `gen_incl`. The former is biased to test the boundary cases more often i.e. the upper and lower bounds.

**Comment by enolan** [comment]
we should fix `gen_keys` from that PR after #2847 is merged. It's also using `Quickcheck.random_value` which is usually the wrong thing to do since it's deterministic, but I didn't look too closely.

**Comment by jkrauska** [comment]
@enolan can you take a look at gen_keys and confirm current state?

**Comment by psteckler** [comment]
As of this writing, this bug still occurs.

**Comment by psteckler** [comment]
Fixed by #3944
