### ISSUE TITLE
Seed node should make verifier_main.bc.js and main.bc.js and save it locally in it's own machine

### ISSUE THREAD

**Issue by wu-s-john** [CodaProtocol/coda#1084]
Whenever we deploy our website, we have to be wary that the keys of `verifier_main.bc.js` and `main.bc.js`matches with the Seed Node's. If they are not the same, then verification will fail for our website. It would be best for the Seed Node to create a set proving keys and their corresponding js files. To make the js files, you can run `make website` in the root directory.

**Comment by johnwu93** [comment]
I think it would be helpful to have this special environment variable. We may not know where Coda will be executed in the file system, so we can not make assumptions about the directory structure. So, it would be nice to use an environment variable.
