### ISSUE TITLE
Deterministically select between blocks proposed in the same slot

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#1127]
Multiple VRF winners in the same slot are expected and common in proof of stake. According the the Ouroboros papers, selection between blocks in this scenario does not neet to be deterministic across all nodes (each node could randomly select a block and the proofs would still hold). However, having a deterministic methodology for selecting between multiple blocks for the same slot would have a significant positive effect on the length of forks. Because of this, we should try and find a non-controllable property that we can use to provide a pseudo random yet deterministic selection across all nodes.

The current proposition for this is to take the VRF evaluation and hash it, taking maximum (or minimum; shouldn't matter which one).  This is likely the best way, although it would require adding the vrf output to the consensus_state, where as right now the vrf evalutation is only in the consensus_transition_data for proving in the snark and is not actually submitted to the network. Either way, whatever option is selected *must* be a non-controllable and evenly distributed property.

**Comment by imeckler** [comment]
Hm -- just realized the way we're doing delegation interacts with this in kind of a screwed up way. Namely, since a delegate may have multiple winning delegators they can pick amongst them as to which has the lowest hash. that's not too much grinding available but it is some…

**Comment by nholland94** [comment]
That's what I do right now, and the proofs in the paper will still hold. But @es92 wanted to find a deterministic way so that the network would have less waste. Selection by order received means you will have forks by locality. In other words, sections of the network with lower network delays with each other will be more likely to cause a major fork, and while eventually only one fork will live, all of the work done on forks that don't win is essentially wasted work. Deterministically selecting could reduce the number of these kind of forks and therefor waste less work (to say it the other way, more work performed will actually make it into the final chain if we deterministically select).

**Comment by imeckler** [comment]
@es92 and I chatted about this and he had some argument against using the one you received first and an argument that the VRF hash thing was actually fine even though you can grind a bit (since it's just as if the individual stakers had all done it themselves). @es92 care to chime in?
