### ISSUE TITLE
Ledger Builder Controller ignoring "select = `Take"

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#1128]
Under certain, unknown circumstances, the ledger builder controller can get stuck in a loop where it will not add any transitions to the tree even though consensus validates the transitions and informs the ledger builder controller to "\`Take" the new transition. This scenario repeats as transitions are continually received from the network. My guess is that a dependency for the first new transition in this broken sequence is missing, and since it doesn't get added, all other transitions branching off of this are also missing dependencies.

This has only been seen when running proof of stake in a dev network.

**Comment by bkase** [comment]
This could be a sign that something with the snark is failing. I saw similar behavior when I had broken snark code in proof of signature. On the whiteboard, we ( @cmr and I ) had a few ideas of new debug assertions we can add to help catch things faster and those may help you solve this. I’m not sure if we turned that list into concrete issues yet.

**Comment by nholland94** [comment]
No longer relevant with the transition frontier controller rewrite.
