### ISSUE TITLE
Interruptible is not exception resistent

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#1140]
The `Interruptible` library should be resilient against exceptions being thrown inside of functions it calls. In particular, `Interruptible.finally` is not exception resistant to any exceptions thrown by the `~f` function.

**Comment by cmr** [comment]
After some discussion, we're not really sure if this is a bug or not. Right now, we're learning towards "no", and that we should adopt fail-fast pretty much everywhere.

**Comment by nholland94** [comment]
After discussing, I am aligned with not considering this to be a bug. Closing the issue for now.
