### ISSUE TITLE
Receipt_chain_database should use a persistent database

### ISSUE THREAD

**Issue by wu-s-john** [CodaProtocol/coda#1144]
Follow up from https://github.com/CodaProtocol/coda/issues/1116

Right now, the database that `Receipt_chain_database` is `Core.Hashtbl`, which is an in-memory database. It would be nice to use an on-disk database and the reads/writes and should be async. A poor man's in-memory database would be using `Core.Hashtbl` and every time we make a write, we record bin_io the entire table. However, we can use Rocksdb instead since @psteckler almost got it integrated into our code base.

**Comment by jkrauska** [comment]
@johnwu93 we think this may be done -- would you like to confirm?
