### ISSUE TITLE
Refactor coda-client and it's helper modules

### ISSUE THREAD

**Issue by johnwu93** [CodaProtocol/coda#1157]
`coda-client` (client.ml) and some of it's helper dependencies, namely `cli_lib.ml` and `client_lib.ml`, are a bit tangled in terms of functionality. To improve navigating around the library and support easy function reuse, we should refactor the code. Here are some suggestions to refactor the code:

- [x] Combine `cli_lib` and `client_lib` together since they are pretty similar to each other and somewhat coupled together. Also, it is hard to distinguish their functionalities by their names. So, it would be better to combine them together. This library would be the main helper library for `client.ml`
- [x] Combine all the flags (i.e. `json_flag`) that are shared among different client commands into one submodule in `client_lib`. 
- [x] Combine all the `arg_type` parsers (i.e.`public_key` and `peer`) in `cli_lib` into one submodule.
- [x] Make `Daemon_cli` in `client.ml` into it's own file.
- [x] Make all the modules that are used to make rpc calls with daemon into it's own submodule. Call them `Daemon_rpc_hooks`?

**Comment by bkase** [comment]
As discussed (with @cmr and @johnwu93 ), can you keep `client_lib` separate (but rename to `daemon_rpcs`) as maybe the wallet code would want to consume the rpcs. Everything else you're suggesting sounds good!
