### ISSUE TITLE
Parallelize non-SNARK pedersen hashing

### ISSUE THREAD

**Issue by emberian** [CodaProtocol/coda#1256]
https://github.com/CodaProtocol/coda/pull/1199 implements a parallel core Pedersen loop with OpenMP and C++. It doubles the performance of hashing PoStake protocol states. It is causing hangs in the integration tests for some unknown reason (it isn't forking, is something wrong with the openmp code?).

This is low priority, but should hopefully only take some debugging.

**Comment by psteckler** [comment]
Pedersen is gone.
