### ISSUE TITLE
Masking_merkle_tree.to_list is incorrect

### ISSUE THREAD

**Issue by cmr** [CodaProtocol/coda#1307]
It shouldn't just concatenate the base and mask lists, it should instead merge them. Instead, take everything from the parent, and then replace the entries with matching ones from the mask if present.

**Comment by cmr** [comment]
`to_list` is currently unused, but it's potentially useful for printf debugging.

**Comment by psteckler** [comment]
Maybe in `to_list`, or another function, like `dump`: show contents of mask in sublist, then contents of its parent, and so on. Each sublist could contain its type, like "Mask" or "Database", and its Uuid.

**Comment by psteckler** [comment]
Furrther, `fold` and `fold_until` should work with such merged lists.
