### ISSUE TITLE
return of the long async cycles - seeing on all processes

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#1336]
In current testing, I'm again seeing these log lines.

```("long async cycle" 1.217s)
("long async cycle" 726.592ms)
("long async cycle" 777.693ms)
("long async cycle" 4.98252s)
("long async cycle" 1.0389s)
("long async cycle" 2.24215s)
("long async cycle" 1.15609s)
("long async cycle" 2.61767s)
```

Before we connected these in part to memory leaks.

I don't think that's what I have here.

As they are emitted to stderr, I don't have good event correlation anymore with the current work happening in stdout -- I think we should move these to stdout and/or try to give more context.

Seeing these on seeds, proposers, snarkworkers...  

Worst cases on proposers.  (peak at ~5s)

Also might be related to simple contention for CPU.
(this is on single node cluster)

Any advice on further debugging would be appreciated.

**Comment by cmr** [comment]
Our current long async cycles are understood.
