### ISSUE TITLE
Figure out how to portably link our C dependencies statically

### ISSUE THREAD

**Issue by emberian** [CodaProtocol/coda#1415]
Right now our build has substantial problems building on macOS because our dependencies assume the linker is GNU ld. On macOS the linker is not GNU ld. We need to be using `-force_load` on macOS, so that dlsym will see all the symbols we expect at runtime. `-force_load` takes a full path to a static library. There's also no equivalent to `-Bstatic` to make the linker consider static libraries before dynamic ones when trying to satisfy an `-lfoo` request.

**Comment by cmr** [comment]
We can use `Configurator` (or, really, anything) to generate a `flags.sexp` that we then use with `(link_flags (:include flags.sexp))`

**Comment by cmr** [comment]
Done in https://github.com/CodaProtocol/coda/pull/1443 and https://github.com/CodaProtocol/coda/pull/1433

**Comment by emberian** [comment]
we finished this!
