### ISSUE TITLE
Epoch ledgers

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#1425]
Now that merkle masks and merkle database are in, we need to setup epoch merkle tree caching for proof of stake properly. In proof of stake consensus, we need to cache and query merkle trees at the beginning of an epoch for the previous epoch. This means that, at any point in time, there will be at least 2 merkle trees we are tracking in the past: the one at the beginning at the current epoch, and the one at the beginning of the previous epoch. These should both be represented as backwards chained merkle masks from the snarked ledger at the root of the transition frontier (the filesystem persisted merkle database). In order to accommodate this work, a few addition will need to be made:

- merkle masks should support backwards chaining
- merkle masks should support unsafe reparenting
- the consensus mechanism layer should have some way of interacting with merkle masks; it needs to "copy" (derive a new merkle mask from an old one), and it needs to query account information.

**Comment by bkase** [comment]
@nholland94  found an optimization in epoch ledger tracking. Since our VRF is in the SNARK, we don't need to keep the full ledgers in the epochs we only need our merkle-path and those that delegate to us. That is the new approach.
