### ISSUE TITLE
Precompute the genesis ledger at compile time

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#1488]
We have compile time selection of the genesis ledger, but the selected ledger is not materialized until runtime. This is because computing the hashes of a genesis ledger involves calling out to C, so `ocamlopt` cannot inline the calls to `Genesis_ledger.Functor.*.Make`. To fix this, we should code gen a file which contains the precomputed intermediate hashes and constructs the ledger object from those. This should allow `ocamlopt` to inline the full ledger object and avoid injecting initialization code from `Genesis_ledger`.

**Comment by cmr** [comment]
#2775 works around this by making the genesis ledger computed lazily. This helps with startup times of the client but doesn't fix the root of the issue.

**Comment by deepthiskumar** [comment]
#4001 implements this
