### ISSUE TITLE
In Blockchain_state, rename `ledger_hash` to `snarked_ledger_hash`.

### ISSUE THREAD

**Issue by johnwu93** [CodaProtocol/coda#1530]
While doing issue https://github.com/CodaProtocol/coda/issues/1510, I misused the `staged_ledger_hash` as `ledger_hash`. `ledger_hash` is actually the hash representing the snarked ledger. We should rename `ledger_hash`  to `snarked_ledger_hash`.

**Comment by ghost-not-in-the-shell** [comment]
`coda_base/blockchain_state.ml` is the file
