### ISSUE TITLE
Catchup_scheduler should only create timeouts for roots of transition trees

### ISSUE THREAD

**Issue by johnwu93** [CodaProtocol/coda#1590]
Currently, when we watch an `external_transition` in `Catchup_scheduler`, we set a timeout and after the timeout, the external_transition will be processed as a `catchup_job`. If we look at this carefully, we do not have to construct a timeout for the `external_transition` if its parent already has a timeout since they are connected. In fact, these `external_transitions` in `Catchup_scheduler` form disjointed trees and their roots should have timeouts for a `catchup_job`.

**Comment by ghost-not-in-the-shell** [comment]
The current implementation would cause duplicate work.

Assume one transition has already fired a catchup job. During the time it waits for the catchup, another transition which belongs to the same branch may fire another catchup job on its own.

I would try to change the current implementation to avoid such duplicate work. And I also should write a unit test to catch such scenario.
