### ISSUE TITLE
Bulk write transactions from mask to database

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#1606]
This is nice for transition frontier root transitions as we commit a massive amount of transactions all at once

**Comment by enolan** [comment]
Because of this, the code that commits the mask of the new snarked ledger when the root of the transition frontier is removed is commented out. So IIUC our memory usage grows without bound. Maybe we should uncomment it and eat the performance cost.

**Comment by enolan** [comment]
I'm wrong. We just do all the writes to the db ledger, the mask is completely unused. But actually this functionality is already in, we just don't use it in the transition frontier. I've modified the code to use it, will PR soon.
