### ISSUE TITLE
replace `set_all_accounts_rooted_at_exn` with `set_batch_accounts`

### ISSUE THREAD

**Issue by wu-s-john** [CodaProtocol/coda#1607]
Follow up from https://github.com/CodaProtocol/coda/issues/1576

We are changing the interface for `get_all_accounts_rooted_at` from `t -> addr -> account list` to `t -> addr -> (addr * account) list`. The `set_all_accounts_rooted_at` would work akwardly with this interface. Instead, we should have a function `set_batch_accounts` that first adds the accounts and then compute their corresponding hashes on their `merkle_paths`

cc: @cmr

**Comment by cmr** [comment]
`set_batch` already exists, thanks to the new ledgers.
