### ISSUE TITLE
PV Keys Created in /tmp even when not used

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#1644]
See this CI build.
https://circleci.com/gh/CodaProtocol/coda/40092#artifacts/containers/0

It pulls down stable keys and seems to compile with those keys (as the binary won't run without them)
     "Transaction_snark: load failed on (/var/lib/coda/d730428c9fa0b6e36f6ca485d05f39fc_verification\
Note key is d730 (part of stable key download)

But then it ALSO generate PV keys in /tmp/
/tmp/coda_cache_dir/
/tmp/coda_cache_dir/4108b53fb3572b6664a9d597abacae84_proving
/tmp/coda_cache_dir/4108b53fb3572b6664a9d597abacae84_verification

These keys seem to NOT be used in the build.

Previously I believe the behavior was NOT to generate keys if the ones in /var/lib/coda worked.

Please review?

**Comment by cmr** [comment]
Pretty sure this doesn't happen today?
