### ISSUE TITLE
get_ledger_by_hash should find a ledger for a given transition frontier in O(1) time

### ISSUE THREAD

**Issue by wu-s-john** [CodaProtocol/coda#1666]
Right now, when we try to look up a ledger by its ledger_hash in a transition_frontier, we look them up by going through all the breadcrumbs and then determine if any of those breadcrumbs' staged_ledger merkle root matches with the ledger_hash. However, this takes linear amount of time and we can do better by augmenting the Transition_frontier with a hashtble for looking up a ledger by it's ledger_hash.  In a Transition_frontier, multiple breadcrumbs can reference a ledger. So, in order to efficiently garbage collecting our frontier, we should have a count of how many breadcrumbs are associated with a ledger. We can use the `rc_pool` to help us count how many breadcrumbs are referencing a ledger and have the fast look-up from _ledger_hash to ledger.

**Comment by cmr** [comment]
:+1: noticed this in a review today as a possible source of slowness.

These days this would make a nice TF extension.
