### ISSUE TITLE
Simple: Add epoch and slot to 'coda client status'

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#1702]
Current beginning of 'coda client status' looks like this.

```
Coda Daemon Status
-----------------------------------
Number of Accounts:       18
Block Count:              106
Uptime:                   63501s
```

I am able to poll current epoch and slot on the proposer log files:
```
"message":"systime: 1550714400000, epoch-slot@systime: 127-2, starttime@epoch@systime: 1550714400000"
```

But I can only get this on the proposer.

Ideally any node in the cluster ought to be able to report the current epoch and slot in client status.

Example:
```
Coda Daemon Status
-----------------------------------
Number of Accounts:       18
Block Count:              106
Uptime:                   63501s
Epoch:                    127
Slot:                     2
```

This would be extremely helpful in debugging test net synchronization and status.

**Comment by cmr** [comment]
done
