### ISSUE TITLE
Create a mini-integration test for transition_handler

### ISSUE THREAD

**Issue by wu-s-john** [CodaProtocol/coda#1720]
Currently, we do not clean up the transitions in catchup_scheduler after a subtree is sent to ledger_catchup and then materializing the breadcrumbs created by the job. It is essential to remove the subtree from the ledger_catchup.

We can create a test for this behaviour by creating the components of Transition_handler, `Processor`, `Validator` and `Catchup_scheduler` and `Ledger_catchup`. Then, create a random transition_frontier along with a dangling subtree that does not connect to the transition_frontier. Then, send those nodes to the `Catchup_scheduler`. After some time, a ledger_catchup job should be invoked and create a breadcrumb bridge connecting the dangling subtree to the frontier. Then, the dangling subtree should be connected to the frontier and there should be no more breadcrumbs in `Catchup_scheduler`

**Comment by ghost-not-in-the-shell** [comment]
The catchup_scheduler and ledger_catchup are writing into the same pipe. And in the `processor.ml`, we read out the breadcrumbs in the pipe and add those to the transition frontier. We usually have to notify catchup_scheduler for any new transitions. Here things are different for breadcrumbs that come from `catchup_scheduler` and `ledger_catchup`:

1) for `catchup_scheduler`, we don't need do any notification.
2) for `ledger_catchup`, we need to notify only the last transition.

So I think we should tag every breadcrumb added into the catchup_breadcrumb_pipe to differentiate whether we need to do notification or not.

**Comment by nholland94** [comment]
Closed by #1696
