### ISSUE TITLE
Fix unstable kademlia test

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#1725]
For now, it's disabled

Example stack trace:
$ (cd _build/default/lib/kademlia && .kademlia.inline-tests/run.exe inline-test-runner kademlia -source-tree-root ../.. -diff-cmd -)
File "lib/kademlia/membership.ml", line 626, characters 8-2332: connect with ban logic threw
(monitor.ml.Error "Assert_failure lib/kademlia/membership.ml:669:14"
  ("<backtrace elided in test>")).
  Raised at file "src/result.ml" (inlined), line 168, characters 17-26
  Called from file "src/thread_safe.ml", line 125, characters 2-36
  Called from file "lib/kademlia/membership.ml", line 541, characters 12-16
  Re-raised at file "lib/kademlia/membership.ml", line 541, characters 41-48
  Called from file "runtime-lib/runtime.ml", line 486, characters 15-19
  Called from file "runtime-lib/runtime.ml", line 327, characters 8-12
  Re-raised at file "runtime-lib/runtime.ml", line 330, characters 6-13
  Called from file "runtime-lib/runtime.ml", line 343, characters 15-52
  Called from file "runtime-lib/runtime.ml", line 430, characters 52-83
  in TEST_MODULE at file "lib/kademlia/membership.ml", line 602, characters 4-3184: Trust
  in TEST_MODULE at file "lib/kademlia/membership.ml", line 393, characters 0-10603: Tests

**Comment by enolan** [comment]
let's just say we're not doing this, since `libp2p` is happening.
