### ISSUE TITLE
VRF checking starts in the next slot, not the current slot

### ISSUE THREAD

**Issue by cmr** [CodaProtocol/coda#1753]
This means we're always missing a slot! https://github.com/CodaProtocol/coda/blob/ca93bb5bd5a0edbeeea98b9ddc78d7c55d566298/src/lib/consensus/proof_of_stake.ml#L1362 there shouldn't be a call to `succ` here.

**Comment by enolan** [comment]
github isn't closing issues automatically :( fixed in #1761
