### ISSUE TITLE
Coinbase has assert for validity on deserialization

### ISSUE THREAD

**Issue by psteckler** [CodaProtocol/coda#1767]
In `Coinbase`, there's an `assert` that checks for validity on deserialization. A maliciously-formed instance could bring down a node.

Is there a better way to handle this check?

**Comment by enolan** [comment]
adding this to the trust system board

**Comment by psteckler** [comment]
Closing because #4133.

**Comment by enolan** [comment]
@psteckler are we calling the `is_valid` function in all the right places? I only see a call to it in `Coinbase.create`. I assume that sometimes we read `Coinbase.t`s from the network but I'm not super familiar.

**Comment by psteckler** [comment]
@enolan I don't know for certain. I'll add an issue.
