### ISSUE TITLE
snark worker 'coordinator' daemon needs to be 'robust'

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#1801]
We should not assume that a snark-worker is reliable. Individual snark-worker daemons can crash or be restarted.

If a snark-worker connects and requests work, and we assign it, but DO NOT receive the result back --   We should re-assign that work to another snark-worker after a period of time has elapsed.

This ensures we don't block on a proof that we have assigned but which will never be solved.

**Comment by deepthiskumar** [comment]
This is already implemented. A specific job assignment is retained for 2mins and if it is still not completed then it is reassigned. "Completed" here means that the snark-worker submitted the proof and a block included it.

**Comment by jkrauska** [comment]
Changing the context of this issue...

@deepthiskumar points out and I confirmed that snark work assigned but not completed DOES get re-assigned after a hardcoded 2m timer.

I have adjusted this issue to reflect that a hardcoded value of 2min would probably be better replaced as a function of slot-time, etc..   Maybe 4x or 8x slot time?  @nholland94  (opinion?)

**Comment by nholland94** [comment]
@jkrauska I don't think slot time is the correct parameter to base this timeout after as slot time is (mostly) orthogonal to proving time. We should probably have this be a function of the average time we expect for proofs to be generated (across some various hardware configurations). For now, we could add a tool to easily measure the average proving time on at least one machine and just update some value in our build configuration with that value. I think setting the time threshold to something in the range of 3x-6x the average proving time makes sense. We may also want to factor some network delay parameter into there as well.

**Comment by cmr** [comment]
Is the timeout still 2 min? We need to crank it up for medium curves.
