### ISSUE TITLE
Error when building source code

### ISSUE THREAD

**Issue by g666** [CodaProtocol/coda#1931]
The command `make USEDOCKER=TRUE dev` fails with the folowing error:

> File "lib/bootstrap_controller/bootstrap_controller.ml", line 158, characters 4-22:
> Warning 3: deprecated: Logger.faulty_peer
> use Trust_system.record
> File "lib/bootstrap_controller/bootstrap_controller.ml", line 225, characters 16-34:
> Warning 3: deprecated: Logger.faulty_peer
> use Trust_system.record
> File "lib/bootstrap_controller/bootstrap_controller.ml", line 333, characters 8-55:
> Error: This expression has type module_:string -> location:string -> unit
>        but an expression was expected of type unit
>        because it is in the left-hand side of a sequence
> Makefile:69: recipe for target 'build' failed
> make: *** [build] Error 1

**Comment by enolan** [comment]
Can you pull the latest code and try building again? We changed the logger library recently and that looks like it was broken then. I don't know how it got past CI though.

**Comment by g666** [comment]
Thanks for the support. The command doesn't fail.

**Comment by g666** [comment]
Hi. After I pull the repository I see the following error when I run the command `make USEDOCKER=TRUE dev`:

> File "lib/transaction_snark/transaction_snark.ml", line 428, characters 27-51:
> Error: Unbound value Groth16.reduce_to_prover
> Makefile:69: recipe for target 'build' failed
> make: *** [build] Error 1

**Comment by mrmr1993** [comment]
@g666 you'll need to update to the latest version of Snarky.

I think `git checkout --recurse-submodules origin/master` will do this automatically for you.

**Comment by g666** [comment]
thanks. It works, so I close the issue.
