### ISSUE TITLE
Pending coinbases: Add versioning

### ISSUE THREAD

**Issue by deepthiskumar** [CodaProtocol/coda#2072]
The following types need to be versioned:
1. `Transaction_witness.t`
2. `Pending_coinabse..t`
3. `Pending_coinabse.Hash.t` 
4. `Pending_coinabse.Stack.t`
5. `Pending_coinbase_stack_state.t` in (`transaction_snark.ml`)

**Comment by psteckler** [comment]
#2194 does some of this.

**Comment by psteckler** [comment]
Done.
