### ISSUE TITLE
Wrap external libraries for versioning

### ISSUE THREAD

**Issue by psteckler** [CodaProtocol/coda#2182]
Currently, we have `deriving version {asserted}" where such types are used. Those should become `deriving version {wrapped}`.

This includes some Jane St modules like `Queue`.

**Comment by johnwu93** [comment]
Maybe it's worth having a functor that transforms a versioned module into the module you want. For example, in `bin_prot`, we have access to `Binable.Of_binable` which lets you "binify" a type for a binable type. 

It would be worth having a `Version.Of_binable`, which extends `Binable.Of_binable` by ensuring that you binify from a versioned type and it outputs a versioned type.

**Comment by johnwu93** [comment]
This would make it easy to version a Queue type by having an isomorphic transformation from a Queue to a List.

**Comment by psteckler** [comment]
Where would the code to transform the list representation to the queue representation?

**Comment by johnwu93** [comment]
List -> Queue:
Queue.of_list

and 

Queue -> List:

Queue.to_list

**Comment by psteckler** [comment]
Yes, but which `Queue` implementation is that? If Jane Street changes their implementation of `Queue`, the serialization could change. That's why we may have to wrap the JSt types.

It's not a likely scenario, but still ....

**Comment by psteckler** [comment]
We're using stable versions of Jane Street types, and whitelist those, so they don't need to be wrapped.

For `Bitstring`, we whitelist it, and have a unit test in `Merkle_address` that will detect if its serialization ever changes.
