### ISSUE TITLE
Get rid of util.ml

### ISSUE THREAD

**Issue by imeckler** [CodaProtocol/coda#224]
Right now there is a small file called nanobit_base/util.ml. It should be split out into a few modules. Maybe a folds library

**Comment by jkrauska** [comment]
Current:
https://github.com/CodaProtocol/coda/blob/master/src/app/cli/src/util.ml

The function: split_last_exn

Is only referenced in here:
src/lib/crypto_params/crypto_params_init/crypto_params_init.ml

And is also defined there with a comment "    (* This is duplicated. Where to put utility functions? *)"
https://github.com/CodaProtocol/coda/blob/master/src/lib/crypto_params/crypto_params_init/crypto_params_init.ml#L99-L107

I believe this means util.ml probably can be dropped entirely.

@imeckler
