### ISSUE TITLE
Insta ban on RPC call error (handshake && connection lost) [potentially fixed]

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#2347]
Currently, the codebase instantly bans peers when there is an RPC error while communicating with them. This happens in our integration tests because we lack a proper graceful shutdown for active connections we are handling. However, and insta ban is also too harsh in the circumstance. There should still be a trust decrease, and the trust decrease should be fairly harsh.

**Comment by nholland94** [comment]
An attempted fix has been implemented inside of https://github.com/CodaProtocol/coda/pull/2298. It also adds some verbose logs whenever an RPC call happens to help gain more information about the exceptions being handled. It is unclear if this code has fixed this issue or not quite yet since this bug only triggers sometimes, and currently, there are many other bugs that tend to be triggered before this one.

**Comment by psteckler** [comment]
#2365, not merged, changes the pattern-match for handshake errors, because those errors seemed to be falling through. I saw the new pattern catch those errors. Maybe there are circumstances in which both patterns could work.

**Comment by psteckler** [comment]
Addressed by #2365.
