### ISSUE TITLE
Pipe overflow (valid transitions && verified transitions)

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#2351]
Status: we believe this is fixed but we need to confirm. If @cmr does not find an occurrence since after 5/9 we will close.

**Comment by ghost-not-in-the-shell** [comment]
I failed to reproduced the pipe-overflow behavior of valid-transitions-pipe both locally and on the CI. Would  anyone please point out a log with this failure?

**Comment by cmr** [comment]
I notice there are two pipes named "valid transitions" as well. I'll keep an eye out for it in CI. It's possible they were overflowing for the same reason (verified transitions reader got backed up and the other processes race to fill their pipes?)

**Comment by jkrauska** [comment]
not seen in ci anymore - closing
