### ISSUE TITLE
Handling bans when testing faults

### ISSUE THREAD

**Issue by cmr** [CodaProtocol/coda#2408]
During integration tests, we simulate faulty behavior with restarts. Once we start accounting for connection failures in the trust system, this can lead to bans (it only takes three connection failures to be banned) that prevents the node from joining the network once it restarts. This leads to a network fork, which kills the test.

Some possibilities:

1. Ignore all bans during the test (possibly by ignoring localhost bans). I think this is too coarse.
2. Modify action scoring for tests. (One concrete possibility: Don't ever decrease the trust score, only consider instabans as banworthy).
3. Reset the trust system after stopping nodes, before restarting them. This will prevent bans from breaking the restart.

Even if the trust system distinguished between between separate processes on localhost, one node being randomly restarted a few times could cause it to be banned.

**Comment by cmr** [comment]
Here's my concrete proposal, a variant of 2:

```diff
diff --git a/src/lib/trust_system/peer_trust.ml b/src/lib/trust_system/peer_trust.ml
index 35486cf8..5756fb61 100644
--- a/src/lib/trust_system/peer_trust.ml
+++ b/src/lib/trust_system/peer_trust.ml
@@ -2,6 +2,12 @@ open Core
 open Async
 open Pipe_lib
 
+[%%import "../../config.mlh"]
+[%%inject "integration_tests", integration_tests]
+
+type exn += Insta_ban_during_tests
+
+
 module Trust_response = struct
   type t = Insta_ban | Trust_increase of float | Trust_decrease of float
 end
@@ -92,7 +98,7 @@ struct
     Option.iter db ~f:Db.close ;
     Strict_pipe.Writer.close bans_writer
 
-  let record ({db; bans_writer} as t) logger peer action =
+  let true_record ({db; bans_writer} as t) logger peer action =
     let old_record =
       match get_db t peer with
       | None ->
@@ -140,6 +146,14 @@ struct
           Deferred.unit
     in
     Option.iter db ~f:(fun db' -> Db.set db' ~key:peer ~data:new_record)
+
+  let record t logger peer action =
+    if integration_tests then (
+      let response = Action.to_trust_response action in
+      match response with
+      | Insta_ban -> raise Insta_ban_during_tests
+      | _ -> Deferred.unit
+    ) else true_record t logger peer response
 end
 
 let%test_module "peer_trust" =
```

**Comment by jkrauska** [comment]
We believe this is resolved -- closed.
