### ISSUE TITLE
Remove main coda functor (coda_main/coda_inputs/coda_lib)

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#2448]
The groundwork for removing coda_main/coda_inputs/coda_lib has been layed. Now we just need someone to go through and finish ripping out a few remaining pieces and the whole thing will fall back into place neatly.

Impact: spend less time fiddling with intfs

- [x] Lift coda_pow up in dependency graph + remove unnecessary signatures + reduce functor inputs
- [x] Export default functor instantiations in all libs where possible
- [x] Make coda_lib depend directly on default insantiations in dependencies
- [x] Clean up monkey patching in Coda_inputs
- [x] Fully remove Main_intf and Coda_inputs by propagating changes from coda_lib

**Comment by nholland94** [comment]
https://github.com/CodaProtocol/coda/pull/2558

**Comment by nholland94** [comment]
https://github.com/CodaProtocol/coda/pull/2653 addresses the rest of #2, as well as #3 and #4. Now all that's left if #5 and some miscellaneous cleanup (mostly defunctoring modules one by one now that the dependencies are direct).

**Comment by cmr** [comment]
Done!
