### ISSUE TITLE
Crash: required_local_state_sync assertion

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#2465]
@cmr is grepping thru logs and will update this issue if any more info is found

**Comment by jkrauska** [comment]
Example Log - [coda.log.gz](https://github.com/CodaProtocol/coda/files/3193405/coda.log.gz)

**Comment by cmr** [comment]
https://github.com/CodaProtocol/coda/pull/2517 should solve this one. We'll wait and see!

**Comment by imeckler** [comment]
#2517 did not solve this.

**Comment by cmr** [comment]
#2571 adds a hack that changes how we do the sync, just during bootstrap. It causes the assertion to not trigger later on, but is only a temporary fix. #2581 tracks fixing the root cause.
