### ISSUE TITLE
Debug_assert/log when receiving two transitions on same slot from same proposer

### ISSUE THREAD

**Issue by imeckler** [CodaProtocol/coda#2467]

**Comment by psteckler** [comment]
I ran bootstrap locally, and saw this condition frequently.

Is that expected?

**Comment by cmr** [comment]
Definitely not. In theory [this code](https://github.com/CodaProtocol/coda/blob/master/src/lib/consensus/proof_of_stake.ml#L2549-L2551) should prevent proposing multiple transitions for the same slot. [Definition of `seen_slot`](https://github.com/CodaProtocol/coda/blob/master/src/lib/consensus/proof_of_stake.ml#L375-L386).

**Comment by enolan** [comment]
What's the status quo? Do we fork?

**Comment by cmr** [comment]
No, we take whichever one wins `Consensus.select`

**Comment by cmr** [comment]
Update: we're not sure exactly what `Consensus.select` does in this case. The VRF evaluations will be the same, which is our usual tiebreaker. We need to look at the paper and the code and see what should happen. I thought we used the state hash as a tiebreaker, but we don't.

**Comment by imeckler** [comment]
Hi @cmr @psteckler do either of you know what the status of this issue is?

**Comment by psteckler** [comment]
I'm working on this, but after talking to Evan, think I've been approaching it wrong. I was looking at external transitions, which might come from any node. It's reasonable to see two external transitions with the same proposer and slot, yes?

**Comment by imeckler** [comment]
@psteckler Actually no. A proposer should only submit one block per slot.

**Comment by psteckler** [comment]
@imeckler But could the external transitions have come from distinct nodes that have gossiped the same information?

**Comment by imeckler** [comment]
You should check uniqueness of (slot_number * protocol_state_hash * proposer)

**Comment by imeckler** [comment]
Actually i think `protocol_state_hash * proposer` is enough since the slot number is in the state.

**Comment by psteckler** [comment]
The hash will differ if the transition is received from different nodes? I'm looking at incoming external transitions about to be validated.

**Comment by cmr** [comment]
Done!
