### ISSUE TITLE
Assert failure with inconsistent nonces when adding commands to the transaction pool from backtrack

### ISSUE THREAD

**Issue by enolan** [CodaProtocol/coda#2499]
@ghost-not-in-the-shell spotted the assertion failure in [this run of the holy grail test](https://circleci.com/gh/CodaProtocol/coda/128234#tests/containers/0).

"Assert_failure src/lib/transaction_pool/indexed_pool.ml:596:6"

That throws when we try to add a command from backtracking, there are queued commands for that account, and the earliest queued command's nonce isn't one greater than that of the command we're adding. I'm not sure what's causing it, let's keep notes here.

**Comment by imeckler** [comment]
Any movement on this this week @enolan ?

**Comment by enolan** [comment]
This hasn't shown up in our Kibana logs since running the beta testnet.

**Comment by enolan** [comment]
Best guess this was fixed by #3199
