### ISSUE TITLE
proof_level="check" blockchain snark proof failure

### ISSUE THREAD

**Issue by imeckler** [CodaProtocol/coda#2528]
Provers occasionally fail on "test--test_postake_split". This is with proof-level check, so it may be nothing, but in that case we should then turn off whatever constraint is not satisfied in this case. 

https://circleci.com/gh/CodaProtocol/coda/131948?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by cmr** [comment]
I've been unable to reproduce this locally, after ~50 runs of `test_postake_split_snarkless:coda-shared-prefix-test -who-proposes 1` and ~30 runs of `test_postake_split:coda-shared-prefix-multiproposer-test -num-proposers 2`. Here's a CI failure from shared-prefix-multiproposer: https://circleci.com/gh/CodaProtocol/coda/133812 and a recent failure on master CI for shared-prefix-test https://circleci.com/gh/CodaProtocol/coda/133812#artifacts/containers/0

I'm not willing to rule this out as nothing yet - AFAIK proof-level=check for that prover is fully featured.

**Comment by deepthiskumar** [comment]
I see this on my parallel scan refactor branch https://github.com/CodaProtocol/coda/pull/2546.
https://github.com/CodaProtocol/coda/pull/2546https://github.com/CodaProtocol/coda/pull/2546
https://circleci.com/gh/CodaProtocol/coda/134701?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by cmr** [comment]
I believe we've solved this, it was some snarky bug.
