### ISSUE TITLE
Be able to refer to protocol state inside new transaction types

### ISSUE THREAD

**Issue by es92** [CodaProtocol/coda#2536]
Some new transaction types we would like to support (locked accounts, computations referring to time) would need to refer to the protocol state. However, transactions in the staged ledger cannot refer to the protocol state right now.

We could store the latest protocol state at the root of the staged ledger, and inject an update whenever we inject a coinbase into the staged ledger to fix this and be able to refer to the current protocol state.

**Comment by enolan** [comment]
The transaction signer would need to know ahead of time what block it's
going into, which isn't guaranteed.

**Comment by imeckler** [comment]
One proposal is to include a protocol-state hash in the transaction SNARK's input and for coinbases to additionally "cons on" the new protocol state to the existing hash. I.e., compute

```ocaml
new_state_hash = Protocol_state.hash {
  some_protocol_state 
  with previous_state_hash = old_state_hash 
} 
```

The trouble is that when we merge back into the blockchain SNARK, there is no way of telling whether the protocol state hash written in the transaction SNARK's input is actually an ancestor of the current protocol state without looking an unknown distance into the past of the hash chain which would kind of suck.

**Comment by imeckler** [comment]
After discussing briefly with @es92 I think we could accomplish this by sticking some more data in the pending coinbase data-structure.

**Comment by imeckler** [comment]
Main remaining issue: Possibly an off by one error somewhere in interval union. length_in_bits wrong somewhere is my guess.

**Comment by psteckler** [comment]
It was an off-by-two error due to a hack that did not consider the curve size.

CI passes now, should be ready to review after making sure PR is clean.
