### ISSUE TITLE
mnt-753 curve build crashes - precomputed_values.ml

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#2559]
Medium (753-bit) curves are failing in CI and re-produced locally.

```
export DUNE_PROFILE=testnet_postake_medium_curves
make build
...
  gen_values lib/precomputed_values/precomputed_values.ml (exit 1)
(cd _build/default/lib/precomputed_values && gen_values/gen_values.exe precomputed_values.ml)
(((pid 5860) (thread_id 0)) "2019-05-28 20:28:20.666293923Z"
 "unhandled exception in Async scheduler"
 ("unhandled exception"
  ((monitor.ml.Error
    "Assert_failure lib/precomputed_values/gen_values/gen_values.ml:58:4"
    ("Raised at file \"lib/precomputed_values/gen_values/gen_values.ml\", line 58, characters 4-75"
     "Called from file \"lib/precomputed_values/gen_values/gen_values.ml\", line 82, characters 16-35"
     "Called from file \"lib/precomputed_values/gen_values/gen_values.ml\", line 100, characters 14-27"
     "Called from file \"src/deferred1.ml\", line 17, characters 40-45"
     "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
     "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
     "Caught by monitor main"))
   ((pid 5860) (thread_id 8)))))
```

**Comment by jkrauska** [comment]
@cmr I'm not sure what this might have to do with async.

**Comment by cmr** [comment]
It doesn't have anything to do with async, async happens to have the only exception handler in that process.

The assertion that's failing tries to guarantee that proofs we produce can verify. This one didn't. Why?

**Comment by cmr** [comment]
@imeckler 	bug somewhere in the curve code?

**Comment by imeckler** [comment]
Odd -- I will take a look tomorrow or Thursday.

**Comment by jkrauska** [comment]
Reference: same error in CI
https://circleci.com/gh/CodaProtocol/coda/133885

**Comment by mrmr1993** [comment]
After a bisect, it seems the failure (and really long runtimes for key generation) started with #2526.

**Comment by mrmr1993** [comment]
Bisecting the PR itself points to 619c1cab1c90d5db8d30c0fef778db7796d678e5, and reverting #2526 (d31441724ae86f5c1bcbcfba22d620af54584de0) does indeed compile for me locally. I'm completely stumped.

**Comment by mrmr1993** [comment]
Closing, #2715 and #2720 should have fixed this. Still not sure what the underlying cause was, but will investigate and fix on the snarky side.

**Comment by mrmr1993** [comment]
Q
