### ISSUE TITLE
What is MNT-753 please?

### ISSUE THREAD

**Issue by vadym-f** [CodaProtocol/coda#2574]
Where/how MNT-753 was defined, and
is there a complementary curve to create a cycle like MNT 4-6?

**Comment by jkrauska** [comment]
Yes -- there is a pair.

Here are some notes from our Snark Challenge program.

https://codaprotocol.github.io/snark-challenge/MNT4753.html#cQ==
https://codaprotocol.github.io/snark-challenge/MNT6753.html#cQ==
