### ISSUE TITLE
Make all warnings into errors

### ISSUE THREAD

**Issue by imeckler** [CodaProtocol/coda#2578]
Our code currently has many warnings. These should be turned into errors.

@psteckler says should be done 06-07-2019 in coda repo

**Comment by psteckler** [comment]
Currently, there's a file `src/dune`, which is actually an `.ml` file, which looks to be attempting to set most warnings as errors (and do some other stuff based on the build profile). (Note: there should be a comment describing what this file does, in fact).

Lots of library individual `dune` files have `flags` clauses containing `warn-error` entries, which I'm supposing override the global default. In all cases that I can see, those entries make the warning just warnings, and not errors.

Note: Most of the flag clauses add `-short-paths`. Can that be added to the default?

So a way to resolve this issue would be to remove the overriding clauses, one at a time, and remove fix the offending code. If it's unclear how to fix the code, the code owner should be consulted.

In some cases, there may be a reason not to change the code: @deepthiskumar mentioned a case where it's handy to have unused values for future use. In that case, suppressing the warning in the code via `@@@warning` could be OK. That has much narrower scope than a dune clause, and is easily grep'able.

**Comment by psteckler** [comment]
Did this for `coda` and for `snarky`.
