### ISSUE TITLE
Fix Consensus.Hooks.required_local_state_sync to handle all cases

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#2581]
Using required_local_state_sync after a bootstrap would cause nodes to accidentally miss updating the current epoch ledger for some reason. A hack has been put in place in order to resolve the issue for now, but we should review what is wrong with the original function and make that work.

https://github.com/CodaProtocol/coda/commit/d71aa917d10f13e3d1ea111932fe47d504d0d1a8#diff-3c8136d8e64556b42357f55c9a026f8cR2250

**Comment by imeckler** [comment]
@ghost-not-in-the-shell fixed
