### ISSUE TITLE
Joining Proposer - banned before bootstrap 

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [CodaProtocol/coda#2642]
The current implementation of proposer has a bug related to bootstrap.

Assuming one proposer is turned off and then back on. Assuming the proposer didn't receive any transition from the network, it didn't yet know that it is out of sync with the network. According to its local information, it would propose next because it won the slot. So it proposes a garbage transition and broadcast to the network which causes other nodes ban it. Therefore, it would never bootstrap successfully.

**Comment by cmr** [comment]
#2642 is closely related.
