### ISSUE TITLE
min_length_of_epoch 0 

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [CodaProtocol/coda#2643]
Under current implementation, the min_length_of_epoch would always be set to 0 at the very beginning in testnet because when the first transition is being proposed, there's a lot of empty epoch before it.

**Comment by nholland94** [comment]
Let's discuss this with @es92 soon. I believe the most sensible thing to do here is to enforce that networks always start during the genesis epoch. I'm concerned that adding special rules for this edge case will potentially open up some new long fork vulnerabilities related to creating new forks from genesis with blank epochs in between. Also, this is an edge case that we will only ever encounter during testing, and we already avoid it in our integration tests by using the time offset. We could just do the same thing on our testnets.

**Comment by cmr** [comment]
https://github.com/CodaProtocol/coda/pull/2676 should fix this, but is currently blocked
