### ISSUE TITLE
rpc port doesn't start until after ~60s (after bootstrap)

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#2655]
With recent changes to how we start the daemon, you cannot access the rpc port (code client status) until after bootstrap is complete.

Please confirm/review?

**Comment by psteckler** [comment]
The delay depends on a consensus constant derived from the profile. Here's the code:

https://github.com/CodaProtocol/coda/blob/master/src/app/cli/src/coda.ml#L445

**Comment by psteckler** [comment]
According to @ghost-not-in-the-shell, this is a temporary situation.

(There should be a comment in the code to describe its status.)
