### ISSUE TITLE
crash: bootstrapping proposer --> "write to closed pipe" error

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#2657]
Shortly after bootstrapping a proposer, we get a "write to closed pipe" error.

bootstrap appears to work fine, but after a short time (when the proposer proposes its first block?) the daemon crashes.

log attached.

[coda.log.save.gz](https://github.com/CodaProtocol/coda/files/3292109/coda.log.save.gz)

**Comment by cmr** [comment]
This one fixed I think.
