### ISSUE TITLE
Query and Clear current Trust Scores

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#2658]
a cli or graphql mode to query and optionally clear (zero out) the trust score (ban state) for a current IP would be very helpful in debugging trust conditions on testnets.

We have observed occasional behavior with lowers trust scores for peers.

Having the ability to query and zero out a trust score for a given ip on a local machine would allow us to further test trust behaviors.

**Comment by psteckler** [comment]
#2680 implements the query part.

**Comment by psteckler** [comment]
#2684 implements the zero/reset part.

**Comment by jkrauska** [comment]
Would also really like a query all to list all IPs in trust db.
(simplification, all non 0 IPs)
