### ISSUE TITLE
Persist epoch ledgers

### ISSUE THREAD

**Issue by emberian** [CodaProtocol/coda#2661]
We should be writing the epoch ledger snapshots to disk. Right now when we restart a daemon we lose these snapshots and need to sync them.

**Comment by cmr** [comment]
Current thought is that syncing these isn't that much worse than a naive approach to persisting these, so we want to just do this right.

**Comment by imeckler** [comment]
@nholland94 proposes every epoch we bin_io the epoch ledger and write it to disk.

**Comment by nholland94** [comment]
Using `bin_io` for the epoch ledger should scale fine up to at least 100k accounts. We will likely need something more sophisticated to scale further, but we may be able to do this for a while due to how infrequently the epoch ledgers are actually updated.

**Comment by imeckler** [comment]
According to @cmr / @psteckler our fork of rocksdb has an API for making live copies/snapshots of the database so we can just make a copy of the rocksdb for the epoch ledger.

**Comment by imeckler** [comment]
@bkase to give @ghost-not-in-the-shell a pointer in how to use "LLDB"

**Comment by psteckler** [comment]
> our fork of rocksdb has an API for making live copies/snapshots 

In fact, the vanilla `ocaml-rocksdb` has a snapshot facility, we don't need the additional `Backup` machinery in our fork.
