### ISSUE TITLE
Benchmark important operations

### ISSUE THREAD

**Issue by cmr** [CodaProtocol/coda#2663]
- Staged_ledger.apply_diff
- Various transition frontier stuff
- Masks/ledger ops
- Database/persistence in general
- Transaction pool validation (new transactions, bootstrap, reorg/best-tip-path changes)
- SNARK verification time
- SNARK proving time (transaction snark profiler is there, but not blockchain snark)
- Pedersen hashing
- VRF evaluations

**Comment by psteckler** [comment]
We have an issue #1439 to create `ppx_bench` scaffolding. Should we do that now for this issue?

**Comment by enolan** [comment]
One more: signing user commands

**Comment by psteckler** [comment]
#2766 contains benchmarks for Pedersen hashing (chunked and vanilla).

**Comment by psteckler** [comment]
#2773 has benchmarks for VRF evaluations.

**Comment by psteckler** [comment]
Created individual issues for benchmarking particular items; closing this catchall issue.
