### ISSUE TITLE
Remove duplicated information in Staged_ledger_diff

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#2671]
A `Staged_ledger_diff.t` has a field called `prev_hash` which is just a duplicate of the information inside of a blockchain state. This should be removed since a staged ledger diff is always sent around via an external transition, which includes the associated blockchain state as well. Having these two be separate both adds unnecessary size to our external transition size, but also is a security concern since we need to always make sure those two fields match so that someone can't easily lie about the information encoded in the snark.

**Comment by cmr** [comment]
Closed by https://github.com/CodaProtocol/coda/pull/2724
