### ISSUE TITLE
Problems with chain reorganization PR

### ISSUE THREAD

**Issue by enolan** [CodaProtocol/coda#2674]
I should've looked at it before merging. There are some problems:
* ["status for whenever the best tip changes"](https://github.com/CodaProtocol/coda/blob/773d9dc2b894fbfd8b240b5fe57f4c1e116c07da/src/app/cli/src/graphql.ml#L242) in the GraphQL API docs should be "status for whenever the blockchain is reorganized" or something. The best tip changes every time the current best tip is extended, as well as in reorgs.
* Nitpicky, but in the transaction pool tests, if `removed_user_commands` is non-empty, `reorg_best_tip` should be true. This is violated [here](https://github.com/CodaProtocol/coda/blob/773d9dc2b894fbfd8b240b5fe57f4c1e116c07da/src/lib/network_pool/transaction_pool.ml#L727) and [here](https://github.com/CodaProtocol/coda/blob/773d9dc2b894fbfd8b240b5fe57f4c1e116c07da/src/lib/network_pool/transaction_pool.ml#L650).
* [The logic for determining if a reorg happened](https://github.com/CodaProtocol/coda/blob/773d9dc2b894fbfd8b240b5fe57f4c1e116c07da/src/lib/transition_frontier/diff.ml#L342) in `transition_frontier/diff.ml` is wrong. The `New_best_tip` event is emitted whenever the best tip changes, not only in reorgs. You either need to check if the `parent` field is equal to the previous best tip, or modify the way the event works.

**Comment by cmr** [comment]
Oops, I severely misread this code:

https://github.com/CodaProtocol/coda/blob/master/src/lib/transition_frontier/transition_frontier.ml#L857-L873

Of course, new blocks extending the old best tip are taken over the new best tip. Sorry for leading you astray @bkase.
