### ISSUE TITLE
crash: failed to synchronize epoch ledger

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#2681]
crash when trying to join a testnet

coda version: 0.1.148107-CI

trying joining after 716 blocks, 11 epochs

crash info
{
    "crash_timestamp": 1560972561.771658,
    "filename": "./test-coda/coda.log",
    "full_error": "
(monitor.ml.Error \"failed to synchronize epoch ledger\"
 (\"Raised at file \\\"src/error.ml\\\" (inlined), line 9, characters 14-30\"
  \"Called from file \\\"lib/bootstrap_controller/bootstrap_controller.ml\\\", line 368, characters 18-31\"
  \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"
  \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"
  \"Called from file \\\"src/job_queue.ml\\\", line 170, characters 6-47\"
  \"Caught by monitor coda\"))
",
    "hostname": "20190613_us-west-2_joiner_0.us-west-2",
    "signature": "51b27accd4b1bdde837552a3f652394f"
}
[coda.log-failed_to_synchronize_epoch_ledger.gz](https://github.com/CodaProtocol/coda/files/3307686/coda.log-failed_to_synchronize_epoch_ledger.gz)

**Comment by cmr** [comment]
#2659 should help with this. We're not sure why the epoch ledger wasn't available.

**Comment by cmr** [comment]
We're not currently having epoch ledger sync problems.
