### ISSUE TITLE
crash: Error validating proposed transition frontier dependencies: already in frontier

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#2682]
Crash on proposer
[coda.log.save.gz](https://github.com/CodaProtocol/coda/files/3307697/coda.log.save.gz)

{
    "crash_timestamp": 1560923717.315317,
    "filename": "./test-coda-already_frontier/coda.log",
    "full_error": "(monitor.ml.Error
 \"Error validating proposed transition frontier dependencies: already in frontier\"
 (\"Raised at file \\\"src/result.ml\\\" (inlined), line 158, characters 17-26\"
  \"Called from file \\\"lib/proposer/proposer.ml\\\", line 316, characters 24-1023\"
  \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n  \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"
  \"Called from file \\\"src/job_queue.ml\\\", line 170, characters 6-47\"
  \"Caught by monitor coda\"))
",
    "hostname": "20190613_us-east-1_proposer_0.us-east-1",
    "signature": "a63663f59bb12ed7bff9215e9038fc03"
}

**Comment by cmr** [comment]
We think this was caused by bad testnet configuration (duplicate proposer keys). It shouldn't crash still.
