### ISSUE TITLE
Weird constraint failure

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [CodaProtocol/coda#2692]
I notice that if we set the time_offsets to be true in `test_postake_delegation.mlh` on master branch, the delegation test would reliably fail with the same constraint failure:
```
[2019-6-20 16:24:16.952734]Prover: Prover failed: (Failure
  \"Constraint unsatisfied (unreduced):\
 \nChecked.Assert.equal\
 \nFile \\"src/lib/coda_base/transition_system.ml\\", line 204, characters 19-26\
 \nmain: File \\"src/lib/coda_base/transition_system.ml\\", line 146, characters 4-3218\
 \n\
 \nConstraint:\
 \n(((basic(Equal(Var 155138)(Constant 395754654565682274270685496579507555760086806953488526742827489560727971982309474606226604)))(annotation(Checked.Assert.equal))))\
 \nData:\
 \nEqual 132141901551275416946585507464668283690948011321245924066719182279486834844007726497657220 395754654565682274270685496579507555760086806953488526742827489560727971982309474606226604\")
```

This assertion failure is mysterious to me because just above that assertion we did the check outside snark to make sure the values are equal.

**Comment by ghost-not-in-the-shell** [comment]
This is commit hash for master when find this issue: 30ca7e0205944c3ad0288a927a65fbd17d2c69f5

**Comment by ghost-not-in-the-shell** [comment]
I made a branch for this: https://github.com/CodaProtocol/coda/tree/bug/assertion_failure_in_transition_system

To reproduce the failure, just run `./scripts/test.py run "test_postake_delegation:*"`

**Comment by nholland94** [comment]
Took a look at this some. The `as_prover` check that compares the states in and out of the snark was no longer being executed due to a change in the snarky monad interpreter. I fixed that (going to put up a PR soon), and got a sexp diff of the two states. It looks like the vrf evaluations are different in and out of the snark. Working on checking why they might be different now.

**Comment by nholland94** [comment]
FWIW, the checkpoints are also different, though I don't have a full enough picture of how checkpoints are implemented in the snark to know whether or not this will contribute to a constraint failure or not. Either way, vrf evaluations being different will certainly cause this.

**Comment by nholland94** [comment]
I confirmed that the delegator account indices are the same in and out of the snark. The constraints that exist between the delegator field of the winner account and the public key for evaluating the VRF appear to make it impossible to provide an incorrect keypair and make it this far. So, I'm left uncertain as to what is different between the two.

**Comment by cmr** [comment]
The seed being used inside the snark and outside the snark differ according to the latest logs from @ghost-not-in-the-shell's branch, during the first slot in the first new epoch. Is the wrong epoch data being selected? Or is the epoch data being updated incorrectly?

**Comment by ghost-not-in-the-shell** [comment]
We finally found that the constraint failure is caused by a bug in select_epoch_data. And this PR fixed that bug https://github.com/CodaProtocol/coda/pull/2676/commits/a67b02f8b49c23435fb4d07d9285eab17bcf28c6
