### ISSUE TITLE
OCaml 4.09.0 (or 4.08.1 (or 4.08.0))

### ISSUE THREAD

**Issue by imeckler** [CodaProtocol/coda#2743]

**Comment by psteckler** [comment]
`ppx_tools` is not in OPAM for 4.08, though it's updated in Github.

Do we wait for OPAM to catchup, or put `ppx_tools` in `src/external`?

**Comment by imeckler** [comment]
I think we can just wait as we're not in a big rush -- I made an issue here https://github.com/ocaml-ppx/ppx_tools/issues/73

**Comment by psteckler** [comment]
`ppx_tools` is now available for 4.08. But some other ppx-related packages are not yet caught up, like `ppxlib`. That package will install, but it uses 4.07 parse trees, making it incompatible with other packages, like `ppx_deriving`, which use 4.08 trees.

Current plan: wait for the ecosystem to catch up to 4.08 before migrating.

Other issues: a signature constraint on recursive modules in `Cached` is an error in 4.08.

Also, `[%%error` for `optcomp` doesn't seem to work with 4.08, for whatever reason.

**Comment by psteckler** [comment]
OCaml 4.08.1 was just released.

**Comment by psteckler** [comment]
Jane Street's `ppx_module_timer` is not ready for 4.08.x. 

There was code committed within the last few days that appears to do the upgrade, not yet in OPAM.

Meanwhile, I rebased my tentative branch on `develop`:  https://github.com/CodaProtocol/coda/tree/feature/ocaml-4.08.1

**Comment by psteckler** [comment]
Ocaml 4.09.0 is released: https://ocaml.org/releases/4.09.0.html

**Comment by psteckler** [comment]
OCaml 4.10 was due in January 2020; there were issues that have stalled the release.

**Comment by psteckler** [comment]
Superseded by #5413.
