### ISSUE TITLE
TestNet Crash 07/02

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#2768]
Tried launching a TestNet right now and am getting this crash log: 

```
💀 Coda's Daemon Crashed. The Coda Protocol developers would like to know why!

  Please:
    Open an issue:
      https://github.com/CodaProtocol/coda/issues/new

    Tell us what you were doing, and paste the last 20 lines of log messages.
    And then paste the following:

    (monitor.ml.Error (B58.Alphabet.Invalid_base58_character)
  ("Raised at file \"lib/read.mll\", line 712, characters 13-36"
    "Called from file \"lib/read.mll\", line 241, characters 23-47"
    "Caught by monitor coda"))
```

cc @jkrauska @psteckler @bkase

**Comment by yourbuddyconner** [comment]
@Schmavery and I have tracked it down to the pk formatting by running this command: 

```
coda client dump-keypair -privkey-path testkeys/high0
```

which results in the following output: 

```
Error: (B58.Alphabet.Invalid_base58_character)
```

**Comment by psteckler** [comment]
What's the text in `testkeys/high0` ?

**Comment by yourbuddyconner** [comment]
@psteckler https://github.com/CodaProtocol/coda-automation/blob/master/ansible/testkeys/high0

**Comment by psteckler** [comment]
Yes, the `ciphertext` field there contains text that is not base58. Can those testkeys be regenerated?

**Comment by yourbuddyconner** [comment]
I'll look into it.

**Comment by yourbuddyconner** [comment]
Regerated the keys in https://github.com/CodaProtocol/coda-automation/pull/47/, closing.
