### ISSUE TITLE
Ledger Merkle Roots would be shorter in base58

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#2771]
Current representation in 'coda client status'

```
Ledger Merkle Root:                            11284745854993566957561933976012118315266923949698751354822419068004161815438744430923460300074834988707929098284805499363767190036771878548767839630776686047687471875456702927579368426320771315881200014912291254872283048593941
```

I'm thinking 'base58 all the things!' is a reasonable choice.

Can you look at changing the status line and logging lines dealing with merkle roots to use base58 representation?

**Comment by psteckler** [comment]
Definitely fixed for `client status`, and probably for logging lines (`Ledger_hash.to_string` yields Base58Check).

Closing, but keep an eye out for any log lines that don't conform to this expectation.
