### ISSUE TITLE
Remove the second input from wrap_input

### ISSUE THREAD

**Issue by imeckler** [CodaProtocol/coda#2803]
This is a SNARK optimization that would remove about 3009 ~= (2*753 + 5/3 * 754) constraints from the blockchain SNARK.

The idea is the following:

The input to the Tock-based wrap SNARK is passed along directly to the Tick-based SNARK it is wrapping. So, we need to be able to encode the input to the Tick SNARK using a Tock field element. 

Because the Tock field is smaller than the Tick field, this seems to require two field elements. One for the for the first `n - 1` bits of the field element you want to represent, and one for the last bit. Having an extra input however has a high cost: it adds one G1 to the verification key of the wrap SNARK which means one G1's worth of hashing has to be done during recursive verification of a wrap SNARK.

The cost of hashing one G1 element is
- 753 constraints to unpack the x coordinate
- ~1000 constraints to faithfully unpack the y coordinate and extract the low bit
- (5 / 3) * 754 constraints for Pedersen-hashing the bits of the x coordinate plus the low bit of the y coordinate.

# Why one input should suffice

The second bit is only useful if the Tick field element which is the input to the inner SNARK exceeds the order of the Tock field. The absolute value of the difference between these two fields is roughly 2^377. So there are roughly that many "bad points" in the Tick field which cannot be represented using a Tock field element.

This is tiny compared to the order of the fields, which are roughly 2^753. In our case the inner SNARK unhashes its public input, so we know that we only need to encode field elements which are in the image of the Pedersen hash function. I conjecture that it is intractible to find a input M such that Pedersen(M) is one of the 2^377 bad points. 

I think there might be other reasons this is OK too, but I haven't thought about it fully yet.

**Comment by daira** [comment]
> I conjecture that it is intractible to find a input M such that Pedersen(M) is one of the 2<sup>377</sup> bad points.

That's entirely plausible, but if you explicitly check that the hash is in range (using an optimized comparison as in the Zcash protocol spec Appendix A.3.2.2), you don't even need to make that assumption, and you'd still be saving ~2000 constraints.
