### ISSUE TITLE
Test prover fees going to not-yet-existing accounts

### ISSUE THREAD

**Issue by cmr** [CodaProtocol/coda#2813]
https://github.com/CodaProtocol/coda/pull/557 added account creation but I don't think it ever tests fees going to accounts that don't yet exist. In theory it works fine, in practice I'm not sure we've ever tested that behavior.

**Comment by enolan** [comment]
The new (in progress) staged ledger tests test this, on a mask. Might be worth testing it more directly as well though?

**Comment by cmr** [comment]
That's probably enough but I guess we should exercise it in an integration test as well

**Comment by imeckler** [comment]
@cmr has tested this.
