### ISSUE TITLE
Investigate why Matt keeps getting banned

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#2855]
Proposing on slot 3 away from real

**Comment by mrmr1993** [comment]
Posting my logs to the discord channel in case they're of use.

**Comment by psteckler** [comment]
Matthew's machine apparently does not have time synchronization enabled, which could explain the banning.

I ran a node on AWS over the weekend, seems still to be chugging along on Monday morning.

**Comment by psteckler** [comment]
Enabling time synch appears to fix the problem.

We should tell test net users to enable time sync.
