### ISSUE TITLE
Audit Logger.warn and Logger.error for readability

### ISSUE THREAD

**Issue by cmr** [CodaProtocol/coda#2873]
# `Logger.error`
- [x] [src/lib/snark_worker/prod.ml](https://github.com/codaprotocol/coda/blob/master/lib/snark_worker/prod.ml)
- [x] [src/lib/snark_worker/functor.ml](https://github.com/codaprotocol/coda/blob/master/lib/snark_worker/functor.ml)
- [x] [src/lib/consensus/proof_of_stake.ml](https://github.com/codaprotocol/coda/blob/master/lib/consensus/proof_of_stake.ml)
- [x] [src/lib/bootstrap_controller/bootstrap_controller.ml](https://github.com/codaprotocol/coda/blob/master/lib/bootstrap_controller/bootstrap_controller.ml)
- [x] [src/lib/coda_networking/coda_networking.ml](https://github.com/codaprotocol/coda/blob/master/lib/coda_networking/coda_networking.ml)
- [x] [src/lib/prover/prover.ml](https://github.com/codaprotocol/coda/blob/master/lib/prover/prover.ml)
- [x] [src/lib/coda_base/transition_system.ml](https://github.com/codaprotocol/coda/blob/master/lib/coda_base/transition_system.ml)
- [x] [src/lib/staged_ledger/staged_ledger.ml](https://github.com/codaprotocol/coda/blob/master/lib/staged_ledger/staged_ledger.ml)
- [x] [src/lib/secrets/wallets.ml](https://github.com/codaprotocol/coda/blob/master/lib/secrets/wallets.ml)
- [x] [src/lib/cache_lib/cache_lib.ml](https://github.com/codaprotocol/coda/blob/master/lib/cache_lib/cache_lib.ml)
- [x] [src/lib/cache_lib/impl.ml](https://github.com/codaprotocol/coda/blob/master/lib/cache_lib/impl.ml)
- [x] [src/lib/proposer/proposer.ml](https://github.com/codaprotocol/coda/blob/master/lib/proposer/proposer.ml)
- [x] [src/lib/web_client_pipe/web_client_pipe.ml](https://github.com/codaprotocol/coda/blob/master/lib/web_client_pipe/web_client_pipe.ml)
- [x] [src/lib/transition_frontier_controller_tests/test_transition_frontier_persistence.ml](https://github.com/codaprotocol/coda/blob/master/lib/transition_frontier_controller_tests/test_transition_frontier_persistence.ml)
- [ ] [src/lib/coda_lib/coda_subscriptions.ml](https://github.com/codaprotocol/coda/blob/master/lib/coda_lib/coda_subscriptions.ml)
- [x] [src/lib/transition_router/initial_validator.ml](https://github.com/codaprotocol/coda/blob/master/lib/transition_router/initial_validator.ml)
- [x] [src/lib/coda_net2/coda_net2.ml](https://github.com/codaprotocol/coda/blob/master/lib/coda_net2/coda_net2.ml)
- [x] [src/lib/gossip_net/gossip_net.ml](https://github.com/codaprotocol/coda/blob/master/lib/gossip_net/gossip_net.ml)
- [x] [src/lib/transition_handler/breadcrumb_builder.ml](https://github.com/codaprotocol/coda/blob/master/lib/transition_handler/breadcrumb_builder.ml)
- [x] [src/lib/transition_handler/processor.ml](https://github.com/codaprotocol/coda/blob/master/lib/transition_handler/processor.ml)
- [x] [src/app/cli/src/web_pipe.ml](https://github.com/codaprotocol/coda/blob/master/app/cli/src/web_pipe.ml)
- [x] [src/app/cli/src/coda_worker.ml](https://github.com/codaprotocol/coda/blob/master/app/cli/src/coda_worker.ml)
- [x] [src/app/cli/src/coda_run.ml](https://github.com/codaprotocol/coda/blob/master/app/cli/src/coda_run.ml)
- [x] [src/app/cli/src/coda.ml](https://github.com/codaprotocol/coda/blob/master/app/cli/src/coda.ml)
- [x] [src/lib/kademlia/membership.ml](https://github.com/codaprotocol/coda/blob/master/lib/kademlia/membership.ml)
- [x] [src/lib/transition_frontier_persistence/transition_storage.ml](https://github.com/codaprotocol/coda/blob/master/lib/transition_frontier_persistence/transition_storage.ml)
- [x] [src/lib/transition_frontier_persistence/transition_frontier_persistence.ml](https://github.com/codaprotocol/coda/blob/master/lib/transition_frontier_persistence/transition_frontier_persistence.ml)

# `Logger.warn`

- [x] [src/lib/pipe_lib/strict_pipe.ml](https://github.com/codaprotocol/coda/blob/master/lib/pipe_lib/strict_pipe.ml)
- [x] [src/lib/coda_networking/coda_networking.ml](https://github.com/codaprotocol/coda/blob/master/lib/coda_networking/coda_networking.ml)
- [x] [src/lib/staged_ledger/staged_ledger.ml](https://github.com/codaprotocol/coda/blob/master/lib/staged_ledger/staged_ledger.ml)
- [x] [src/lib/coda_p2p/coda_networking.ml](https://github.com/codaprotocol/coda/blob/master/lib/coda_p2p/coda_networking.ml)
- [x] [src/app/cli/src/coda_delegation_test.ml](https://github.com/codaprotocol/coda/blob/master/app/cli/src/coda_delegation_test.ml)
- [x] [src/app/cli/src/coda_worker_testnet.ml](https://github.com/codaprotocol/coda/blob/master/app/cli/src/coda_worker_testnet.ml)
- [x] [src/app/cli/src/coda.ml](https://github.com/codaprotocol/coda/blob/master/app/cli/src/coda.ml)
- [x] [src/app/cli/src/coda_commands.ml](https://github.com/codaprotocol/coda/blob/master/app/cli/src/coda_commands.ml)
- [x] [src/lib/coda_lib/coda_lib.ml](https://github.com/codaprotocol/coda/blob/master/lib/coda_lib/coda_lib.ml)
- [x] [src/lib/coda_net2/coda_net2.ml](https://github.com/codaprotocol/coda/blob/master/lib/coda_net2/coda_net2.ml)
- [x] [src/lib/transition_router/initial_validator.ml](https://github.com/codaprotocol/coda/blob/master/lib/transition_router/initial_validator.ml)
- [x] [src/lib/ledger_catchup/ledger_catchup.ml](https://github.com/codaprotocol/coda/blob/master/lib/ledger_catchup/ledger_catchup.ml)
- [x] [src/lib/transition_handler/processor.ml](https://github.com/codaprotocol/coda/blob/master/lib/transition_handler/processor.ml)
- [x] [src/lib/transition_frontier/transition_frontier.ml](https://github.com/codaprotocol/coda/blob/master/lib/transition_frontier/transition_frontier.ml)
- [x] [src/lib/kademlia/membership.ml](https://github.com/codaprotocol/coda/blob/master/lib/kademlia/membership.ml)

**Comment by cmr** [comment]
https://sketch.sh/s/mzsvf0EmNZ8x4sLUjjsQZo/ assignment

**Comment by enolan** [comment]
will look at `coda_lib.ml` now
