### ISSUE TITLE
Make `constraint-system-digests` independent of the verification keys in use

### ISSUE THREAD

**Issue by cmr** [CodaProtocol/coda#2886]
Maybe find some way to zero out those inputs?

**Comment by mrmr1993** [comment]
@cmr this worries me a bit, can you clarify what we're trying to do here? AFAIK when the R1CS depends on the other verification keys then any change to those keys needs a different proving key, and it seems like we only use the digests to identify the keys.

**Comment by cmr** [comment]
ihm came up with a good metaphor: "like we have a graph of constraint system generators, where randomness gets fed in the top, and we only care when the graph itself changes"

The intent is to only use the hash of the entire `constraint-system-digests` output, as a key into a cache of pregenerated P/V keys. If any of them change, we regenerate keys.

**Comment by mrmr1993** [comment]
Thanks, that makes sense.

Perhaps we should be storing the keys as `$keyhash-$dependentkeyhashes` and showing the same in `constraint-system-digests`, so that the information returned by `constraint-system-digests` still relates to to the keys in a usable way?

**Comment by cmr** [comment]
I believe this has been done.
