### ISSUE TITLE
error validating the wrap verification data on mighty-wombat

### ISSUE THREAD

**Issue by enolan** [CodaProtocol/coda#2890]
I see the massive wall of text in the daemon log: https://gist.githubusercontent.com/enolan/387abcf7155865c9b46979b94ec24bf0/raw/0f73f869848a14ff3f388dc55a98c41eaf45909d/verifier__prod%2520error. 

I am running a snark worker, so maybe this is a failure validating a SNARK it generated? It hasn't banned any peers. But it looks like it's a blockchain snark since the message includes stuff like `has_ancestor_in_same_checkpoint_window`, and I'm not running a proposer.

[full log here](https://github.com/CodaProtocol/coda/files/3403464/coda.log.txt)

**Comment by bkase** [comment]
Ahh sorry this was a log I added to debug why I couldn't verify any SNARKs. It has since been removed, but was present on the might wombat network binaries. It's safe to ignore these logs
