### ISSUE TITLE
Error when Starting up a node

### ISSUE THREAD

**Issue by pkrasam** [CodaProtocol/coda#2899]
💀 Coda's Daemon Crashed

```
    (monitor.ml.Error
  (Failure
     "Failed to connect to kademlia process: If you are a dev, did you forget to `make kademlia` and set CODA_KADEMLIA_PATH? Try CODA_KADEMLIA_PATH=$PWD/src/app/kademlia-haskell/result/bin/kademlia (Unix.Unix_error \"No such file or directory\" Core.Unix.create_process\
    \n \"((prog coda-kademlia) (args (test 0.0.0.0 \\\"(\\\\\\\"103.217.167.242\\\\\\\", 8303)\\\" \\\"(\\\\\\\"34.216.76.18\\\\\\\", 8303)\\\")) (env (Extend ())))\")\
    \n")
  ("Raised at file \"stdlib.ml\", line 33, characters 17-33"
    "Called from file \"src/deferred1.ml\", line 17, characters 40-45"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
    "Caught by monitor coda"))
```

**Comment by enolan** [comment]
How did you install Coda, and what OS are you using? If you built from source, you need to do what it says and run `make kademlia`.

**Comment by yourbuddyconner** [comment]
Hey @pkrasam, as @enolan indicated, your problem is that the coda-kademlia binary is not present on your system. Please provide more information on your build system and more assistance can be provided.

**Comment by pkrasam** [comment]
Thank you @enolan @yourbuddyconner I downloaded the coda.zip file and it had all the binaries ...see below the directory structure & contents.

<img width="386" alt="coda-daemon-macos" src="https://user-images.githubusercontent.com/4514654/61502971-55afce00-aa19-11e9-92a6-40bef4fa5687.png">

**Comment by yourbuddyconner** [comment]
Hey @pkrasam thanks for that. We're not quite ready to support those binaries, but by all means please stick around until we have a stable release for you.
