### ISSUE TITLE
Extend dump-ledger to a full export for genesis

### ISSUE THREAD

**Issue by cmr** [CodaProtocol/coda#2935]
The idea here is to export a `testnet_postake_ledger.ml` from a running testnet, so we can start the new one with the same account state. Right now `coda advanced dump-ledger` will output a sexp.

**Comment by psteckler** [comment]
So basically, generate OCaml from the sexp? Should that be in `coda.exe`, or in a script?

**Comment by cmr** [comment]
We want this for the next release. As discussed: yes, generate OCaml from something that we can easiliy export. `dump-ledger` exports an `%{sexp:Account.t list}` which should be good enough. The existing `Genesis_ledger.Functor.*` functors all take partial `account_data` records, except `Make_with_base`. 

At the end of the day we want some script that can talk to running Coda daemon, exports what needs to be, and formats into an `ml` output easy to substitute for `src/lib/genesis_ledger/testnet_postake_ledger.ml`
