### ISSUE TITLE
Allow REST Port Listener to be Configurable

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#2937]
Right now, the Daemon port automatically binds the REST Port to `localhost`. This is a good idea for security, however it's a non-starter when the Daemon is in a container cluster and must be communicated with by other containers. 

([This line here](https://github.com/CodaProtocol/coda/blob/release/beta/src/app/cli/src/coda_run.ml#L226)) 

We should add an `--expose-rest-port` flag that will optionally bind the REST Port to `0.0.0.0` to enable this use-case. 

cc @figitaki @Schmavery @bkase

**Comment by yourbuddyconner** [comment]
p.s. this currently blocks the Faucet bot as I would like to use the docker container architecture I mentioned for this purpose

**Comment by cmr** [comment]
https://github.com/CodaProtocol/coda/pull/2942 does this, argument is named `-insecure-rest-server`
