### ISSUE TITLE
[Bug] Kademlia Reports Erroneous Port to Peers When Using Docker Bridge Networking

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#2947]
This one is a little weird and convoluted...

- I have the Coda Daemon running in a Docker container. 
- I have the Daemon ports bound to localhost `--port 8304:8304`, which involves passing traffic through the Docker network.
- The seed is recognizing the node running on my IP, but at a super high port: 
`Peers:                                         Total: 8 (<MY-IP>: 51657 ..........)`

When investigating, running `lsof -i` inside the container, I find this: 
`coda        7 root   54u  IPv4 265055      0t0  TCP c36a8d2fd407:8304->172.18.0.1:51810 (ESTABLISHED)`

This is expected, as `172.18.0.1` is the Docker Network Controller's IP and it is routing traffic for us. 

Now, I believe this weird behavior to be a bug, or at the very lest not the desired behavior. Kademlia is reporting the of the intermediate connection, and not the port bound externally on the host (and also the default). 

EDIT: Actually I am feeling less confident about my hunch of Kademlia reporting the connection to the Docker Network to the gossip network, but I still feel like the Docker Network is interacting with Kademlia in a weird way.

**Comment by yourbuddyconner** [comment]
Okay, actually more confident now. I rebooted everything, and the seed node was registering this: 
`Peers:                                         Total: 8 (45.17.136.92:51396 .....`

 I ran `lsof -i` on the MacOS side of things and found this: 

`com.docke 82385 connerswann   20u  IPv4 0x1a067d4ece5b355b      0t0  UDP *:51396`

I believe Kademlia is gossip-ing the osx-side port of its connection with the Docker Network. Why? I am not quite sure.

**Comment by yourbuddyconner** [comment]
Final verdict is that the Docker NAT breaks the UDP functionality of the gossip net.  It should be decided if there is a hard requirement on nodes having a direct connection to their peers or not.

**Comment by yourbuddyconner** [comment]
Another thing to note is that the ethereum client can be run in a docker container, meaning this UDP source port thing is a solved problem... https://github.com/ethereum/go-ethereum/wiki/Running-in-Docker

**Comment by cmr** [comment]
So the external IP + port to bind is passed to the helper, parsed [here](https://github.com/CodaProtocol/coda/blob/master/src/app/kademlia-haskell/app/Main.hs#L118) and used [here](https://github.com/CodaProtocol/coda/blob/master/src/app/kademlia-haskell/app/Main.hs#L131) (which calls [this](https://github.com/CodaProtocol/kademlia/blob/master/src/Network/Kademlia.hs#L179) which uses the external IP and the actual socket differently...). Kinda confusing...

**Comment by yourbuddyconner** [comment]
@cmr this is the dockerfile I am using

`docker build -t coda-docker -f Dockerfile-codaslim .`
```
FROM debian:stretch

# Dependencies
RUN apt-get -y update && \
  DEBIAN_FRONTEND=noninteractive apt-get -y upgrade && \
  DEBIAN_FRONTEND=noninteractive apt-get -y install \
    dumb-init \
    libssl1.1 \
    libprocps6 \
    libgmp10 \
    libgomp1 \
    libffi6 \
    apt-transport-https \
    ca-certificates && \
  rm -rf /var/lib/apt/lists/*

# coda package
RUN echo "deb [trusted=yes] http://packages.o1test.net unstable main" > /etc/apt/sources.list.d/coda.list \
  && apt-get update \
  && apt-get install --force-yes -t unstable coda-testnet-postake-medium-curves=0.0.1-release-beta-020df4e7 -y

ENTRYPOINT ["/usr/bin/dumb-init", "/usr/local/bin/coda"]
```

**Comment by yourbuddyconner** [comment]
Yeah I have never worked with UDP + Docker before, but this behavior is not what I would expect... 

1. Check open ports: 
```
$ lsof -i | grep com.docke
com.docke 82383 connerswann    5u  IPv4 0x1a067d4ec8145f9b      0t0  UDP localhost:60603
com.docke 82385 connerswann   14u  IPv4 0x1a067d4ec8cb39db      0t0 ICMP *:*
com.docke 82385 connerswann   22u  IPv4 0x1a067d4f0d68b1b3      0t0  UDP *:57550
com.docke 82385 connerswann   23u  IPv4 0x1a067d4f0d68c773      0t0  UDP *:56663
com.docke 82385 connerswann   24u  IPv4 0x1a067d4f0d68ca2b      0t0  UDP *:62806
```

2. Run `coda-docker`: `docker run -p "8303:8303/udp" coda-docker daemon -peer silly-grumpuso1test.net:8303 -rest-port 8304 -insecure-rest-server`

3. Check open ports: 
```
$ lsof -i | grep com.docke
com.docke 82383 connerswann    5u  IPv4 0x1a067d4ec8145f9b      0t0  UDP localhost:60603
com.docke 82385 connerswann   14u  IPv4 0x1a067d4ec8cb39db      0t0 ICMP *:*
com.docke 82385 connerswann   18u  IPv4 0x1a067d4f0d68cf9b      0t0  UDP *:61460
com.docke 82385 connerswann   20u  IPv4 0x1a067d4f0d68ed83      0t0  UDP *:52149
com.docke 82385 connerswann   21u  IPv4 0x1a067d4f0d68d253      0t0  UDP *:8303 <--------
com.docke 82385 connerswann   22u  IPv4 0x1a067d4f0d68b1b3      0t0  UDP *:57312
com.docke 82385 connerswann   23u  IPv4 0x1a067d4f0d68c773      0t0  UDP *:60599 <---------
```

4. Check peer for gossiped port: 
`Peers  Total: 8 (45.17.136.92:60599 ................................)`

It really looks to me like Docker is randomly opening a high-numbered port and using it for this UDP session. Why? I have no idea. 
```
docker port ed46a17c1f31
8303/udp -> 0.0.0.0:8303
```
Docker clearly thinks its not doing so however, and the process itself doesn't think so either: 
```
root@ed46a17c1f31:/# lsof -i 
COMMAND   PID USER   FD   TYPE DEVICE SIZE/OFF NODE NAME
coda        6 root   28u  IPv4 340683      0t0  TCP *:37661 (LISTEN)
coda        6 root   29u  IPv4 337573      0t0  TCP ed46a17c1f31:43141->ed46a17c1f31:43079 (ESTABLISHED)
coda        6 root   32u  IPv4 340699      0t0  TCP ed46a17c1f31:40085->ed46a17c1f31:34199 (ESTABLISHED)
coda        6 root   42u  IPv4 343181      0t0  TCP *:8302 (LISTEN)
coda        6 root   45u  IPv4 337580      0t0  TCP *:8304 (LISTEN)
coda        6 root   47u  IPv4 337581      0t0  TCP *:8301 (LISTEN)
exe        79 root    8u  IPv4 339823      0t0  TCP *:43079 (LISTEN)
exe        79 root   10u  IPv4 339826      0t0  TCP ed46a17c1f31:43079->ed46a17c1f31:43141 (ESTABLISHED)
exe        92 root    8u  IPv4 331593      0t0  TCP *:34199 (LISTEN)
exe        92 root   10u  IPv4 331596      0t0  TCP ed46a17c1f31:34199->ed46a17c1f31:40085 (ESTABLISHED)
coda-kade 119 root    3u  IPv4 341531      0t0  UDP *:8303 <----------------------
```

**Comment by cmr** [comment]
I can't seem to reproduce this on Linux...

**Comment by yourbuddyconner** [comment]
It looks to me like when a peer connects to the seed node, its "address" is inferred to be the IP:PORT combo that any datagrams were received from, RATHER than an IP:PORT combo reported by the peer. 

In my view, it shouldn't matter which port the peer is sending UDP packets from, but which port the peer is listening for UDP packets on.

**Comment by cmr** [comment]
We confirmed (using a modified `coda-kademlia`) that the seed node is seeing the high number as the source port. However an strace of the `coda-kademlia` inside the container seems to be `bind`ing to the right ports etc. I'm trying harder to repro.

@yourbuddyconner managed to repro this using docker-in-linux in a VMWare instance on mac. I _should_ be able to repro using docker-in-linux on native linux...

**Comment by cmr** [comment]
I think this might be a macOS-specific weirdness somehow shared with VMware's networking stack?

On my home machine, with this dockerfile:

```Dockerfile
FROM debian:stretch

# Dependencies
RUN apt-get -y update && \
  DEBIAN_FRONTEND=noninteractive apt-get -y upgrade && \
  DEBIAN_FRONTEND=noninteractive apt-get -y install \
    dumb-init \
    libssl1.1 \
    libprocps6 \
    libgmp10 \
    libgomp1 \
    libffi6 \
    apt-transport-https \
    ca-certificates strace && \
  rm -rf /var/lib/apt/lists/*

# coda package
RUN echo "deb [trusted=yes] http://packages.o1test.net unstable main" > /etc/apt/sources.list.d/coda.list \
  && apt-get update \
  && apt-get install --force-yes -t unstable coda-testnet-postake-medium-curves=0.0.1-release-beta-43cb0790 -y

ENTRYPOINT ["/usr/bin/dumb-init", "/usr/local/bin/coda"]
```

I build `docker build -t coda-docker .` and run `docker run -p '8301:8301/tcp' -p '8302:8302/tcp' -p '8303:8303/udp' coda-docker daemon -peer dry-plants.o1test.net:8303`.

I ssh into `dry-plants.o1test.net` and look in `coda client status` and see `157.131.221.53:8303` which is my correct port.

**Comment by enolan** [comment]
just spitballing, but could it have something to do with the way
docker-machine does routing?

**Comment by yourbuddyconner** [comment]
Seeing this error manifest on Kubernetes as well I believe, k8s is listening ports `31234 TCP` and `31235 UDP` and forwarding to container ports `10101 TCP` and `10102 UDP`. 

The seed node is is registering connections from a random high-numbered port and RPC calls are failing as a result: 

```
[2019-8-22 02:10:18.675633]Gossip_net: Connected to some peers []
[2019-8-22 02:14:15.782658]Kademlia__Membership: 34.222.211.93:31360 \"UOP9CY0Jop46jEJblO6C4fnXAMupRk7zdOpfnZ3RJVo=\" on
[2019-8-22 02:14:20.793193]Trust_system__Peer_trust: Decreasing trust for peer "34.222.211.93" due to action Trust_system.Actions.Connected. New trust is -0.000000.
[2019-8-22 02:14:45.782835]Gossip_net: RPC call raised an exception: $exn
$exn = "(\"connection attempt timeout\" 34.222.211.93:31359 src/tcp.ml:120:11)"
[2019-8-22 02:14:45.782887]Gossip_net: Retrieving chain ID failed: refusing to connect to [host : 34.222.211.93, discovery_port : 31360, communication_port : 31359]: $error
$error = "(\"connection attempt timeout\" 34.222.211.93:31359 src/tcp.ml:120:11)"
```
