### ISSUE TITLE
Exception from trace task

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#2948]
This was from anode that had ~47.5k seconds uptime if that’s related. This happened on the daemon process.

```
("Exception raised to 
[Monitor.try_with] that already returned.""This error was captured by a 
default handler in [Async.Log]."(exn(monitor.ml.Error(Failure"traced 
task failed, exception reported to parent monitor")("Raised at file 
\"stdlib.ml\", line 33, characters 17-33""Called from file 
\"src/result.ml\", line 96, characters 19-24""Called from file 
\"src/monad.ml\" (inlined), line 37, characters 20-29""Called from file 
\"src/implementations.ml\", line 493, characters 25-67""Called from file 
\"src/result.ml\", line 151, characters 9-15"))))
```

**Comment by cmr** [comment]
`trace_task` should interpolate the task name into that exception... and possibly keep around a stack trace.

**Comment by imeckler** [comment]
- @deepthiskumar says this happens if you e.g. get balance during bootstrap
- it also happens if you give the wrong port in the get balance command

@cmr says we generally need better error handling around performing client actions during bootstrap

**Comment by cmr** [comment]
Closing in favor of #3025. `trace_task` now includes the task name in that message
