### ISSUE TITLE
Investigate why we frequently jump between boostrap/sync

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#2968]
<img width="749" alt="Screen Shot 2019-07-23 at 9 08 49 PM" src="https://user-images.githubusercontent.com/515445/61764848-6cdf1a80-ad8f-11e9-8934-63f6c58bc3e0.png">

**Comment by o1pranay** [comment]
I noticed that this happens whenever I do `coda client status` - must be connected to the client command somehow

**Comment by o1pranay** [comment]
The daemon also repeats this:
```
2019-07-24 05:07:46 UTC [Info] Coda daemon is now connecting
2019-07-24 05:07:46 UTC [Info] Coda daemon is now listening
```

when you do `coda client status` and the sync status is `Connecting`

**Comment by cmr** [comment]
We aren't switching between these statuses, there's a bug in the logging code.
