### ISSUE TITLE
Local daemon should cache last used nonce for a given sender key - allow for multiple individual txns in one slot

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#2976]
Rather than just looking up what's in the ledger, we should remember the latest nonce. This remembering can be looking up what's inside the transaction pool I think? (though there's a minor race to that)

**Comment by imeckler** [comment]
This data is already tracked in the transaction pool. We will just use the nonce from that. All that is required is to change the get_nonce rpc handler.

**Comment by wu-s-john** [comment]
Oh I'm doing this now

**Comment by enolan** [comment]
Done in #3047
