### ISSUE TITLE
Surface error saying that node is using old version of daemon

### ISSUE THREAD

**Issue by o1pranay** [CodaProtocol/coda#2979]
Users were stuck in bootstrap without realizing that they were using an older version of the daemon - would be good to surface this quicker so they know to download the new version.

Example:
```
jspadaveToday at 4:36 PM
bionic 64bit
coda version
Commit 5d031d6 on branch status-logs-noise
Hmm... I did an apt-get update and dist-upgrade earlier 2day... maybe I did it too early?
```

**Comment by imeckler** [comment]
@cmr says this could be addressed with a stable apt repo. @jkrauska want to do this?

**Comment by imeckler** [comment]
We need to
- mark a tag for releases
- then push to a repo that is only for releases
- then update the docs to say use that repo

**Comment by o1pranay** [comment]
we have a release repo now - can I close this one out @jkrauska ?
