### ISSUE TITLE
Coda Daemon crashed

### ISSUE THREAD

**Issue by chtostoic** [CodaProtocol/coda#2996]
coda daemon -peer hello-coda.o1test.net:8303

(monitor.ml.Error
  (runtime-lib/runtime.ml.E
    "Merkle roots differ after transfer: got unexpected result"
    ((expected
       38932695040467596106866402734597443669063381446628167838929129222958650359402660018169492542114228579857016809663362878702967691140114883880635297843337526424344049903879831696969707777320618038873222528382381697025453708056747)
      (got
        16614876361025011603230697695085370554301275323584479787590866411302392047573659534418116050177771442629407029327750673002858692494540135237949546362363166695549101792654595707467823915385172461099965870109734933066241071519040)
      (Loc src/lib/coda_base/ledger_transfer.ml:25:19)))
  ("Raised at file \"runtime-lib/runtime.ml\", line 28, characters 28-53"
    "Called from file \"runtime-lib/runtime.ml\" (inlined), line 105, characters 27-78"
    "Called from file \"src/lib/coda_base/ledger_transfer.ml\", line 25, characters 19-32"
    "Called from file \"src/lib/coda_lib/coda_lib.ml\", line 352, characters 4-73"
    "Called from file \"src/lib/coda_lib/coda_lib.ml\", line 394, characters 12-52"
    "Called from file \"src/deferred0.ml\", line 56, characters 64-69"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
    "Caught by monitor coda"))

**Comment by o1pranay** [comment]
@chtostoic Thanks for reporting this - it is a known issue and being tracked here: #2991. Closing this one out as it is a dupe
