### ISSUE TITLE
Unit tests time out with medium curves on CircleCI.

### ISSUE THREAD

**Issue by enolan** [CodaProtocol/coda#3024]
The staged ledger tests alone take more than 2h20m on my laptop. I gave up and Ctrl-Ced after that. We need to either optimize or tweak the parameters enough to make them run in a reasonable amount of time. [Here](https://drive.google.com/file/d/1wIDbb5qzBCt5jLpAyLVh5K9snRiQUj3U/view?usp=sharing)'s a perf script from running the first test, subsampled from 100hz to 10hz.

**Comment by cmr** [comment]
We switched one of the medium curve builders to a large box. Maybe that will help with the timeout? Probably not. This is absurdly long.

**Comment by enolan** [comment]
They also fail, so it's possible a lot of the time is spent shrinking. We can see if it improves after #2609 lands.

**Comment by imeckler** [comment]
@bkase to check if medium curves tests are running nightly, then we need to figure out a good way to know when it's failing!

**Comment by imeckler** [comment]
@deepthiskumar to bump the timeout to N hours
