### ISSUE TITLE
coda daemon -peer hello-coda.o1test.net:8303

### ISSUE THREAD

**Issue by OAV1** [CodaProtocol/coda#3026]
cat numbers /home/administrator/.coda-config/coda.log
cat: numbers: No such file or directory
{"timestamp":"2019-07-26 22:19:10.696620Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 291, characters 65-72"},"message":"Error reading daemon.json: $error","metadata":{"error":"(Unix.Unix_error\"No such file or directory\"open\"((filename /home/administrator/.coda-config/daemon.json) (mode (O_RDONLY O_CLOEXEC)) (perm 0o0))\")","pid":2639}}
{"timestamp":"2019-07-26 22:19:10.696725Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"external-port","pid":2639}}
{"timestamp":"2019-07-26 22:19:10.696739Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"client-port","pid":2639}}
{"timestamp":"2019-07-26 22:19:10.696747Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"snark-worker-fee","pid":2639}}
{"timestamp":"2019-07-26 22:19:10.696754Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"max-concurrent-connections","pid":2639}}
{"timestamp":"2019-07-26 22:19:10.696762Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"work-selection","pid":2639}}
{"timestamp":"2019-07-26 22:19:10.696769Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 313, characters 65-72"},"message":"Key '$key' not found in the config file, using default","metadata":{"key":"peers","pid":2639}}
{"timestamp":"2019-07-26 22:19:11.457693Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 486, characters 54-61"},"message":"Creating database of type $typ in directory $directory","metadata":{"directory":"/home/administrator/.coda-config/trust","pid":2639,"typ":"trust_system"}}
{"timestamp":"2019-07-26 22:19:24.944988Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 500, characters 63-70"},"message":"Creating database of type $typ in directory $directory","metadata":{"directory":"/home/administrator/.coda-config/trust","pid":2639,"typ":"consensus local state"}}
{"timestamp":"2019-07-26 22:19:24.947664Z","level":"Debug","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 467, characters 63-70"},"message":"Long async cycle: $span milliseconds","metadata":{"pid":2639,"span":"13.614901062s"}}
{"timestamp":"2019-07-26 22:19:25.068809Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 523, characters 64-71"},"message":"Creating database of type $typ in directory $directory","metadata":{"directory":"/home/administrator/.coda-config/receipt_chain","pid":2639,"typ":"receipt_chain_database"}}
{"timestamp":"2019-07-26 22:19:25.170487Z","level":"Trace","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 531, characters 62-69"},"message":"Creating database of type $typ in directory $directory","metadata":{"directory":"/home/administrator/.coda-config/transaction","pid":2639,"typ":"transaction_database"}}
{"timestamp":"2019-07-26 22:20:03.789697Z","level":"Debug","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 467, characters 63-70"},"message":"Long async cycle: $span milliseconds","metadata":{"pid":2639,"span":"1.437377587s"}}
{"timestamp":"2019-07-26 22:20:03.821532Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 191, characters 56-63"},"message":"Kademlia command-line arguments: $argv","metadata":{"argv":["test","0.0.0.0","(\"188.187.190.53\", 8303)","(\"52.37.41.83\", 8303)"],"pid":2639}}
{"timestamp":"2019-07-26 22:20:03.825939Z","level":"Info","source":{"module":"Transition_router","location":"File \"lib/transition_router/transition_router.ml\", line 98, characters 53-60"},"message":"Starting Bootstrap Controller phase","metadata":{"pid":2639}}
{"timestamp":"2019-07-26 22:20:03.826561Z","level":"Debug","source":{"module":"Network_pool__Transaction_pool","location":"File \"lib/network_pool/transaction_pool.ml\", line 224, characters 69-76"},"message":"no frontier","metadata":{"pid":2639}}
{"timestamp":"2019-07-26 22:20:03.826591Z","level":"Debug","source":{"module":"Network_pool__Transaction_pool","location":"File \"lib/network_pool/transaction_pool.ml\", line 224, characters 69-76"},"message":"no frontier","metadata":{"pid":2639}}
{"timestamp":"2019-07-26 22:20:03.827323Z","level":"Info","source":{"module":"Proposer","location":"File \"lib/proposer/proposer.ml\", line 212, characters 57-64"},"message":"Pausing block production while bootstrapping","metadata":{"pid":2639}}
{"timestamp":"2019-07-26 22:20:03.827463Z","level":"Trace","source":{"module":"Web_pipe","location":"File \"app/cli/src/web_pipe.ml\", line 122, characters 58-65"},"message":"Not running a web client pipe","metadata":{"pid":2639}}
{"timestamp":"2019-07-26 22:20:03.827522Z","level":"Info","source":{"module":"Coda","location":"File \"app/cli/src/coda.ml\", line 590, characters 56-63"},"message":"Daemon ready. Clients can now connect","metadata":{"pid":2639}}
{"timestamp":"2019-07-26 22:20:04.268894Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 303, characters 64-71"},"message":"Creating instance","metadata":{"kademlia_level":"DBUG","pid":2639}}
{"timestamp":"2019-07-26 22:20:04.268949Z","level":"Debug","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 303, characters 64-71"},"message":"Attempting to connecting to peer: \\\"52.37.41.83\\\":8303, \\\"q4J+NuCRuYBN1VUg+Xy5pMpT26ffGbgmcqs9xFKziVY=\\\"","metadata":{"kademlia_level":"DBUG","pid":2639}}
{"timestamp":"2019-07-26 22:20:24.510383Z","level":"Error","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 277, characters 65-72"},"message":"Kademlia stderr output: coda-kademlia: thread blocked indefinitely in an MVar operation\n","metadata":{"pid":2639}}
{"timestamp":"2019-07-26 22:20:24.511551Z","level":"Fatal","source":{"module":"Kademlia__Membership","location":"File \"lib/kademlia/membership.ml\", line 228, characters 68-75"},"message":"Kademlia process died: $exit_or_signal","metadata":{"exit_or_signal":"exited with code 1","pid":2639}}
{"timestamp":"2019-07-26 22:20:24.511671Z","level":"Debug","source":{"module":"Coda_run","location":"File \"app/cli/src/coda_run.ml\", line 70, characters 52-59"},"message":"Successfully wrote the visualization of the registered masks at location: /home/administrator/.coda-config/registered_masks.dot.","metadata":{"coda_run":"Logging state before program ends","pid":2639}}
{"timestamp":"2019-07-26 22:20:24.516948Z","level":"Debug","source":{"module":"Coda_run","location":"File \"app/cli/src/coda_run.ml\", line 83, characters 58-65"},"message":"Could not visualize transition frontier since daemon is currently bootstrapping","metadata":{"coda_run":"Logging state before program ends","pid":2639}}
    

(monitor.ml.Error (Kademlia.Membership.Child_died)
  ("Raised at file \"lib/kademlia/membership.ml\", line 233, characters 18-34"
    "Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
    "Called from file \"src/job_queue.ml\", line 170, characters 6-47"
    "Caught by monitor coda"))

**Comment by o1pranay** [comment]
Thanks for reporting this @OAV1 ! This is a known issue and it is being tracked here: #3030.

Closing this issue out since it's a duplicate
