### ISSUE TITLE
Generate a "crash report" on failure

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#3045]
Currently, we dump some information on daemon failures, such as visualizations of the transition frontier and the merkle ledger, but we do not bundle this together with logs in order to make issues submissions from users easy to make and robust enough for us to debug. For instance, #3018 is a great bug find, but 20 lines of logs are not nearly enough information in order to debug the root cause of the failure. As part of graceful shutdown, we should bundle together all relevant information into a "crash report", which can just be a tar file. The crash message that informs users how to submit an issue can tell them the path to the crash report file and urge them to upload it when they make the issue. Things that would be nice to have in the crash report would include: recent logs (of any log level), more logs of more specific log levels (for instance, *all* warnings and error logs that are available), transition frontier visualization, merkle ledger visualization, version information, basic OS information, and local configuration state. We should be cognizant when designing this to make sure that the crash report can't get too big (for instance, if we put all available logs in there right now, that would be 1gb by itself, and we want to be respectful of user bandwidth).

**Comment by enolan** [comment]
worth pointing out that json logs compress *very* well. As a test I pulled
the log file off the main testnet seed node. Uncompressed it's 393M,
compressed with xz and default settings it's 4.6M. Interestingly, cranking
the compression level up to 9 doesn't buy you anything. If we wanted to get
fancy we could integrate compression into the logrotate system.

**Comment by nholland94** [comment]
Ah, that's a great compression ratio. Not too surprised really, our json logs have a lot of common bytes between each entry, but that's still a great compression ratio, so we should be able to fit quite a lot of logs in the crash report.
