### ISSUE TITLE
Empty epoch causes proposer crash

### ISSUE THREAD

**Issue by enolan** [CodaProtocol/coda#3093]
[Log snippet from Gareth on the Discord](https://gist.github.com/garethtdavies/bc2c17337da4c1551d1ba2c0740c0ff2). `next_proposal` calls `select_epoch_data`, which returns `Error` if the epoch by the clock isn't either the consensus state epoch or the immediate successor. That `Error` leads to a `failwith`, and the proposer crashes.

**Comment by garethtdavies** [comment]
Reproduced here: https://discordapp.com/channels/484437221055922177/601215883939020852/608762099321274369

**Comment by imeckler** [comment]
This error state will be fixed by a planned change to consensus. At this point we should indicate to the user via status and/or a log message that we have entered a state which is currently un-recoverable but will in a future testnet be acceptable.

**Comment by imeckler** [comment]
@ghost-not-in-the-shell has an open PR for this. @cmr to review
