### ISSUE TITLE
Gracefully handle invalidation of internally produced transitions

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#3160]
If a proposer begins proposing a transition during some slot `sl`, but does not finish generating the proof until `sl+1` has begun, there is a chance that they will have received another transition from `sl` that was sent by another proposer which is better than the one that was just produced internally. When this happens, the proposer attempts to submit the new transition to it's transition frontier and times out with `Generated transition $state_hash was never accepted into transition frontier`. Note that this can also happen even if the proving time does not straddle across blocks, but it's more likely to see it under that scenario, and that is how it's surfacing right now. There should be some logic in place to detect this condition after the proof has finished and before the proposer actually submits the transition to it's transition frontier.

**Comment by imeckler** [comment]
In case this happens, we'll log an error to the user that their block won't be counted and then move on.

**Comment by imeckler** [comment]
@nholland94 and @ghost-not-in-the-shell to discuss
