### ISSUE TITLE
URGENT: (b3) "Proposing in X slots" no longer in logs

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#3171]
There used to be logs to let a proposer know when it was proposing next.
These are fundamental in tracking how often a node is proposing and when its happening.

I can't find them anymore?

It used to say "Proposing in X slots" or something close to that effect.

This logging message will be extra important for the next weeks testnet where we have users be proposers.

**Comment by cmr** [comment]
Got renamed pre-first-release with the [new user-facing terminology](https://github.com/CodaProtocol/coda/pull/3076) in https://github.com/CodaProtocol/coda/pull/2957

**Comment by jkrauska** [comment]
is fixed
