### ISSUE TITLE
Changing Genesis Time Changes PV Keys

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#3176]
Changing Genesis timestamp changes PV Keys.

**Comment by imeckler** [comment]
I removed the genesis_timestamp from the config to track down what all depends on it. I confirmed that the snark code does not depend on it. 

I also did the following:

1. Ran `dune exec app/cli/src/coda.exe -- advan const` to look at the constraint system digests.
2. Modified the genesis timestamp in `config.mlh`
3. Ran `dune exec app/cli/src/coda.exe -- advan const` again and confirmed the digests were unchanged.

Can you give some indication of the symptom you're seeing?

**Comment by cmr** [comment]
@imeckler 	you need to remove `_build` and build again before that result is truly trustworthy, although I think you're right about the timestamp not mattering...
