### ISSUE TITLE
Coda Daemon crashed

### ISSUE THREAD

**Issue by Vasya-kripto** [CodaProtocol/coda#3194]
I'v started node and eveything was good at the beginning. But in some time daemon crushed.

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
2019-08-14 13:43:25 UTC [Error] Prover failed: $error
        error: "((rpc_error (Connection_closed (\"EOF or connection closed\")))\n (connection_description (\"Client connected via TCP\" (233648.local 38979)))\n (rpc_tag rpc_parallel_plain_3) (rpc_version 0))"
2019-08-14 13:43:25 UTC [Info] Generating crash report
[coda_crash_report_2019-08-14_13-43-41.739273.tar.zip](https://github.com/CodaProtocol/coda/files/3502612/coda_crash_report_2019-08-14_13-43-41.739273.tar.zip)

**Comment by cmr** [comment]
Thanks for the report! This seems to be another instance of https://github.com/CodaProtocol/coda/issues/2978. I'll close this issue in favor of that one...
