### ISSUE TITLE
Coda Daemon crashed

### ISSUE THREAD

**Issue by AlexanderYudin** [CodaProtocol/coda#3196]
Coda Daemon crashed

coda_crash_report_2019-08-14_19-55-21.341483.tar.xz
https://drive.google.com/file/d/1lD6iAhev6d0r37MglN1dlsmpksa_gwcw/view

**Comment by AlexanderYudin** [comment]
Today, the problem repeated several times

here are the last logs
https://drive.google.com/file/d/1VC8ofrvMOOLejUxqKYK_V-317pT5kNJE/view?usp=sharing

**Comment by cmr** [comment]
Another instance of #2978. I've asked you a followup question there!
