### ISSUE TITLE
LOGGING: Gossip - "broadcasting message" needs more context

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#3197]
Current logging has messages like this

```
{
  "timestamp": "2019-08-14 20:45:14.444696Z",
  "level": "Trace",
  "source": {
    "module": "Gossip_net",
    "location": "File \"lib/gossip_net/gossip_net.ml\", line 500, characters 71-78"
  },
  "message": "broadcasting message",
  "metadata": {
    "pid": 10199
  }
}
```

Without any context this is mostly a useless log line.

Broadcasting what type of message?
to who?
was it locally generated or is this a rebroadcast of someone else's message?

**Comment by imeckler** [comment]
Let's add the following metadata:

- Add summary of message

@deepthiskumar to check if she added this
