### ISSUE TITLE
Surface info around slots won within the epoch more easily (via status?)

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#3200]
Several block producers this testnet are wondering if there is an error in their nodes or if they just are getting very unlucky and not winning blocks.

Currently the best way to tell if your node wins is to look for logs:

"No slots won in this epoch"

or

"Producing block in X slots" where X is the number of slots to wait.

We should have information in status:

`Production Status` which exposes the following information:

```
type block_production_status = Before_checked | None_this_epoch | This_epoch of Slot.t list
```

**Comment by imeckler** [comment]
```ocaml
let () =
  List.init 100 ~f:(fun i -> eval_vrf (Int.to_string i) < threshold 0.03)
```

**Comment by imeckler** [comment]
Currently we implicitly compute the list of won slots lazily by repeatedly calling `next_proposal`. Should we change this behavior and eagerly compute this list?

**Comment by bkase** [comment]
@nholland94 ran that function and experimentally saw what we expected so our best guess is that it’s a user error

@ihm we can expose “next won” instead of a list if we’re doing so lazily
