### ISSUE TITLE
Coda Daemon Crashed while Staking

### ISSUE THREAD

**Issue by paul-bison** [CodaProtocol/coda#3205]
Was synced and up for over a day and the daemon crashed logs attached
[coda_crash_report_2019-08-14_20-42-48.186385.tar.xz.zip](https://github.com/CodaProtocol/coda/files/3506090/coda_crash_report_2019-08-14_20-42-48.186385.tar.xz.zip)

**Comment by cmr** [comment]
This is another instance of #2978. Thanks for the report!
