### ISSUE TITLE
File format for Coda Daemon Crashes

### ISSUE THREAD

**Issue by paul-bison** [CodaProtocol/coda#3206]
Hey, since the project is using github to track issues, it would be nice if the coda daemon crash logs were output in a format that could be directly uploaded to github issues. Making the outputted file a .zip  would save us a step in reporting and uploading.

thanks.
-paul

![image](https://user-images.githubusercontent.com/49249346/63106081-1610cf00-bf50-11e9-9f87-7041c162bfae.png)

**Comment by cmr** [comment]
:+1: thanks Paul, I've done that in https://github.com/CodaProtocol/coda/pull/3221
