### ISSUE TITLE
Snark worker is not turned off properly in integration tests

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [CodaProtocol/coda#3231]
Sometimes integration tests fails because snark worker isn't shut down properly.
The following is an example:
https://201325-114581326-gh.circle-artifacts.com/0/home/opam/project/test_logs/1565995854/test_postake_txns/coda-shared-state-test.log
In this one, the test went on well. But at the end when we shut down the two nodes, the shut down failed.

The correct order of shutdown should be:
0. turn the status of the node to be offline
1. shut down the snark worker
2. shut down the connection
3. shut down the subprocess

**Comment by cmr** [comment]
#3239 was supposed to close this.

**Comment by ghost-not-in-the-shell** [comment]
@cmr #3239 mitigates the problem. But I still see it in our integration test.

The problem is that the close of snark worker is implemented asynchronously.

We just send a signal to close it and not waiting for to close.

Following are relevant functions we use for closing snark workers:
Inside coda_lib.ml
```
  let replace_key ({processes= {snark_worker; _}; config= {logger; _}; _} as t)
      new_key =
    match (snark_worker, new_key) with
   ...
    | `On (_, fee), None ->
        let%map () = stop t in
        t.processes.snark_worker <- `Off fee
```

```
  let stop t =
    match t.processes.snark_worker with
    | `On ({public_key= _; process}, _) ->
        let%map process = Ivar.read process in
        Logger.info t.config.logger
          "Killing snark worker process with pid: $snark_worker_pid"
          ~module_:__MODULE__ ~location:__LOC__
          ~metadata:
            [("snark_worker_pid", `Int (Pid.to_int (Process.pid process)))] ;
        Signal.send_exn Signal.term (`Pid (Process.pid process))
    | `Off _ ->
        Logger.warn t.config.logger
          "Attempted to turn off snark worker, but no snark worker was running"
          ~module_:__MODULE__ ~location:__LOC__ ;
        Deferred.unit
```
