### ISSUE TITLE
Add an initialization phase to coda daemon

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [CodaProtocol/coda#3272]
The current rule is that
1. if we are in the first epoch, start transition frontier controller
2. if we are not in the first epoch, start bootstrap controller

This would cause certain trouble for proposers which start near the end of the first epoch. At that point, those proposer would probably needs to do bootstrap, but bootstrap won't be triggered until it receive a transition from the network. Before a transition is received it could have a chance to propose and this would cause it be banned by other nodes for broadcasting disconnected transition. This happens a lot in holy-grail test.

A possible fix to this problem is to add an initialization phase such that when a node start it would first collect best-tip information from peers and using this information to decide whether it should start transition frontier controller or bootstrap controller or start ledger catchup.

This is could be seen as an extension to eager-bootstrap.

**Comment by imeckler** [comment]
@ghost-not-in-the-shell has an open PR -- @cmr says looks good. needs code owner reviews mayhaps
