### ISSUE TITLE
[Feature Request] Runtime Genesis Ledger 

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#3277]
I believe it is of dire importance to be able to set the genesis ledger at runtime. 

@bkase believes this to be impossible, however I have heard promising things when posing the question to @cmr and @nholland94. 

I'd like the user experience to be similar to this: https://github.com/ethereum/go-ethereum/wiki/Private-network#creating-the-genesis-block

**Comment by imeckler** [comment]
The easy version of this is to make it so when a new genesis ledger is created we also generate an associated keypair.

**Comment by imeckler** [comment]
After discussing at the prioritization meeting -- it seems like this is not a huge blocker at the moment. Is it OK with you if we don't prioritize this in the short term @yourbuddyconner ?

**Comment by yourbuddyconner** [comment]
Yeah, I'd say it probably won't be a hard blocker for a while as long as we have a time offsets build.

**Comment by bkase** [comment]
It's starting to be a harder blocker...

**Comment by yourbuddyconner** [comment]
Use-Case: This is very much required for testing hotfixes before we roll them out to our users. Since `time-offsets` are off on production builds, we have no way to test a daemon  without connecting it to a network that has been running since genesis.

**Comment by imeckler** [comment]
@cmr: This is hard because the hash of the genesis ledger is hard-coded in the negative one state.

@nholland94 suggests: When advancing from negative one to genesis, we can turn off all checks (I think the VRF check is actually the only that is blocking this) so that we can make the zero state whatever we like.

**Comment by imeckler** [comment]
@cmr : we should aim for having the genesis ledger be in a json file

**Comment by yourbuddyconner** [comment]
Encountering another situation where this would save time. Currently the release branch has a genesis ledger set to `10/21` However, I am going to have to amend the ledger to allow me to launch a release candidate ledger today, then again next week to launch the public network.

**Comment by yourbuddyconner** [comment]
Reopening this one as #4001 only implements balances/accounts. I have said repeatedly that this feature is only really useful if it includes the genesis timestamp. 

CC @bkase
