### ISSUE TITLE
[Feature Request] Load Multiple Wallets at Runtime

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#3285]
When launching Daemons in a production-type environment, there is a requirement to allow installing multiple private keys as "wallets" at daemon runtime.

**For example,** 
> A coda daemon running alongside the bot requires the private keys for the `Echo` and `Faucet` accounts to be installed and available as wallets. 

I have talked to @Schmavery and @bkase about this -- they might have more information about the why/when/how.

**Comment by yourbuddyconner** [comment]
There is a "Gross Hack" I am using currently which imports the keys in an unsafe manner, but a better mechanism needs to be devised. 

```
# Gross Hack Alert
# Need to unsafely import the private keys
for file in "${key_files[@]}"
do
  coda advanced unsafe-import -privkey-path $file
done

```

**Comment by imeckler** [comment]
@Schmavery is working on a fix that doesn't strip the password from the keys. @Schmavery can you close this issue when that's done?

**Comment by Schmavery** [comment]
There should now be a `coda advanced import` that doesn't strip passwords.
