### ISSUE TITLE
Don't propose when we are doing ledger catchup

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [CodaProtocol/coda#3332]
I noticed that holy-grail sometimes fails because we are proposing before ledger-catchup finishes. It would cause other nodes to ban us for disconnected transitions.

**Comment by ghost-not-in-the-shell** [comment]
This could be dangerous. If a peer finds a way to make other proposers intentionally do catchup, then it could abuse it to block those proposers.

**Comment by bkase** [comment]
@nholland94 and @ghost-not-in-the-shell to discuss

**Comment by ghost-not-in-the-shell** [comment]
I have RFC that discusses possible solutions to this problem #3340
