### ISSUE TITLE
Make sure all RPC handlers are wrapped in a try with or monitor

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#3335]
We should not be able to crash from an RPC. See for example https://github.com/CodaProtocol/coda/issues/3162.

**Comment by imeckler** [comment]
@cmr did you look at this?

**Comment by bkase** [comment]
@cmr ping, did you look at this"?

**Comment by bkase** [comment]
@cmr the ping of the wing

**Comment by bkase** [comment]
do we have a handler for integration tests?

**Comment by enolan** [comment]
We potentially leak `Rpc.Connection.t`s in an rpc handler throws an
exception. There should be a `with_monitor` at the level of the rpc server,
and only inside of the handlers themselves if there's some cleanup logic
that needs to happen inside there.
