### ISSUE TITLE
-no-bans has expired

### ISSUE THREAD

**Issue by enolan** [CodaProtocol/coda#3395]
We put a time bomb in for the `-no-bans` option, since we were having issues with the trust system spuriously banning people. It expired last Friday, and we extended the deadline to this Friday.

I looked at the Kibana logs for who would've been banned if bans were turned on on our nodes:

# Investigation of ban logs over the last 7 days, based on Kibana query "New trust is -1.000000.":

- 335 of the messages are from a single IP, in EC2. I think they had their network misconfigured somehow.
- Excluding that IP, there are only 18 messages, distributed over 11 IPs.

## Bans from grab-bag

- Around 13:28 September 7, the rpc parallel worker on grab-bag_us-west-2_seed_0.us-west-2 died. Since we use parallel workers to check proofs, this made proof checking fail and we would've banned some IPs because they sent what seemed to be invalid proofs. This accounts for 6 of the ban messages.
- One peer would've been banned because of `Outgoing_connection_error`. This should only be a trust decrease of 0.05, so they should have had to do a bunch of other stuff in order to get banned. I don't see any other stuff in the log though. Something weird happened.
- One peer would've been banned because of `Sent_invalid_proof`, unrelated to the parallel worker dying. Appears to be a legit error.

## Bans from something-snarky

- Two `Disconnected_chain` errors from one peer
- Three different IPs owned by VPS provider your-server.de would've been banned because of `Gossiped_old_transition`. Probably the same person operating them with some clock problem.
- One IP owned by EC2 with the same issue.
- One peer in EC2 `Connected` to a single O(1) node 463 times and eventually would've gotten banned for `Incoming_connection_error`. Possibly related to #3022. Or that guy is running a lot of clients simultaneously, or an honest to goodness attempted DoS. They also would've been banned on some other O(1) nodes.

# Discussion

So we would've only banned 12 IPs in the last week. And the vast majority of those would have only been banned on one or two nodes, not disconnected from the network as a whole. At least one of them was misconfigured enough to be totally broken regardless of if we banned it or not.

What do people think of removing `-no-bans`? If you're against it, how much do we need to lower the rate of spurious bans for you to be satisfied? I said before I was fine with decreasing ban duration to 4 hours from 24, and I still am.

**Comment by yourbuddyconner** [comment]
Good analysis, supports turning off `-no-bans` in my opinion.
