### ISSUE TITLE
Base58-ify Utility

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#3442]
Often we run in to other representations of keys and need to convert them to base58 to decode them.

Would it be possible to write a small base58 utility that could take inputs, try to guess at what form they are, and then try to provide an encoding?

eg.

echo '10678220997160895385753836087815976126795597965337500955257468561562558224639604531671522458871181490687626593275979160528050495600978832374315639249884424631656628660832415991217595564546161803026643912674548333193665613720362' | coda-c58
might print

LOG: Converting from uncompressed to base58
tNciP3S9u596zcmc6Mm2hT3AXXNt2HisaEzkHjrwGXhADYCZaqgRxxw4DUtUx4VtQahxeMEZHN3a2RYmCxHiArNSPSFmq5ooYAhZh3U2dpEn7zK214ycJee1YnoaugMrGcy5TXc3YxA42d

(I don't believe that's a proper conversion, it's just an example)

**Comment by psteckler** [comment]
We have a Base58Check representation only for compressed public keys.

The non-Base58Check representations we have for public keys are:

- uncompressed sexp
- compressed sexp
- compressed json
- compressed bigstring

I'm supposing the bigstring representation is never printed; it's derived from the `bin_io` serialization.

I'm also supposing that we should have a single sexp representation, the compressed one, like we do for json (I'll open an issue).

That leaves two representations to deal with. While it's easy enough to distinguish them -- one begins with a round brace, the other with a curly brace -- I'll suggest that the utility take flags, like `--from-json` and `--from-sexp`.

**Comment by jkrauska** [comment]
@psteckler which representation is in the bug?
10678220997160895385753836087815976126795597965337500955257468561562558224639604531671522458871181490687626593275979160528050495600978832374315639249884424631656628660832415991217595564546161803026643912674548333193665613720362

I'm sure it's easier to make the user know their inputs, but I'd prefer a 'universal translator'.
The point of the tool is that we don't know what we are looking at and need help.

Would trying to convert from an invalid format fail?

eg. If I was json and used --from-sexp what would the parser do?

--Joe

**Comment by psteckler** [comment]
@jkrauska In fact, the JSON representation is just a JSON string containing Base58Check, so no conversion to do there.

So the only other representation is sexp. 

For an uncompressed key, the sexp (currently) is a pair of field elements in decimal format, which is probably what you have there, with maybe the parens and separating space missing (?). Here's an example that I just printed:
```
(56994357222575487925955871668158748421225338776246696455571360618066746034970464175948949 391166886291072308594567426024944295740048689577547480070325132376730402464737306939248262)
```
For a compressed key, the sexp is a field element and a bool:
```
((x 41376453179727011640573551597434838706406490696029074948842100588564528265719313153119014)(is_odd true))
```
In  #3461, I'm suggesting that we have only this latter sexp representation (just as we have only one repr for JSON). In that case, the utility has only one case to deal with, no flags or format detection needed. In case we don't make that change, we have two representations, which are easy to distinguish.

We could do something even more radical: make the sexp representation be Base58Check, like we're already doing for JSON. Then you don't need the utility at all.

**Comment by psteckler** [comment]
Moreover, I'm not sure we can recover a pubkey from its current sexp representation: see #3444.
