### ISSUE TITLE
cli command send-payment responds incorrectly when payment validation fails

### ISSUE THREAD

**Issue by deepthiskumar** [CodaProtocol/coda#3457]
When we send user transactions we don’t infer balances like we infer nonces, meaning, every time a send-payment command is issued,  the payment  is validated against the account balance at the best tip and doesn’t consider transactions already in the pool. But while creating the transaction pool diff that is to be broadcasted, it’d calculate the correct balance and drop those that cause an overdraft with the message `insufficient funds`. However, for such transactions we also log the msg Added transaction $user_command to transaction pool successfully and return a transaction ID to the cli

**Comment by imeckler** [comment]
Here we should look at the result of "Transaction_pool.apply" not just our account balance in the best pool ledger.

**Comment by deepthiskumar** [comment]
This needs more work because the receipt chain hashes are computed incorrectly as well. When multiple transactions are sent from one sender within a block, the receipt chain hashes are always computed using the receipt chain hash from the account state at the best tip which will not match with the actual receipt chain hashes. So we need to keep track of receipt chain hashes of locally generated transactions in the transaction pool to fetch the latest latest receipt-chain-hash of an account whenever a new payment is made. We also don't update the receipt-chain-hash database when there's a reorg or when transactions are dropped due to fee/size constraints
