### ISSUE TITLE
Add spacetime to common docker toolchain image

### ISSUE THREAD

**Issue by psteckler** [CodaProtocol/coda#3472]
We should have a single docker image that contains switches for both vanilla and the spacetime variant of OCaml.

For the most part, both switches can install the same packages. For spacetime, we also want to install the packages for `prof_spacetime`, and make sure the stack is unlimited. See #3471 for more details.

**Comment by imeckler** [comment]
Basically we have to modify the toolchain docker.

**Comment by psteckler** [comment]
Implemented in #3519.
