### ISSUE TITLE
crash report

### ISSUE THREAD

**Issue by ul1tko** [CodaProtocol/coda#3497]
Generating crash report
        exn: "(monitor.ml.Error (\"Secrets.Privkey_error.Privkey_exn(_)\")\n  (\"Raised at file \\\"lib/secrets/privkey_error.ml\\\", line 23, characters 14-35\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 170, characters 6-47\"\n    \"Caught by monitor coda\"))"

  ☠  Coda daemon crashed. The Coda Protocol developers would like to know why!

[coda_crash_report_2019-09-26_07-22-24.116855.tar.gz](https://github.com/CodaProtocol/coda/files/3656464/coda_crash_report_2019-09-26_07-22-24.116855.tar.gz)

**Comment by o1pranay** [comment]
Thanks for reporting! This error means that either password / permissions are wrong with your private key. Please try again with the release tomorrow, and let us know if this continues to be an issue -- we also have added better error messaging to explain this issue.
