### ISSUE TITLE
Unhandled top-level exception: $exn

### ISSUE THREAD

**Issue by UbikCapital** [CodaProtocol/coda#3499]
2019-09-26 17:52:25 UTC [Warn] Different version of Coda detected in config directory "/root/.coda-config", removing existing configuration
2019-09-26 17:52:25 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error (\"Secrets.Privkey_error.Privkey_exn(_)\")\n  (\"R
[coda_crash_report_2019-09-26_17-52-25.875812.tar.gz](https://github.com/CodaProtocol/coda/files/3659205/coda_crash_report_2019-09-26_17-52-25.875812.tar.gz)
aised at file \\\"lib/secrets/privkey_error.ml\\\", line 23, characters 14-35\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 170, characters 6-47\"\n    \"Caught by monitor coda\"))"

  ☠  Coda daemon crashed. The Coda Protocol developers would like to know why!

  Please:
    Open an issue:
      <https://github.com/CodaProtocol/coda/issues/new>

    Briefly describe what you were doing and attach the crash report /root/.coda-config/coda_crash_report_2019-09-26_17-52-25.875812.tar.gz

**Comment by o1pranay** [comment]
Thanks for reporting! This error means that either password / permissions are wrong with your private key. Please try again with the release on 10/8/19, and let us know if this continues to be an issue -- we also have added better error messaging to explain this issue.
