### ISSUE TITLE
Cannot start coda after abrupt termination

### ISSUE THREAD

**Issue by Codonyat** [CodaProtocol/coda#3506]
I was running coda with screen in Ubuntu, when I think I terminated a screen with the coda daemon abruptly. Now, when I try to restart the daemon, I get this error.

[coda_crash_report_2019-09-26_20-10-01.633301.tar.gz](https://github.com/CodaProtocol/coda/files/3659707/coda_crash_report_2019-09-26_20-10-01.633301.tar.gz)

**Comment by enolan** [comment]
Can you double check you're using the right password? We broke the error
message recently unfortunately.

**Comment by Codonyat** [comment]
I found out the problem. The wallet folder didn't have the right
permissions.

**Comment by o1pranay** [comment]
👍 closing this one out, as it's resolved
