### ISSUE TITLE
Default Memo should be empty.

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#3507]
Because of hashing or something post processing when you don't apply a MEMO to a transaction, you get:

Memo: i!z0y!B5J\|UH,% nz

We should default an empty memo or even 'empty memo' as a default to make this a little prettier/nicer.

**Comment by psteckler** [comment]
I can do this one easily.

**Comment by psteckler** [comment]
@jkrauska where are the memos made visible?

**Comment by Schmavery** [comment]
@psteckler not sure where Joel is seeing them, but they're visible in a base58check-encoded form (we should probably change that too but idk if it's related to this issue) in the logs and in one of the graphql queries.
@garethtdavies decodes those encoded strings in https://codaexplorer.garethtdavies.com, which is where I've seen the `i!z0y�!B5J|�UH,��% �nz`-like string in the past.

**Comment by psteckler** [comment]
@Schmavery OK, I believe I know where they're generated. I do need a way to verify that a fix is indeed a fix.

**Comment by Schmavery** [comment]
If you're able to print out the base58check-encoded representation of an empty memo, then you should be able to look for that in the logs when sending a transaction
