### ISSUE TITLE
Coda daemon crashed

### ISSUE THREAD

**Issue by AlexanderYudin** [CodaProtocol/coda#3515]
[coda_crash_report_2019-09-27_00-20-50.229813.tar.gz](https://github.com/CodaProtocol/coda/files/3660365/coda_crash_report_2019-09-27_00-20-50.229813.tar.gz)

**Comment by o1pranay** [comment]
@AlexanderYudin I think this was due to a wrong password on the private key. We fixed the error message to be more clearer this time. Thanks for reporting!
