### ISSUE TITLE
"Cannot allocate memory"

### ISSUE THREAD

**Issue by ilhanu** [CodaProtocol/coda#3528]
During Testnet 2 Beta:

I run on a VPS 4-core/8gb memory ubuntu 18.04. I have been active since genesis and until now haven't produced any block. 
When I type `coda client status` to find our the status of my node, I get the following output

```
Uncaught exception:
  
  (Unix.Unix_error "Cannot allocate memory" fork
   "((command \"brew --prefix 2>/dev/null\"))")

Raised at file "src/core_unix.ml", line 50, characters 4-43
Called from file "src/core_unix.ml" (inlined), line 1687, characters 22-60
Called from file "lib/cache_dir/cache_dir.ml", line 9, characters 12-60
```

When I read the journalctl I don't  get anything why it failed, it mentions that it disconnected from a node and before that It calculated epoch 4 and it will produce blocks in 84 slots. 

After that when I ask for the client status I get this output `Segmentation fault (core dumped)`

**Comment by o1pranay** [comment]
@ilhanu Thanks for reporting, can you try bumping you machine to 16gb? We're working on improving the memory usage
