### ISSUE TITLE
unix error, 

### ISSUE THREAD

**Issue by cbrown330** [CodaProtocol/coda#3535]
not sure if this has been seen but it popped up with no reason a simple restart fixed it, but i am not sure if it was on my end or the connection end but it was after about 2 full days running, and i did complete alot of translations, enough to drain my wallet lol.  But this happened about 4 hours after i turned off my auto payment script,   And like i said just letting you all know, that is what testing is for right lol

        exn: "(Unix.Unix_error \"No route to host\" connect 95.165.167.193:8322)"
2019-10-01 07:40:38 UTC [Error] Broadcasting message "snark pool diff" to $peer failed: $error
        peer: {
  "host": "95.165.167.193",
  "discovery_port": 8323,
  "communication_port": 8322
}
        error: "(Unix.Unix_error \"No route to host\" connect 95.165.167.193:8322)"
2019-10-01 07:41:05 UTC [Error] RPC call raised an exception: $exn
        exn: "(\"connection attempt timeout\" 99.45.147.6:8302 src/tcp.ml:120:11)"
2019-10-01 07:41:05 UTC [Error] Broadcasting message "snark pool diff" to $peer failed: $error
        peer: { "host": "99.45.147.6", "discovery_port": 8303, "communication_port": 8302 }
        error: "(\"connection attempt timeout\" 99.45.147.6:8302 src/tcp.ml:120:11)"
2019-10-01 07:41:10 UTC [Error] RPC call raised an exception: $exn
        exn: "(Unix.Unix_error \"No route to host\" connect 95.165.167.193:8322)"
2019-10-01 07:41:10 UTC [Error] Broadcasting message "snark pool diff" to $peer failed: $error
        peer: {
  "host": "95.165.167.193",
  "discovery_port": 8323,
  "communication_port": 8322
}
        error: "(Unix.Unix_error \"No route to host\" connect 95.165.167.193:8322)"

**Comment by enolan** [comment]
Your computer's network connection went down for some reason. You'll see that if none of the entries in the local routing table match the destination IP.
