### ISSUE TITLE
Coda daemon crashed

### ISSUE THREAD

**Issue by UbikCapital** [CodaProtocol/coda#3536]
exn: "(\"connection attempt timeout\" 148.64.99.117:12222 src/tcp.ml:120:11)"
2019-10-01 09:06:42 UTC [Error] Broadcasting message "snark pool diff" to $peer failed: $error
        peer: {
  "host": "148.64.99.117",
  "discovery_port": 12223,
  "communication_port": 12222
}
        error: "(\"connection attempt timeout\" 148.64.99.117:12222 src/tcp.ml:120:11)"
2019-10-01 09:08:04 UTC [Error] RPC call raised an exception: $exn
        exn: "(\"connection attempt timeout\" 148.64.99.117:12222 src/tcp.ml:120:11)"
2019-10-01 09:08:04 UTC [Error] Broadcasting message "snark pool diff" to $peer failed: $error
        peer: {
  "host": "148.64.99.117",
  "discovery_port": 12223,
  "communication_port": 12222
}
        error: "(\"connection attempt timeout\" 148.64.99.117:12222 src/tcp.ml:120:11)"
^Z
[1]+  Stopped                 coda daemon -peer filet-mignon.o1test.net:8303 -propose-key keys/my-wallet
root@vmi300810:~# coda daemon -peer filet-mignon.o1test.net:8303 -propose-key keys/my-wallet
2019-10-01 09:08:14 UTC [Info] Coda daemon is booting up; built with commit "78e066cd487ab2ec16594d6b3bf489deffe140c3" on branch "master"
2019-10-01 09:08:14 UTC [Info] Daemon will expire at "2019-10-08 14:00:00-07:00"
2019-10-01 09:08:14 UTC [Info] Booting may take several seconds, please wait
Secret key password:
Wrong password! Please try again
Secret key password:
2019-10-01 09:08:34 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error\n  (Failure\n    \"IO error: While lock file: /root/.coda-config/trust/LOCK: Resource temporarily unavailable\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"lib/rocksdb/database.ml\\\", line 16, characters 34-63\"\n    \"Called from file \\\"lib/trust_system/peer_trust.ml\\\", line 50, characters 15-44\"\n    \"Called from file \\\"app/cli/src/coda.ml\\\", line 569, characters 28-65\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 170, characters 6-47\"\n    \"Caught by monitor coda\"))"

  ☠  Coda daemon crashed. The Coda Protocol developers would like to know why!

  Please:
    Open an issue:
      <https://github.com/CodaProtocol/coda/issues/new>

**Comment by Schmavery** [comment]
I could be wrong, but it looks like you started the daemon, then suspended it (with ctrl-z), then started another, and the second one crashed because of a lockfile in `.coda-config/trust`.

One thing you could try is only running one daemon at a time, for now (if you need to run more than one, you can specify non-conflicting .coda-config directories and ports).

We could definitely stand to improve this error message though, thanks!
