### ISSUE TITLE
[Feature Request] Metrics -- Block Height, Max Block Height, Local Uptime

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#3552]
We have metrics for blocks proposed (`Coda_Proposer_blocks_proposed`) and slots won (`Coda_Proposer_slots_won`) and it would be useful to have a block height metric for each node. 

In `coda client status` these are present via `block height` and `max observed block height`, so hopefully its easy to pull these out. 

It would be useful to have metrics for the following: 
- `Block Height`
- `Max Block Height`
- `Local Uptime`

cc @ghost-not-in-the-shell

**Comment by yourbuddyconner** [comment]
PR: https://github.com/CodaProtocol/coda/pull/3554

**Comment by ghost-not-in-the-shell** [comment]
Should we close this issue?
