### ISSUE TITLE
Urgent: 'Next proposal' stuck in 'Computing'

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#3560]
In fillet: (current public testnet)
`Next proposal:              in 29.023m`

In smoketest (nightly run of develop):
`Next proposal:              Computing next proposal state...`

Something broke in the next proposal analysis, notification.

Fully sync'd block producers that are actively producing blocks no longer identify WHEN their next block is..

**Comment by jkrauska** [comment]
@enolan any insight here?

**Comment by enolan** [comment]
I looked into it yesterday and didn't get anywhere. None of the logic I
checked has changed recently and it seems right. The hashing functions have
changed but not the proposal logic or the code that sets the variable that
coda client status reads. I can do some more debugging.

**Comment by enolan** [comment]
I think @nholland94 fixed this
