### ISSUE TITLE
Coda daemon crashed

### ISSUE THREAD

**Issue by novy4** [CodaProtocol/coda#3581]
2019-10-06 10:10:34 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error\n  (Unix.Unix_error \"No child processes\" waitpid\n    \"((mode (WNOHANG)) (pid 9979))\")\n  (\"Raised at file \\\"src/core_unix.ml\\\", line 50, characters 4-43\"\n    \"Called from file \\\"src/core_unix.ml\\\", line 930, characters 4-246\"\n    \"Called from file \\\"src/unix_syscalls.ml\\\", line 596, characters 10-39\"\n    \"Called from file \\\"src/unix_syscalls.ml\\\" (inlined), line 602, characters 21-55\"\n    \"Called from file \\\"src/unix_syscalls.ml\\\", line 610, characters 33-48\"\n    \"Called from file \\\"camlinternalLazy.ml\\\", line 27, characters 17-27\"\n    \"Re-raised at file \\\"camlinternalLazy.ml\\\", line 34, characters 4-11\"\n    \"Called from file \\\"src/process.ml\\\" (inlined), line 142, characters 13-25\"\n    \"Called from file \\\"src/process.ml\\\", line 148, characters 25-31\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 170, characters 6-47\"\n    \"Caught by monitor coda\"))"

  ☠  Coda daemon crashed. The Coda Protocol developers would like to know why!

  Please:
    Open an issue:
      <https://github.com/CodaProtocol/coda/issues/new>

**Comment by o1pranay** [comment]
@novy4 Thanks for reporting! Closing this one out, as this bug is already reported in a previous issue: https://github.com/CodaProtocol/coda/issues/3520.
