### ISSUE TITLE
Daemons with expiration all shut down at different times

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#3594]
Daemons that have an expiration set do not consistently shut down at the expiration. Observing a testnet which expired, there was as much as a 40 minute drift between the time that the individual nodes shut down. This is pretty low priority, but should be an easy fix.

**Comment by yourbuddyconner** [comment]
Some metrics supporting this conclusion: 
<img width="1603" alt="Screen Shot 2019-10-08 at 4 51 09 PM" src="https://user-images.githubusercontent.com/2635475/66441479-e4fec900-e9eb-11e9-8794-672fcd9b351d.png">

**Comment by jkrauska** [comment]
Odd -- All the fillet nodes stopped precisely at the same time.
![Screenshot 2019-10-09 14 28 23](https://user-images.githubusercontent.com/613548/66521947-16859c00-eaa1-11e9-8ce3-76bdc09622e3.png)

**Comment by jkrauska** [comment]
What was your expiration time?

Based on the wide spread, I suspect those nodes died 'naturally' and just weren't restarted.
(monit is only deployed manually at the moment)

**Comment by nholland94** [comment]
It's possible that happened instead, but at least on the nodes that I inspected (2 nodes, not all of them) there were no crashes and the last log messages were regarding expiration.

**Comment by jkrauska** [comment]
I have a utility in ansible to gather up all log dirs when you retire a testnet
we should be sure to do that for your next net.
