### ISSUE TITLE
[Feature Request] Scan State Metrics

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#3609]
Right now we've got several metrics relating to snark work going into and out of the scan state, but the only insight we've got into the actual contents of the scan state is `Coda_Snark_work_scan_state_snark_work`. 

I'd like a more granular view, potentially going down to the "tree" level, telling me how many transaction and merge proofs need to be done/are present. 

I would also like to calculate the "max size" of the scan state and identify when things are "filling up"

**Comment by ghost-not-in-the-shell** [comment]
I am not very familiar with scan state. I probably need Deepthi's help to add metrics for that.

**Comment by yourbuddyconner** [comment]
cc @deepthiskumar

**Comment by imeckler** [comment]
per @deepthiskumar , @jkrauska : At the moment, there is a CLI command for doing this. They are  under advanced:

```
snark-job-list
snark-pool-list
```

but we can add it to the prometheus metrics
