### ISSUE TITLE
URGENT - LOGS - POS last_vrf_output contains binary

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#3625]
In File \"lib/consensus/proof_of_stake.ml
line 2466, characters 54-61

message":"Selecting best consensus state

metadata.candidate
"last_vrf_output":"\u000e4w˅<FF><F5>s\\<DA>\u0004,\"<F0><FC>X;<82>z\u0012Lo<D9>Qd<A5>l<F8>k\u001d-\u

Please help keep binary data out of text logs.

**Comment by jkrauska** [comment]
Urgent because this breaks most ability to parse logs cleanly.

eg
```
cat test-coda/coda.log | grep curr_global_slot
Binary file (standard input) **matches**
```

**Comment by ghost-not-in-the-shell** [comment]
`last_vrf_evaluation` is actually important for debugging. And we might not want to truncate it from the log messages.

@imeckler or @nholland94 might find a better way to represent this field, so that it doesn't read like binary.

**Comment by nholland94** [comment]
As a followup to this removal, I have logged an issue here which encapsulates the work to do to put it back into the logs with a reasonable format. https://github.com/CodaProtocol/coda/issues/3628

**Comment by jkrauska** [comment]
@nholland94  to be clear, I wasn't asking for a removal, just a cleaner representation that doesn't break text tools

**Comment by imeckler** [comment]
@ghost-not-in-the-shell to delete it re https://github.com/CodaProtocol/coda/issues/3628
