### ISSUE TITLE
LOGS - sok_digest is non-string

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#3630]
sok_digest will frequently emit in to the logs with non-string representations

eg
"sok_digest":"<E7>Lh<A5><8C>u\u0002l@\u0013\b<9F><C7>V\u0010<A2>L6W\u001b<8D>|<E9><CD>@<F0>@+%D<BF>q"

This breaks log parsers which expect ascii/utf8/text.

Please review the yojson representation of sok_digest and either remove this field or find a way to encode it as a true string.

**Comment by imeckler** [comment]
We can also remove this from logs.

**Comment by imeckler** [comment]
@jkrauska and @ghost-not-in-the-shell to team up and find and remove this
