### ISSUE TITLE
Diagnose long async cycles

### ISSUE THREAD

**Issue by imeckler** [CodaProtocol/coda#3674]
High priority:
- [x] Long async cycle caused by `List.fold` (takes ~80s in release/0.0.9-beta, happens everytime when we do bootstrap) https://github.com/CodaProtocol/coda/blob/74bf7ca51bb2d005c44a04f41d97a2a9e0d82fad/src/lib/staged_ledger/staged_ledger.ml#L267
This one should be fixed by https://github.com/CodaProtocol/coda/pull/3669
- [x] Long async cycle caused by `Statement_scanner.check_invariants` @deepthiskumar (takes ~17s in release/0.0.9-beta, happens everytime when we verify a network transition or proposed transition)
The transaction_snark_scan_state is parameterized by a monad, maybe we could use a `Deferred` monad here? 
https://github.com/CodaProtocol/coda/blob/74bf7ca51bb2d005c44a04f41d97a2a9e0d82fad/src/lib/staged_ledger/staged_ledger.ml#L700
https://github.com/CodaProtocol/coda/blob/74bf7ca51bb2d005c44a04f41d97a2a9e0d82fad/src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml#L411
https://github.com/CodaProtocol/coda/blob/74bf7ca51bb2d005c44a04f41d97a2a9e0d82fad/src/lib/transaction_snark_scan_state/transaction_snark_scan_state.ml#L294
This one should be fixed by https://github.com/CodaProtocol/coda/pull/3753
- [ ] Long async cycle caused by scan_state deserialization @imeckler (takes ~2min in release/0.0.9-beta, happens everytime when we do bootstrap)
The scan_state contains hundreds/thousands of proofs. The deserialization of each proof takes 
~0.065s.
https://github.com/CodaProtocol/coda/blob/74bf7ca51bb2d005c44a04f41d97a2a9e0d82fad/src/lib/coda_base/proof.ml#L27
This one should be fixed by https://github.com/o1-labs/snarky/pull/403
- [ ] Long async cycle happens around `Get_epoch_ledger` rpc call, still investigating (takes ~2min in release/0.0.9-beta, happens everytime when we do bootstrap)
UPDATE 10/25: The rpc call itself didn't take a lot of time. It's actually compute compute the root staged_ledger that takes a lot of time. @deepthiskumar 
https://github.com/CodaProtocol/coda/blob/60d28635becd43f57de9797a84d67fe7fc26f7bd/src/lib/staged_ledger/staged_ledger.ml#L230
The above function call takes ~30s in release/0.0.10-beta
The solution would be remove this check.
This one should be fixed by https://github.com/CodaProtocol/coda/pull/3782
- [ ] Long async cycle happens during catchup, still investigating (takes ~4min in release/0.0.9-beta, doesn't pop up everytime, I am guessing it happens around catchup)
UPDATE 10/29: This one is still mysterious to me, because this cycle contains several long async jobs of 6 secs, but in theory those jobs shouldn't be scheduled in 1 cycle. I hope https://github.com/CodaProtocol/coda/pull/3753 would mitigate the situations.

Low priority:
- [ ] not very long async cycle caused by scan state hashing (takes ~2s in release/0.0.9-beta, happens everytime when we do bootstrap)
https://github.com/CodaProtocol/coda/blob/be49825c20d7c9ffd57fe62c6718af542b8bf73e/src/lib/parallel_scan/parallel_scan.ml#L1008

**Comment by imeckler** [comment]
@nholland94 says every single transaction in apply_diff happens in a different deferred, so this ought not to be the issue.

**Comment by imeckler** [comment]
@ghost-not-in-the-shell @cmr and @nholland94 to sit down and 'hash' it out

**Comment by ghost-not-in-the-shell** [comment]
Computing the hash of scan state takes about 1-3 secs. But it is not the main reason for long async cycles. See `parallel_scan.ml line 1008`

**Comment by ghost-not-in-the-shell** [comment]
The `Staged_ledger.of_scan_state_pending_coinbases_and_snarked_ledger` is one of the main contributor to the long async cycles. It took ~90 secs. See `staged_ledger.ml` line 269

**Comment by ghost-not-in-the-shell** [comment]
For the 20s async cycle. I am suspecting it comes from `Staged_ledger.apply_diff`. Specifically, it comes from `transaction_snark_scan_state.ml`'s check_invariants function. This function would be trigger every time we propose or validate a network transition.

**Comment by ghost-not-in-the-shell** [comment]
I am also suspecting that the 2min async_cycles are caused by rpc calls. I think we should check those two: `get_staged_ledger_aux_and_pending_coinbases_at_hash` and `get_epoch_ledger`.

**Comment by ghost-not-in-the-shell** [comment]
bin_io takes 116 secs for `get_staged_ledger_aux_and_pending_coinbases_at_hash` rpc call. I believe that's reason for long async cycles.

**Comment by ghost-not-in-the-shell** [comment]
After dig deeper into this `get_staged_ledger_aux_and_pending_coinbases_at_hash` rpc call, I found out that decoding the scan state tree takes majority of time. Inside the scan state tree, we have many ledger proof. For the current testnet, there's on average about ~270 ledger proof and the decoding of each proof takes around ~0.065 sec. So in total it takes ~17 secs to decode the scan state.

**Comment by ghost-not-in-the-shell** [comment]
There should be another long async cycle happens around when sync the epoch ledger. But for the current testnet, the chain isn't long enough so I don't have a chance to see it. But I am assuming the decoding the sparse ledger takes most of the time.

**Comment by imeckler** [comment]
Deserializing proofs should basically be a `memcpy`, @ghost-not-in-the-shell can you investigate ?

**Comment by imeckler** [comment]
@ghost-not-in-the-shell can you make a prioritized list here and mark which ones are easy to fix and which ones you need a hand with?
