### ISSUE TITLE
"So you want to add a pinned opam to the docker..."

### ISSUE THREAD

**Issue by imeckler** [CodaProtocol/coda#3677]

**Comment by imeckler** [comment]
@cmr asks if this may already be documented in a markdown file

**Comment by imeckler** [comment]
One piece of this is, 

Docker containers should build from scratch instead of using ADD.

**Comment by imeckler** [comment]
@psteckler to add some information repinning in CI and the consequences of changing how we do pinning in the docker image

**Comment by psteckler** [comment]
There are two kinds of pinned opam packages, submodules and not-submodules, that have to be treated somewhat differently. I'd say that `external` needs a `submodules` directory to make that distinction clear.
