### ISSUE TITLE
[Metrics] Coda_Network_peers reporting incorrect data

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#3725]
This metric is reporting vastly higher values than there are peers on the network, in the words of @ghost-not-in-the-shell: "that metric is hopeless."

![image](https://user-images.githubusercontent.com/2635475/67343648-c10ead80-f4ea-11e9-9987-6537569ff7b3.png)

We should be able to fix it now that LibP2P has landed.

**Comment by imeckler** [comment]
@ghost-not-in-the-shell @jkrauska @cmr will discuss

**Comment by yourbuddyconner** [comment]
Any updates on this? @ghost-not-in-the-shell

**Comment by imeckler** [comment]
We currently don't remove peers from the peer list until the gossip layer detects them as down, this detection hasn't landed yet which is part of @cmr 's work.
