### ISSUE TITLE
[Metrics] Change where/when Coda_Proposer_slots_won is calculated

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#3726]
It appears that that the slots won and blocks proposed metrics mirror each-other exactly, and this implies to me that "slots won" is incremented when (or shortly before) the block is proposed.

It should be possible to increment this value when the VRF is computed instead, as the daemon is aware of how many slots it will win/has won at the beginning of each epoch. 

![image](https://user-images.githubusercontent.com/2635475/67343959-a1c45000-f4eb-11e9-8bc8-677131b2598d.png)

It seems more useful to have the the graph for "slots won" will inform the future state of "blocks proposed".

**Comment by imeckler** [comment]
In the current implementation we stop evaluating VRFs once we find the next slot one, so this is consistent with the current implementation. We could change this but that's how it is now anyway :)
