### ISSUE TITLE
Crash in 478b060

### ISSUE THREAD

**Issue by lyoungblood** [CodaProtocol/coda#3730]
Coda daemon crashed with a ton of output (lost any crash dump messages as it scrolled off) like this:

```8-51""Called from file \"src/scheduler.ml\", line 178, characters 10-30""Called from file \"src/scheduler.ml\", line 186, characters 2-12""Called from file \"src/raw_scheduler.ml\", line 676, characters 4-49""Called from file \"src/raw_scheduler.ml\", line 920, characters 6-16""Called from file \"src/raw_scheduler.ml\", line 924, characters 23-32""Called from file \"src/command.ml\", line 75, characters 21-
```

[coda_crash_report_2019-10-23_10-51-19.776228.tar.gz](https://github.com/CodaProtocol/coda/files/3762996/coda_crash_report_2019-10-23_10-51-19.776228.tar.gz)

**Comment by cmr** [comment]
Closing to track in https://github.com/CodaProtocol/coda/issues/3751, thank you for the report!
