### ISSUE TITLE
Crash Report 2019-10-23_18-48-59.479740 - CrisF#3405

### ISSUE THREAD

**Issue by Cris-F** [CodaProtocol/coda#3749]
Crashed overnight.  Woke up to it being down.
[coda_crash_report_2019-10-23_18-48-59.479740.tar.gz](https://github.com/CodaProtocol/coda/files/3764954/coda_crash_report_2019-10-23_18-48-59.479740.tar.gz)

**Comment by cmr** [comment]
Closing to track in https://github.com/CodaProtocol/coda/issues/3751, thank you for the report!
