### ISSUE TITLE
Coda Daemon crash report

### ISSUE THREAD

**Issue by byrongibson** [CodaProtocol/coda#3754]
[coda_crash_report_2019-10-24_08-16-56.253480.tar.gz](https://github.com/CodaProtocol/coda/files/3766423/coda_crash_report_2019-10-24_08-16-56.253480.tar.gz)

This crash happened a few seconds after I ran the following command on the commandline:

```bash
coda daemon \
-peer /ip4/52.39.56.50/tcp/8303/ipfs/12D3KooWHMmfuS9DmmK9eH4GC31arDhbtHEBQzX6PwPtQftxzwJs \
-peer /ip4/18.212.230.102/tcp/8303/ipfs/12D3KooWAux9MAW1yAdD8gsDbYHmgVjRvdfYkpkfX7AnyGvQaRPF \
-peer /ip4/52.13.17.206/tcp/8303/ipfs/12D3KooWCZA4pPWmDAkQf6riDQ3XMRN5k99tCsiRhBAPZCkA8re7 \
-propose-key .keys/coda-wallet.pub
```
Running without `-propose-key` appended works.  

Running with `propose-key .keys/coda-wallet` works (the private key file, not the public key file).

Running with `-propose-public-key` appended fails with error:

```
Error parsing command line.  Run with -help for usage information.
unknown flag -propose-public-key
```

`-propose-public-key` is suggested as an option in the `coda daemon -help` menu.  Might want to remove mention of that flag if it's not enabled.

**Comment by enolan** [comment]
It's removed in newer versions of the daemon. We've moved a bunch of stuff around in the CLI and a lot is changing. Thanks for the report!
