### ISSUE TITLE
Daemon Crash Report

### ISSUE THREAD

**Issue by novy4** [CodaProtocol/coda#3755]
[coda_crash_report_2019-10-24_09-26-44.030788.tar.gz](https://github.com/CodaProtocol/coda/files/3767643/coda_crash_report_2019-10-24_09-26-44.030788.tar.gz)

**Comment by o1pranay** [comment]
hey @novy4 thanks for reporting this one. We're tracking it in this issue here: #3751

closing it out because it's a dupe
