### ISSUE TITLE
Coda Daemon, Unhandled top-level exception: No child processes

### ISSUE THREAD

**Issue by sundafa** [CodaProtocol/coda#3775]
system: ubuntu 18.04
cmd: 
```
coda daemon \
    -discovery-port 8303 \
    -peer /ip4/52.39.56.50/tcp/8303/ipfs/12D3KooWHMmfuS9DmmK9eH4GC31arDhbtHEBQzX6PwPtQftxzwJs \
    -peer /ip4/18.212.230.102/tcp/8303/ipfs/12D3KooWAux9MAW1yAdD8gsDbYHmgVjRvdfYkpkfX7AnyGvQaRPF \
    -peer /ip4/52.13.17.206/tcp/8303/ipfs/12D3KooWCZA4pPWmDAkQf6riDQ3XMRN5k99tCsiRhBAPZCkA8re7
```

error info: Unix.Unix_error \"No child processes\"
[coda_crash_report_2019-10-25_03-50-06.014634.tar.gz](https://github.com/CodaProtocol/coda/files/3770283/coda_crash_report_2019-10-25_03-50-06.014634.tar.gz)

**Comment by o1pranay** [comment]
Hi @sundafa thank you for reporting this -- we are tracking the WNOHANG error here: #3520 

Closing this issue out to consolidate it in one place!
