### ISSUE TITLE
Require minimum amount and fee for txns

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#3830]
See also #3165

0 amount transactions don't 'do' anything. (except perhaps put a new account on the ledger)

0 fee transactions flood the network and aren't helpful (and may be harmful if they don't pay for snarks)

We should consider adding a minimum transaction amount (suggest 2) and a minimum fee amount (suggest 2). To ensure that all transactions that make it in to the queue are 'real' and could be purchased.  

This also helps dissuade making 'throw away' accounts. 

 min=2

**Comment by psteckler** [comment]
@enolan thinks this isn't a good idea.

I have an idea how to implement this, but I'll hold off until we have ... consensus on this issue.

**Comment by psteckler** [comment]
@jkrauska Can this be closed, since #3892 is merged? We filter by fee, but not by amount now.
