### ISSUE TITLE
Crash daemon 22.11

### ISSUE THREAD

**Issue by Igor-Tselkovskiy** [CodaProtocol/coda#3979]
[coda_crash_report_2019-11-22_14-36-15.213366.tar.gz](https://github.com/CodaProtocol/coda/files/3882031/coda_crash_report_2019-11-22_14-36-15.213366.tar.gz)
[coda_short.log](https://github.com/CodaProtocol/coda/files/3882032/coda_short.log)

**Comment by bkase** [comment]
Closing because this looks like it was caused from a SIGABRT trigger on a snark worker. We'll reopen if this happens to too many other folks and warrants an investigation to get a better error message
