### ISSUE TITLE
Daemon crashed

### ISSUE THREAD

**Issue by petemccarthy** [CodaProtocol/coda#4009]
I was trying to launch a node that was staking.
[coda_crash_report_2019-12-05_07-42-20.926952.tar.gz](https://github.com/CodaProtocol/coda/files/3925636/coda_crash_report_2019-12-05_07-42-20.926952.tar.gz)

**Comment by bkase** [comment]
`IO error: While lock file: /Users/pete/.coda-config/trust/LOCK: Resource temporarily unavailable`

@petemccarthy this crash means you have some running Coda process somewhere else on your system

We should definitely fix this error message, but if you try a `ps aux | grep coda`, kill anything you see there, and re-run it should work

Closing for now, please re-open if you still see this error after trying that.
