### ISSUE TITLE
Resolve async_ssl issues with openSSL1.1 on mac + brew

### ISSUE THREAD

**Issue by Schmavery** [CodaProtocol/coda#4019]
Brew recently removed openSSL1.0 and now installs OpenSSL1.1. This is causing issues with async_ssl, getting errors like this when building:

```
Undefined symbols for architecture x86_64:
  "_ERR_load_crypto_strings", referenced from:
      _async_ssl_stub_14_ERR_load_crypto_strings in libasync_ssl_stubs.a(ffi_generated_stubs.o)
     (maybe you meant: _async_ssl_stub_14_ERR_load_crypto_strings)
  "_OpenSSL_add_all_ciphers", referenced from:
      _async_ssl_stub_9_OpenSSL_add_all_ciphers in libasync_ssl_stubs.a(ffi_generated_stubs.o)
     (maybe you meant: _async_ssl_stub_9_OpenSSL_add_all_ciphers)
  "_OpenSSL_add_all_digests", referenced from:
      _async_ssl_stub_8_OpenSSL_add_all_digests in libasync_ssl_stubs.a(ffi_generated_stubs.o)
     (maybe you meant: _async_ssl_stub_8_OpenSSL_add_all_digests)
  ...
```

The async_ssl library is an optional dependency of cohttp, which uses it to make requests over https. It seems that we only use this in one place currently -- to find the external IP address. https://github.com/CodaProtocol/coda/blob/develop/src/app/cli/src/init/find_ip.ml

Note: it does seems that async_ssl is happy to build against OpenSSL1.1, the hypothesis is that some issue with the LD_LIBRARY_PATH or pkg-config settings is causing the system OpenSSL to get picked up instead.  More investigation is required.

As a workaround to enable shipping the daemon via brew on mac, we're removing async_ssl and requesting the IP over http. This issue tracks switching back to https.

cc @bkase

**Comment by Schmavery** [comment]
For now the workaround is to `opam uninstall async_ssl`

**Comment by imeckler** [comment]
The current plan is just to shell out to `curl` whenever we need to use `https`.
