### ISSUE TITLE
Fatal error soon after starting coda deamon

### ISSUE THREAD

**Issue by smartins** [CodaProtocol/coda#4024]
Attached is the crash report as requested. Ubuntu 18.04 LTS, c5.2xlarge on AWS.

```
2019-12-06 18:14:39 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error\n  \"RPC #72 failed: \\\"internal RPC error error: input isn't valid multihash\\\"\"\n  (\"Raised at file \\\"src/error.ml\\\" (inlined), line 9, characters 14-30\"\n
  \"Called from file \\\"src/or_error.ml\\\", line 72, characters 17-32\"\n    \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"


  ☠  Coda daemon crashed. The Coda Protocol developers would like to know why!
```

[coda_crash_report_2019-12-06_18-14-39.707581.tar.gz](https://github.com/CodaProtocol/coda/files/3933468/coda_crash_report_2019-12-06_18-14-39.707581.tar.gz)

**Comment by bkase** [comment]
@smartins I'll cut a new release to hotfix this soon! For now, you can workaround by force-installing version 0.0.11-beta2

**Comment by smartins** [comment]
Thanks, I installed version 0.0.11-beta2 as a temporary "fix". Should I go ahead and install the latest version now?

**Comment by bkase** [comment]
Should be fixed with the latest version
