### ISSUE TITLE
[Feature Request] Allow bi-directional delegate query in GraphQL

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#4044]
Currently, it is possible to query an account (A) and get the public key of the account (B) it is delegating to. However, it is not possible to query the account (B) that was delegated to and get the public key of the account(s) delegating to it. 

This sort of bi-directional relationship is important to be able to query via GraphQL. 

This works: 
```
query DelegateAccount {
  account(publicKey: "tdNE5By1TGtHVAHG2MgL6zAZ1NjchrvvdNUgYPm8wb3cULZCWCHPwm64yDM67UH7yWwLok1Hv3csj9NUzkTz13uLsc89S7m9HZMgH2XMWVb8FcxMoVHw3jnD9iytniStDjBe84ZV6CYqYE") {
    delegateAccount {
      publicKey
    }
  }
}
```

Returns: 
```
{
  "data": {
    "account": {
      "delegateAccount": {
        "publicKey": "<DELEGATE-PUBLIC-KEY>"
      }
    }
  }
}
```

I would like the opposite to work as well: 
```
query DelegatorAccounts {
  account(publicKey: "<DELEGATE-PUBLIC-KEY>") {
    delegatorAccounts {
      publicKey
    }
  }
}
```

Should Return: 
```
{
  "data": {
    "account": {
      "delegatorAccounts": [
          {
            "publicKey": "tdNE5By1TGtHVAHG2MgL6zAZ1NjchrvvdNUgYPm8wb3cULZCWCHPwm64yDM67UH7yWwLok1Hv3csj9NUzkTz13uLsc89S7m9HZMgH2XMWVb8FcxMoVHw3jnD9iytniStDjBe84ZV6CYqYE"
          }
      ]
    }
  }
}
```

**Comment by bkase** [comment]
In addition to the above, we'll also want to track the last epoch's delegators as well.

I propose the following API:

```
query DelegatorAccounts {
  account(publicKey: "<DELEGATE-PUBLIC-KEY>") {
    stakingLedger {
      epoch
      totalCurrency
      accounts {
        publicKey
      }
    }
    lastStakingLedger {
      epoch
      totalCurrency
      accounts {
        publicKey
      }
    }
  }
}
```

Implementation details:

* Change delegatee_table to store full accounts as well public keys
* Keep an extra last_delegatee_table that stores the ones in the prior epoch
* Expose the delegatee_table in the consensus_intf.ml interface
* Access it from the graphql system to expose the above API

**Comment by Schmavery** [comment]
done
