### ISSUE TITLE
Reintegrate Bootstrap_controller Unit Tests

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#4049]
Some `Bootstrap_controller` tests were disabled in order to land the transition frontier persistence branch before it bitrot. These should be added back in ASAP to prevent new `Bootstrap_controller` bugs from being introduced.

**Comment by ghost-not-in-the-shell** [comment]
Currently I am blocked by a weird behavior in the fake_network layer.

After tinkering around, I got to a state that the test was able to compile but failed to succeed. It seemed like `get_ancestry` RPC is failing. So I added a logger to the `get_ancestry` RPC handler in `fake_network.ml` ~line 103. I did see the log being printed but the log in `Sync_handler.Root.prove` is lost somehow. I tried to use `printf` instead, but it still didn't show up.

**Comment by imeckler** [comment]
By @ghost-not-in-the-shell : merged, with the exception of 1 test in `bootstrap_controller.ml`
