### ISSUE TITLE
Snark node crash

### ISSUE THREAD

**Issue by wjdfx** [CodaProtocol/coda#4088]
`Dec 14 10:59:39 ip-172-25-236-201 bash[20479]: Generating crash report`

[crash_log.log](https://github.com/CodaProtocol/coda/files/3963787/crash_log.log)

**Comment by gregbostrom** [comment]
```
exn: "(monitor.ml.Error\n  (Failure\n     \"indexed pool nonces inconsistent when adding from backtrack. 
```
Looks like another occurrence of 
https://github.com/CodaProtocol/coda/issues/4078

**Comment by bkase** [comment]
Dupe of #3644 ; thanks for reporting!

**Comment by bkase** [comment]
Actually let's dedupe with #4066
