### ISSUE TITLE
CrisF - coda_crash_report_2019-12-16_04-14-59.694998

### ISSUE THREAD

**Issue by Cris-F** [CodaProtocol/coda#4089]
I returned to find my daemon down.  
Was running block producer and snark-worker simultaneously.
Hope this helps.
CrisF
[coda_crash_report_2019-12-16_04-14-59.694998.tar.gz](https://github.com/CodaProtocol/coda/files/3967443/coda_crash_report_2019-12-16_04-14-59.694998.tar.gz)

**Comment by bkase** [comment]
Thanks for reporting! Dupe of #3644

**Comment by bkase** [comment]
Actually let's dedupe with #4066
