### ISSUE TITLE
Snarks worker not running (team name: skultra)

### ISSUE THREAD

**Issue by Taaseen-Ali** [CodaProtocol/coda#4138]
We attempted to run a delegate and snark worker and kept running into the attached error. 
[coda_crash_report_2020-01-07_05-43-42.266868.tar.gz](https://github.com/CodaProtocol/coda/files/4029050/coda_crash_report_2020-01-07_05-43-42.266868.tar.gz)

**Comment by nholland94** [comment]
@Taaseen-Ali The error I see in the logs is `IO error: While lock file: /home/captain/.coda-config/trust/LOCK: Resource temporarily unavailable`. This indicates you were running 2 nodes on the same system with the same config directory, which is disallowed. The lock file helps us to ensure two nodes don't run at the same time and attempt to read/write the same data from/to disk.

**Comment by bkase** [comment]
We need to improve this error message! Thanks @Taaseen-Ali
