### ISSUE TITLE
Move genesis timestamp out of compile-time to runtime

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4195]

**Comment by aneesharaines** [comment]
Check w/ @yourbuddyconner to see how much time this would save in the near term

**Comment by yourbuddyconner** [comment]
This would save ~1h / build as the workflow currently is to rebase a branch off of develop with the appropriate timestamp. 

Ultimately some infrastructure machinery is going to have to be built around this feature so would be nice to have a spec sooner rather than later.

**Comment by psteckler** [comment]
I'm told @nholland94 will write up something on how this should go.

**Comment by aneesharaines** [comment]
![IMG_20200221_161428](https://user-images.githubusercontent.com/27711349/76346543-7091c400-62c2-11ea-82bb-b8452eb3527f.jpg)
