### ISSUE TITLE
Signaling -- Look at the 32 byte string

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4200]
Decide whether or not to fork based on the percentage of blocks

**Comment by imeckler** [comment]
Check with @es92 on what the actual behavior should be for consensus nodes

**Comment by nholland94** [comment]
Let's scope this to the validation portion of the logic described in https://github.com/CodaProtocol/coda/issues/4199#issuecomment-583174832. We will implement bitcoin style [MASF](https://bitcoin.org/en/glossary/masf) as another issue later.
