### ISSUE TITLE
b58.ml has pathological runtime on large inputs

### ISSUE THREAD

**Issue by emberian** [CodaProtocol/coda#4236]
Seems to be roughly quadratic for every 1k after ~23k ish. @nholland94  and I think carry propagation is hitting some pathological behavior, but don't feel like understanding+fixing the root issue. I switched over coda_net2 to use base64 with the helper protocol. We should add an assert in Base58_check.encode that the input size isn't too large (I propose 8K as a reasonable max) and accidentally causing us long jobs.

**Comment by psteckler** [comment]
#4299 puts in the length check.
