### ISSUE TITLE
Consider making the merkle tree index part of a public key

### ISSUE THREAD

**Issue by imeckler** [CodaProtocol/coda#436]
Our code would die if there were multiple merkle accounts with the same public key

**Comment by cmr** [comment]
I believe we considered this and decided to not do it, either because it's not necessary or the feature we tried to support with this didn't work out for other reasons.

**Comment by enolan** [comment]
see also #1916

**Comment by imeckler** [comment]
i'm going to close this for now as it would be a giant headache as per echo's comments in #1916
