### ISSUE TITLE
Official Coda Restart Script (macos/brew)

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4402]
The problem:

Coda sometimes crashes and will continue to sometimes crash for the short future. Sophisticated testnet users are running restart scripts

A proposal:

Change `coda` to instead be a wrapper script that calls the `coda.exe` binary in such a way to trap errors and restart gracefully.

We must ensure that we don't end up in an insta-crash loop. If we crash in a loop, we should exit and show the errors to the user.

The other consideration is how to surface these crashes to the developers.

Note: Several community members have created scripts so we can see if any of them can be used here. Whatever we come up with should be x-platform at least between Debian/Ubuntu and MacOS

**Comment by Schmavery** [comment]
https://github.com/CodaProtocol/homebrew-coda/pull/3

**Comment by Schmavery** [comment]
Can linux users be persuaded to use https://github.com/jkrauska/coda-systemd ?

**Comment by Schmavery** [comment]
Tracking Linux support in #4493
