### ISSUE TITLE
Wallet: Update to support new Coda decimals

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4405]
With the addition of decimal precision we must update how we handle displaying units of Coda across the wallet. Under the new system the smallest denomination of Coda is 1 nanoncoda which is equivalent to 10^-9 Coda. As such all the values returned from GraphQL must be formatted properly. 

One way to handle this is to duplicate the logic we added to the `lib/currency` package to the Wallet with a new `Currency` module which has an internal `type t = int64`. The methods are `to_formatted_string` and `of_formatted_string` which convert between a `Currency.t` and a string with the decimal representation. Here’s some examples:

```reason
let example1 = of_int(1);
to_formatted_string(example1);
# 0.000000001

let example2 = of_int(4_209_100_000);
to_formatted_string(example2);
# 4.2091

let example3 = of_int(90_000_000_000);
to_formatted_string(example3);
# 90
```

The `of_formatted_string` performs the inverse operation. 

This formatter needs to be used whenever we display an amount of currency throughout the app. This could conceivably be broken up into a follow on PR since that’s likely to be a lot of work.

**Comment by Schmavery** [comment]
https://github.com/CodaProtocol/coda/blob/72df07aeb0e52c0c73d14cd2eea5daeed19d06fb/src/lib/currency/currency.ml#L78-L106

for reference
