### ISSUE TITLE
Script to invoke the best tip from neighbors

### ISSUE THREAD

**Issue by aneesharaines** [CodaProtocol/coda#4430]

**Comment by aneesharaines** [comment]
Done but needs a deployment method.  @yourbuddyconner  is working on that.

**Comment by aneesharaines** [comment]
@yourbuddyconner  - working on a way to deploy in the test net.  Any update?

**Comment by yourbuddyconner** [comment]
I took some time today to slap together the rest of the script. It can be deployed locally for adhoc testing, I am going to include it in a future commit to `coda-automation` but here it is for posterity: https://gist.github.com/yourbuddyconner/ea9aeb5729722cc1a1d4ba2a5ac27b31

**Comment by psteckler** [comment]
The script(s) were included in the `coda-automation` commit `cf53839b4d59da9fdd2c6884b34197faf63936c9`
