### ISSUE TITLE
Review/implement schema for tokens & graphql

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4447]
(This is @Schmavery writing, hijacking this empty description)

@mrmr1993 made a really helpful summary of the proposed changes to the protocol here: https://gist.github.com/mrmr1993/1c424644a597aa9ef6bda888616f2d06

This issue attempts to publicize some attempts/discussion of how to expose this new functionality to users in the context of our existing APIs

**Comment by Schmavery** [comment]
As I'm brainstorming how to integrate this, I'm writing out several potential queries/mutations that could be made against the new endpoints to visualize how the api could be used. I find it easier to think about than the schema definition.

```graphql
query QueryAccountTokens($pk: PublicKey!) {
  account(publicKey: $pk) {
    tokens { # list, includes default
      id
      balance {
        total
      }
    }
  }
}

query QueryAccountToken($pk: PublicKey!, $id: TokenID!) {
  account(publicKey: $pk) {
    token(id: $id) { # list, includes default
      balance {
        total
      }
    }
  }
}

query QueryTokens($id: TokenID!) {
  token(id: $id) {
    id
    publicKey
    balance {
      total # default token balance
    }
  }
}

mutation MintNewToken($pk: PublicKey!) {
  mintToken(payload:{
    publicKey: $pk, # is there a better name, what does this pk represent?
    numberOfTokens: 100,
    feePublicKey: $pk, # optional
    feeTokenID: 0, # optional
    fee: 10,
  }) {
    token {
      id
    }
  }
}

mutation MintExistingToken($pk: PublicKey!, $id: TokenID!) {
  mintToken(payload:{
    publicKey: $pk,
    tokenID: $id
    numberOfTokens: 100,
    feePublicKey: $pk, # optional
    feeTokenID: 0, # optional
    fee: 10,
  }) {
    token {
      id
    }
  }
}
```

**Comment by Schmavery** [comment]
Changes to existing mutations:
```diff
SendPaymentInput {
  nonce: Int!
  from: PublicKey!
  to: PublicKey!
+ token: Token # If not specified, default token is used
+ feePayer: PublicKey # If not specified, `from` is used
+ feeToken: Token # If not specified, default token is used
  amount: UInt64!
  fee: UInt64!
  memo: String!
}

SendDelegationInput {
  nonce: Int!
  from: PublicKey!
  to: PublicKey!
+ feePayer: PublicKey # If not specified, `from` is used
+ feeToken: Token # If not specified, default token is used
  fee: UInt64!
  memo: String!
}
```

Right now these mutations also accept an optional `signature` (string) field. We should probably add an optional `signatures` (or "otherSignatures"?) which lets you pass in an array to support multisig

**Comment by Schmavery** [comment]
Approved accounts:

Thought: We have `approved_accounts_only` but the mutations are called `enable`/`disable`. Maybe it should be `enabled_accounts_only`?

-- alternatively --

 Should enable/disable be "setAccountApproval" and accept a boolean for whether it is enabled/disabled.

```graphql
mutation EnableAccount($pk: PublicKey!, $id: TokenID!) {
  enableAccount(payload:{
    tokenOwner: $pk,
    target: $pk, # Or publicKey/account/enabledAccount???
    token: $id # Or `tokenID`
    feePayer: $pk, # optional, defaults to creator pk
    feeToken: 0, # optional, defaults to default token
    fee: 10,
  }) {
    account {  publicKey }
    token { id }
  }
}

mutation DisableAccount($pk: PublicKey!, $id: TokenID!) {
  ... same as above
}
```

**Comment by mrmr1993** [comment]
> Thought: We have `approved_accounts_only` but the mutations are called `enable`/`disable`. Maybe it should be `enabled_accounts_only`?

That sounds better to me, much nicer to be consistent! I'll update the gist.

**Comment by Schmavery** [comment]
I'm going to leave out feeToken for now, since it seems like it still needs some fleshing out product-wise before it's usable. i.e. block producers needing to specify an exchange rate for every token etc
