### ISSUE TITLE
Node failed to collect any peer during initialization

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [CodaProtocol/coda#4483]
In our Gerald QA net, I found that some node failed to collect any peer in the initialization phase upon restart. In current implementation, the node would wait 60s to collect at least 4 peers, and then it would request their best tips to determine the current condition of the network. If a node fails to collect any peer during initialization, then it would falsely believe that the network has just been spawned and start a new chain off the genesis block. This could be one the reason that our QA net is forky when k is small and a lot of nodes are doing restart.

**Comment by aneesharaines** [comment]
Will check the new QA net to see if it's still an issue

**Comment by aneesharaines** [comment]
@emberian  has a pr that tweaks the parameters to help with this issue.  Need to check if this still happens and is actually a bug.

**Comment by aneesharaines** [comment]
@emberian @ghost-not-in-the-shell  - we aren't still seeing this in the new networks are we?  Can this be closed?

**Comment by emberian** [comment]
I'm going to say yes!
