### ISSUE TITLE
Broken link on the website

### ISSUE THREAD

**Issue by nat8552** [CodaProtocol/coda#4484]
Hello guys,

https://codaprotocol.com/glossary/#peer-to-peer returns 404 error

**Comment by Schmavery** [comment]
Hey @nat8552, what page did you find this on? Seems like it should be `https://codaprotocol.com/docs/glossary#peer-to-peer`

**Comment by nat8552** [comment]
Here it is:
https://codaprotocol.com/docs/my-first-transaction
http://prntscr.com/rb9k3q

**Comment by Schmavery** [comment]
@nat8552 it should be fixed now, thanks for the help!
