### ISSUE TITLE
Realistic token balances in accounts

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4503]
## Goal

Make token amounts more realistic so that people have proper expectations going into mainnet.

## Background

We have to make a choice to either make the total tokens in the network realistic _or_ to make the total tokens per user account (individuals that signup to stake in 3.2) realistic.

I don't think we want to do both because that would make the O(1) nodes have too much stake (such that our testnet wouldn't be very interesting!)

## Proposal

User accounts target 66,000.00 tokens for genesis ledger. We then put 40% to O(1) nodes and 60% to the users for everyone that signs up to stake.

**Comment by Schmavery** [comment]
I think this is done now
