### ISSUE TITLE
Random killing of nodes in the QA net --- need to make sure that there are other nodes that are already sync'd to the main chain (Nathan has an existing script)

### ISSUE THREAD

**Issue by aneesharaines** [CodaProtocol/coda#4507]

**Comment by psteckler** [comment]
Conner says there's an existing tool called "Pumba" that will do this for us.

This is a related link: https://github.com/ishantanu/pumba-helm

**Comment by aneesharaines** [comment]
Needs to be merged into the main branch.

**Comment by imeckler** [comment]
@emberian says the script is in the automation repo
