### ISSUE TITLE
Validation failure for blocks.

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [CodaProtocol/coda#4557]
#4533 is a temporary hack to by pass the topic validation in libp2p. The reason we introduced this hack is because validation was failed in both the qa net and integration tests which caused forkiness.

Here's how the block validation for network transitions is done in OCaml side:
1. An "validate" upcall send from libp2p to coda daemon is capture in coda_net2.ml line 734.
2. It would call the "validator" function on the message. "validator" is set when subscription is created in libp2p.ml line 233.
3. The "validator" function would write the message and a call back function to the "message_writer" pipe. The reader end of this pipe would be exposed through Gossip_net.Any.received_message_reader.
4. received_message_reader pipe is consumed in the coda_networking line 891,
depending on the type of the messages, it would be processed differently. For transitions, it would be written into Coda_networking.states pipe.
5. Coda_networking.states pipe is then consumed by transition router. The redirection happens in coda_lib.ml line 901 where transitions in Coda_network.states pipe is transferred in the network_transition_reader pipe in transition_router.
6. Inside Transition_router,  the network_transition_reader pipe is redirected to Initial_validator.
7. Inside Initial_validator, transitions would go through several checks (duplication check, validate_time_received, validate_genesis_protocol_state, validate_proof and validate_delta_transition_chain). If all the check passes, then the validation_callback is set to validation_callback in exterrnal_transitions. If the validation isn't successful, then we call validation_callback with false which notify libp2p that validation fails.
8. Once transitions pass initial validation, depending on the state of node, they would be either passed to transition_frontier_controller or bootstrap controller.
9. Let's say transitions are passed to transition_frontier_controller. Then it would be redirected to Transition_handler.Validator in transition_frontier_controller.ml line 67.
10. If validation passes again, then the transitions would be written into the processed_transition pipes and this pipe is consumed in coda_lib where we would be check to see if those transitions are appropriate for rebroadcast by checking their receiving time. If so, the validation callback would be called with true.

**Comment by ghost-not-in-the-shell** [comment]
Block produced by oneself would be gossiped twice. But I don't think that's the bug.

**Comment by ghost-not-in-the-shell** [comment]
One suspecious thing is that when a message validation is timed out, the lock `ValidatorMutex` is never set to `Unlock`.

**Comment by ghost-not-in-the-shell** [comment]
I fixed the `ValidatorMutex` bug and the block being gossiped twice bug in this PR https://github.com/CodaProtocol/coda/pull/4558

**Comment by aneesharaines** [comment]
We should try on the QA net before merging.
