### ISSUE TITLE
Script for Telemetry Part 1

### ISSUE THREAD

**Issue by aneesharaines** [CodaProtocol/coda#4587]

**Comment by aneesharaines** [comment]
Prelim version is done, doesn't persist results waiting until Conner gets back.

**Comment by psteckler** [comment]
Updated script to use peer ids, per changes in the RPC output.

Script is in `feature/telemetry-fixpoint`.

**Comment by imeckler** [comment]
@psteckler has tested the script and has shared it with @yourbuddyconner -- at this point, deciding about deployment and so on should be done by team B

**Comment by aneesharaines** [comment]
Created #4950 to track on infra side so moving this to closed since there is no more protocol work to be done.
