### ISSUE TITLE
[Bug] State Hashes in logs output in wrong format

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#4678]
Example State Hash from GraphQL: 
`6hrsesesE46ztiKHYkmtaiiduvn2uFP4q8tPyScMQU4YLq22T6WnRxsyMTMXfFjYo82L2mpv5PGHR5RWwBkSRx4uEC7YpiTESraYc5ymr3PWiTGeX2RjbMUfsrDx3jPuE6UnAJapTN121`

From the logs: 
`37780740477173221906691743855027905743526794705424875591494107167383834935834536470919985356117919455873839772308127760172511970833016041879842080070355197754720425479330354831215207170936030648632962098974248179900434037950089`

**Comment by aneesharaines** [comment]
Already fixed in the release branch.  Just needs to be merged to develop.

**Comment by aneesharaines** [comment]
Closed as this should have been moved as part of the overall port
