### ISSUE TITLE
Empower individual engineers to validate and test their changes

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4737]
Only a few engineers on our core team are capable of deploying QA-testnets and other infrastructure necessary to test new features or bugfixes. This is a bottleneck that we aim to remove.

Friction points:
* Infrastructure information is in a separate repository and cannot update in lockstep nor CI along with Coda's changing repo.
* There is not enough knowledge shared around how to do this properly
* There is a belief that if CI passes it's good to merge
* Change culture around what is required to test a protocol or product change
* We have many config.mlh profiles (most of which we don't use or can obsolete when we finish moving over to runtime genesis) -- hard to know which one is right for the task at hand

Potential ideas:
* Discontinuous integration:
    * If I force push to `env/staging1`, automatically redeploy a new network with my configuration
    * An easy "one-click" deploy a staging network (in CI?)
* Share knowledge and creds and culture
* Config.mlh culling and renaming of profiles

Exit Criteria:
* . >50% of protocol team and >50% of product team has successfully deployed QA-net-infrastructure without help
* Solution for sharing keys (covered in #4722 )
* Configuration of networks requires minimal knowledge of infra code -- at the most requiring just 1 or 2 top-level files being touched (covered in #4723)
* Minimal config.mlhs, all unnecessary ones removed, files named properly (covered in #4756)

**Comment by yourbuddyconner** [comment]
Relates to #4723

**Comment by bkase** [comment]
Enveloped by #4723
