### ISSUE TITLE
Docker toolchain rebuilds take over an hour

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4754]
## Problem

Docker toolchain rebuilds take over an hour to complete. If there is any iteration involved sometimes this can eat more than a day. This doesn't need to happen too often, but it does need to happen sometimes, and when it does it's very annoying.

## Proposal

Move as much as we can out of the toolchain and into CI proper. Example: Rather than caching opam deps in the toolchain, cache the `~/.opam` folder across builds. Look to the macOS build on circle as an example of how we cache there. This needs to be fleshed out further.

In the short term, @mrmr1993 is going to strip out the spacetime build from the toolchain as we don't use it anymore.

Exit Criteria:
* Investigate to caching `~/.opam` in builds, if it doesn't work within a day or so of effort. Punt on it for now.

**Comment by bkase** [comment]
I prototyped what it would look like for Nix to build the toolchain docker container. This way we can effectively incrementally cache all of the toolchain build in a way that isn't possible with raw Docker.

From a Linux context with nix installed (use `nixos/nix` container if you're on macOS)

Create a `docker.nix` file:

```
{ pkgs ? import <nixpkgs> {} }:


pkgs.dockerTools.buildImage {
  name = "test";
  tag = "latest";
  contents = [ pkgs.hello pkgs.cmake ];
}
```

Run `nix-build docker.nix` and you are presented with a `tar.gz` that you can feed into `docker load` like so:

```
docker load < /nix/store/67b1k3vc6fnfw6947zvzq133f6ghdiaq-docker-image-test.tar.gz
```

Then you can run hello:

```
docker run -it test:latest hello
```

`buildImage` builds everything in a single layer, but you can use `pkgs.dockerTools.buildLayeredImage` to build a layered one if that's desired. You can also use `fromImage` to change the base image from "scratch" the default, to whatever (created from `docker save`) -- I tested to see if we could use our existing base image `ocaml/opam2:debian-9-ocaml-4.08` and add nix-built things on top -- and we can. See https://nixos.org/nixpkgs/manual/#sec-pkgs-dockerTools for further docs.

The nice thing about this is that _unlike_ a `RUN apt install hello make gcc # etc` when you add a new package, you only have to download that single new package -- contents are cached incrementally. The order of the `RUN` commands no longer dictate the cache-ability of the programs as well.

Looking at `Dockerfile-toolchain` in detail, this would work well and require minimal effort for:

1. All of our system binary dependencies (cmake, jq, m4, nodejs, python, etc)
2. Any gems or python (pip) packages
3. The random things we install (nix, rocksdb)

It will be harder for:

1. Any opam things; The `opam switch import` step, package pinning
2. Install the dev-dependencies for C++ stuff (libboost-dev, libffi-dev, etc) such that they're visible by the parts of the build that depend on it.

Thus, I still think we should try caching of `~/.opam` and ripping that out of the toolchain for now (as 1 is hard anyway).

---

You may ask:

If everything is cached, then why do we even need to build a toolchain container in the first place? Can't we just copy the cache over when we do CI builds?

Yes, exactly. I wish time were infinite and then we could just do that. I'm imagining it will take quite a while to get to this world though.

---

I don't think this approach is worth the time investment for it to really pay off on the "now" timescale but could be worth picking back up in the future.

**Comment by bkase** [comment]
Explore staging

**Comment by psteckler** [comment]
For `.opam`, when it's built in docker, the build cost is amortized over all CI jobs until the next toolchain build.

If you build `.opam` in CI, the cost is amortized only in the current CI pipeline. Or do you mean something else?

**Comment by mrmr1993** [comment]
> If you build `.opam` in CI, the cost is amortized only over the current CI pipeline.

The idea was to use caching so that
* usually the cache contains the `.opam` directory with the correct libraries installed, akin to them being in the docker image
* when we want to change things in `.opam`, we use the cache to avoid a full rebuild, and those things that do need a rebuild are committed to new cached version.
