### ISSUE TITLE
Integration Testing: Detail plan for setting up structured events

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#4759]
Part of epic #4735. We need structured, pre-defined events in order to have a robust, type-safe DSL for writing protocol integration tests in. This is something I have been thinking about and planning out in recent times (especially related to OpenTracing work). As such, I will write up my thoughts and ideas about this and how we can utilize structured events across our logger, OpenTracing, and our integration test suite.

**Comment by nholland94** [comment]
I need to pass this off to someone else as there is too much on my plate. I will write up requirements and considerations regarding how structured events should be implemented.

# Requirements

- There is a shared module across the code codebase which declares all the structured events up front (along with the log message and metadata for these events)
  - each structured event includes
    - a display message for the event
    - a typed set of metadata emitted with the event
    - a unique id (either derived or enforced by a ppx)
 	  - one easy option here may be setting the id to be the hash of the message template, and then just checking for collisions
  - logger supports emitting unstructured or structured events
    - logger format would remain the same, except that structured event logs would be emitted with an id
    - thinking forward to the opentracing world, it would make sense to build this to later support enter and exit logs for events (without having to redo all the logging later)
  - logproc supports quick filtering of structured events by id
    - it should know the event names and be able to map them to event ids

# Implementation Considerations

- these structured event definitions will be consumed from both the logger and the jaeger open tracing stuff that is currently planned for development very soon
  - if there are necessary changes to requirements or questions about a compatible interface for that, please ask me as I am currently investigating and have some code around open tracing + jaeger
- there will be dependency cycle with the logger module implementation under this, so the logger needs to be abstracted (probably functored) over the structured event definitions
  - to avoid functor hell, `coda_base` or an equivalent layer of the code should export an instantiated logger
  - if there isn't a good place in the code to have a single instantiation (because some calls to the logger are lower in the dep graph than the structured event type defs), then the logger can use a GADT trick like what we do for merkle ledgers and verifier processes to make a logger that only supports unstructured logs available at those scopes

**Comment by psteckler** [comment]
For the event declaration, @mrmr1993 suggests:
```ocaml
type Structured_event.t += My_structured_event of Time.t * Time.t * bool [@@deriving structured_event {msg= "Saw my structured event from $1 to $2. Bool=%3"}]```

**Comment by psteckler** [comment]
@psteckler responds to this suggestion:

that template would be a function that takes the id and log message, then unstringifies each interpolated argument, and applies the constructor to them?

since there would be many declarations, I think you need a dispatching functions that takes the id, sends the log msg to the right function
the declaration would register the function

**Comment by psteckler** [comment]
and @mrmr1993 adds:

think the actual arguments should be carried outside of the message as well, to make getting them back easy

**Comment by psteckler** [comment]
since we'll receive the metadata as strings, we might need to specify `of_string` functions for them in the declaration

**Comment by mrmr1993** [comment]
> we might need to specify `of_string` functions for them in the declaration

If we're integrating this with our existing logging, I think it makes sense (and keeps things easy) if we use JSON for this.

**Comment by nholland94** [comment]
I think that structure for the ppx makes a lot of sense. Some additional thoughts on it:

The way metadata works in the existing logger, each metadata field has a name associated with it. Initially, I thought it would be fine to forego this detail, but I think it will actually be easier to integrate into our logger and consume externally if we keep that. We can easily achieve this using the following syntax.

```ocaml
type Structured_event.t += My_structured_event of {start_time: Time.t; end_time: Time.t; successful: bool} 
[@@deriving structured_event {msg= "Saw my structured event from $start_time to $end_time. Bool=$successful"}]
```

You can then have a function with label arguments that constructs log messages for this event. You could either do that by generating a function from the deriver like `my_structured_event ~start_time ~end_time ~successful`, or you could do a GADT trick if you are feeling fancy (inject the record type as a parameter to the structure event type, create a function `constructor_of_event : 'a Structured_event.t -> 'a` which you can extend using a number of tricks).

> If we're integrating this with our existing logging, I think it makes sense (and keeps things easy) if we use JSON for this.
This is true, but you lose some type safety if you make every metadata field for an event of the type `Yojson.Safe.t`. It would be nice to derive yojson for the type of the constructor args for each `Structure_event.t` constructor so that we enforce what types are passed in when you construct structured logs.

**Comment by psteckler** [comment]
Do we need to be able to build the event from log messages? What data would we have, just the message, the id, the metadata as a list of strings?

**Comment by nholland94** [comment]
Yes, but we don't need to worry about building from the log message for right now. We can plan for it, but I think it's a while away before we will be utilizing something that does that in OCaml natively. The important thing we have right now is a function `event -> string * metadata` where `type metadata = (string, Yojson.Safe.t) list`. The `id` of the event would be encoded in the metadata, perhaps under a key such as `event_id`.

**Comment by mrmr1993** [comment]
> We can easily achieve this using the following syntax.

That's exactly what I had in mind, yea. I posited the other syntax because I thought we might also want something for positional arguments, but we could probably skip that for the initial version.

> This is true, but you lose some type safety if you make every metadata field for an event of the type `Yojson.Safe.t`. It would be nice to derive yojson for the type of the constructor args for each `Structure_event.t` constructor so that we enforce what types are passed in when you construct structured logs.

Agreed; I mentioned JSON to contrast it to the stringly-typing approach in the draft PR.

For a concrete proposal of what I was expecting:

`Structured_event.mli`:
```ocaml
type t = ...

type id [@@deriving eq]

val id_of_string : string -> id

type repr = {log: t -> string * id * Yojson.Safe.json list; parse: id -> Yojson.Safe.json list -> t option}

val register_constructor : repr -> unit

val log : t -> string * id * Yojson.Safe.json list
```

Unprocessed code:
```ocaml
type Structured_event.t += My_structured_event of {a: int; b: bool; c: Another.Type.t} [@@deriving structured_event]
```

gets transformed into the pre-processed code:
```ocaml
type Structured_event.t += My_structured_event of {a: int; b: bool}

let my_structured_event_id : Structured_event.id =
  let id_string =
    (* Generate a unique static ID ID from module path, constructor name, etc. *)
  in
  Structured_event.id_of_string id_string

let my_structured_event_repr : Structured_event.repr =
  { log= (function
      | My_structured_event {a; b; c} ->
          ( "My_structured_event {a=$a; b=$b; c= $c}" (* This is replaced by the [msg] parameter when present *)
          , my_structured_event_id
          , [ ("a", int_to_yojson a)
            ; ("b", bool_to_yojson b)
            ; ("c", Another.Type.to_yojson c) ] ) )
  ; parse= (fun id args ->
        if Structured_event.id_equal id my_structured_event_id then (
          match args with
          | [a; b; c] -> (
              let res =
                let open Result.Let_syntax in
                let%bind a = int_of_yojson a in
                let%bind b = bool_of_yojson b in
                let%bind c = Another.Type.of_yojson c in
                return (
                  My_structured_event
                    { a= int_of_yojson a
                    ; b= bool_of_yojson b
                    ; c= Another.Type.of_yojson c } )
              in
              match res with
              | Ok res -> Some res
              | Error _ ->
                  (* If this message is in a functor, there may be messages with the same ID but different
                     argument types, so we don't error in case a parser for those is later in the stack.
                  *)
                  None )
          | _ ->
            (* The ID should uniquely identify one type. *)
            assert false )
        else
          None ) }

let () = Structured_event.register_constructor my_structured_event_repr
```
