### ISSUE TITLE
Integration Testing: Implement the interface to the orchestrator (kube) and get deploys working

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4767]
It seems as though the best way to get this to happen in the short term is to shell out to `helm`.

We can `helm install` and `helm uninstall` when we want to create or destroy nodes. 

Epic: #4735

**Comment by 0x0I** [comment]
May be able to use `terraform [plan|apply]` and `terraform destroy` for integration testing (as is done in **testnets** -- depending on [#8164](https://github.com/kubernetes/minikube/pull/8164) and some testing on our end)

tl;dr: enable `minikube` launch within *Docker-in-Docker* setup on Buildkite cluster (currently cluster only supports CI/CD pipelines running `docker ...` family of commands.
