### ISSUE TITLE
SHA256 mismatch when installing coda on Mac with Homebrew

### ISSUE THREAD

**Issue by playHing** [CodaProtocol/coda#4778]
SHA256 mismatch when installing coda on Mac10.15.3 with Homebrew

<img width="561" alt="WechatIMG120" src="https://user-images.githubusercontent.com/26762575/80271836-c72e5280-86f6-11ea-83e4-d216e43adc82.png">

**To Reproduce**
1. `brew upgrade && brew update`
2. `brew install codaprotocol/coda/coda`
3. Observe "ChecksumMismatchError: SHA256 mismatch"

**Output of `brew --version`**: Homebrew 2.2.13

**Comment by bkase** [comment]
thank you! Oversight when we upgraded it

**Comment by bkase** [comment]
@playHing can you try now?

**Comment by bkase** [comment]
Please re-open if you're still seeing the issue -- I believe it's fixed
