### ISSUE TITLE
BuildKite CI: Deployed buildkite agents can download and upload artifacts to gcloud

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4804]
See https://buildkite.com/docs/agent/v3/gcloud#uploading-artifacts-to-google-cloud-storage

The JSON credentials approach is nice because we would also be able to support artifact upload/download on local developers' machines trivially.

Depends on #4802

**Comment by 0x0I** [comment]
Initial thinking around implementation:

**Steps:**
1. create GCP service account for Buildkite Agent Kubernetes cluster during provisioning
2. store service account as Kubernetes secret
3. provision Buildkite agent pods with volume-sidecar containing **environment hook** which exposes `$BUILDKITE_GS_APPLICATION_CREDENTIALS_JSON=<value-of-stored-secret>` EnvVar
4. Buildkite agents should be able to run ANY job which requires access to Google Cloud Storage by setting `$BUILDKITE_ARTIFACT_UPLOAD_DESTINATION="gs://<ci_cd_bucket>/$BUILDKITE_JOB_ID"

----

* 1. Create Buildkite service account credentials

```bash
resource "google_service_account" "buildkite_gcs_account" {
  account_id   = "buildkite-${var.cluster_name}"
  display_name = "Buildkite agent GCS service account -- cluster: ${var.cluster_name}"
  project = "o1labs-192920"
}
```
* 2. Store service account credentials as Kubernetes secret
```bash
resource "google_service_account_key" "buildkite_gcs_key" {
  service_account_id = google_service_account.buildkite_gcs_account.name
}

resource "kubernetes_secret" "google-application-credentials" {
  metadata {
    name = "google-application-credentials"
  }
  data = {
    "credentials.json" = base64decode(google_service_account_key.mykey.private_key)
  }
}
```

* 3. Store Buildkite service account credentials as pod secret volume
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: buildkite-agent
spec:
  containers:
  - name: buildkite-agent
    image: buildkite/agent
    env: 
    - name: BUILDKITE_HOOKS_PATH
      value: {{ $.Values.buildkite_hooks_path }} 
    volumeMounts:
    - name: credentials-json
      mountPath: "/etc/credentials.json"
      readOnly: true
  volumes:
  - name: credentials-json
    secret:
      secretName: google-application-credentials
```

* 4. Either provide Buildkite agent pod with **/hooks/environment** file mount or build *script* into Buildkite agent Docker image:
```bash
$ cat /hooks/environment

#!/bin/bash
set -euo pipefail

if [[ "$BUILDKITE_STEP_KEY" ~= ^upload|download ]]; then
  export BUILDKITE_GS_APPLICATION_CREDENTIALS_JSON="$(cat /etc/credentials.json)"
fi
```

**Comment by 0x0I** [comment]
[reference] **buildkite agent hooks**: https://buildkite.com/docs/agent/v3/hooks#available-hooks

```
environment | Agent, Plugin | Runs before all other hooks. Useful for exposing secret keys and adding strict checks.
-- | -- | --
```

**Comment by 0x0I** [comment]
[reference]: **Buildkite Helm chart**:
```
# configure the Buildkite provider - note: operator should have API token env var exposed
provider "buildkite" {
    #  api_token = "token" -- SHOULD be set from env: **BUILDKITE_API_TOKEN**
    organization = "O(1) Labs"
}

# create an agent token with an optional description
resource "buildkite_agent_token" "agent_token" {
    description = "default Buildkite agent token"
}

buildkite_agent_vars = {
    numAgents             =   var.num_agents
    labelOffset              =   var.agent_offset
    image = {
      repository              =   var.image_repository
      tag                         =   var.image_tag
      pullPolicy               =   var.image_pullPolicy
    }
    agentToken              =   agent_token.token
    agentMeta                =   var.agent_meta
    agentHooksPath      =   var.agent_hooks_path
    volumeMounts = [
      {
          name = "credentials-json"
          value  = "/etc/credentials.json"
      }
   ]
   volumes = [
      {
          name = "credentials-json"
          secret = {
              secretName = "google-application-credentials"
          }
      }
   ]
}

 resource "helm_release" "buildkite_agent" {
  name      = "${var.cluster_name}-buildkite-agents"
  chart     = "bk-agent"
  namespace = kubernetes_namespace.buildkite_namespace.metadata[0].name
  values = [
    yamlencode(local.buildkite_agent_vars)
  ]
  wait       = false
}
```

**Comment by 0x0I** [comment]
**Note:** We may need to either mount an additional volume for the `environment` script defined above or build the script into the image.

**Comment by bkase** [comment]
@0x0I what is the benefit of using the official buildkite agent docker image vs. just including the buildkite-agent package in whatever environment we have.

I forsee this being somewhat difficult to compose with [our existing toolchain image](https://github.com/CodaProtocol/coda/blob/c645266e69af7b0dc59687bfdeae7a203bcdd3f6/dockerfiles/Dockerfile-toolchain) -- it would be much easier to `apt install buildkite-agent` in this image in the short term, unless that trick you mentioned about merging from multiple dependent docker images could work here too.

**Comment by bkase** [comment]
@0x0I also this approach seems good to me terraform -> helm -> etc (may be worth quickly chatting with @yourbuddyconner and @nholland94 to see how it could or should fit in with the other dhall stuff) -- in the short (today), term do you know of a quick way I can get a local agent to talk to gcloud so it can unblock some pipelines I want to write?

**Comment by 0x0I** [comment]
> @0x0I what is the benefit of using the official buildkite agent docker image vs. just including the buildkite-agent package in whatever environment we have.

@bkase : so we'll likely use the official Buildkite Helm chart for deploying the Buildkite agents across the Kubernetes cluster though that's still in discussion (#4803) due to how it fits in with our current infrastructure stack and since the Helm chart seems solidly built. Based on if we do, seems to make sense to leverage an image with proper packaging, etc. (either our own, the official image, a hybrid of both, etc) rather than creating a base image and adding/maintaining the instattion of necessary packages ourselves.

>  in the short (today), term do you know of a quick way I can get a local agent to talk to gcloud so it can unblock some pipelines I want to write?

You should be able to properly set the environment variables mentioned earlier (e.g. $BUILDKITE_GS_APPLICATION_CREDENTIALS_JSON) to what you use locally and make use of the `gcloud` cli. As far as I can tell though, I don't think we currently a GCS account.... @yourbuddyconner ¯\_(ツ)_/¯

**Comment by 0x0I** [comment]
@bkase, @yourbuddyconner:
- all of the existing Buildkite [agents](https://buildkite.com/organizations/o-1-labs-2/agents) should be able to handle jobs which attempt to upload/download from our GCS repo.
- I'm working on creating the Terraform bits in `coda-automation` but you can unblock/experiment yourself using my minikube prototype cluster (existing k8s cluster  ^^^) or one of your own:

```bash
# MacOS installation
brew install minikube helm
minikube start   # should automatically choose *docker* virtualization but if not, run: minikube start --driver=docker
helm install <cluster/release-name> buildkite/agent --set privateSshKey="$(cat </path/to/your/github/private-key>)" -f <helm-buildkite-values.yaml> 
``` 

**Note:** most of the configuration defaults should be fine except:
- `agent.token` (or set **$BUILDKITE_AGENT_TOKEN**) to your token
- for upload/download capabilities, you'll want to add the following to your <helm-buildkite-values.yaml>:

```yaml
extraEnv:
  - name: BUILDKITE_GS_APPLICATION_CREDENTIALS_JSON
    value: '<contents-of-gs-app-creds.json>'
```

**Comment by 0x0I** [comment]
@bkase @yourbuddyconner Thinking we shouldn't have to worry about developing and maintaining our own Docker image for the buildkite-agents, at least for the purpose of setting buildkite-agent *hooks* since:
- sensitive environment configuration can be injected at build time and maintained and secured within individual pod runtimes without *environment hooks* (via `Terraform`)
- sensitive environment configs can be modified infra-wide or targeting specific pods without *hooks* post provisioning (via `kubectl`)
- individual cluster builders/operators can choose to provision new clusters with *hooks* mounted or included within pre-initialized images if desired

**Comment by yourbuddyconner** [comment]
@0x0I good call-out, I concur that we probably won't need to extend beyond the built-in functionality of the buildkite agent in the initial implementation.

**Comment by 0x0I** [comment]
Resolved by: https://github.com/CodaProtocol/coda-automation/pull/377
