### ISSUE TITLE
Add receiver field to metadata for "Received a block $block from $sender" logs

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#4816]
Currently there's no way to build a graph exclusively using these logs. I propose we add a `receiver` field to this log that represents the node that produced the log entry. I could then easily build a directed graph with the available data. 

```
jsonPayload: {
  level: "Debug"   
  message: "Received a block $block from $sender"   
  metadata: {
   external_transition: {…}    
   pid: 10    
   sender: {
    Remote: {
     host: "35.227.62.45"      
     peer_id: "12D3KooW9q63yQvWT6XJP71Z8VQuZMbG2gr2NopbKeHKqL7PfBQ8"      
    }
   }
   state_hash: "2qxVdy2PHSTg4UEdeUD1jKjTU5p6tJFveMVZc5LYdPs8nvYy36jbAWrySrrJfxJztVd1EcZcGLbQR4ikki4xbnzb3JFd6o2nD3LzvE5PiYgLW7fEFnECdgRrZ4pKiZDuJxJU1K5ZdaMZw"    
  }
```

**Comment by nholland94** [comment]
I thought that @emberian had added a trick recently that put the current node's peer id in the global metadata for the logger so that it would be appear in all log messages. Did that code get lost somewhere, or am I mistaken?

**Comment by yourbuddyconner** [comment]
Another thing to consider is that when a node restarts its peer id can change, so we might need more data than just peer id (IP and port at the very least).
