### ISSUE TITLE
Daemon crash while testing hd wallet integration

### ISSUE THREAD

**Issue by Schmavery** [CodaProtocol/coda#4818]
Got a ledger and been testing out the hd wallet functionality a little.

- Managed to get the coda app installed on the ledger from my Mac, which is cool, will update the docs to reflect that eventually
- Got to the "Generate Public Key #1" screen on the ledger, I confirmed, and then it hung there for quite a while and eventually the daemon crashed with this error:
```
Assertion failed: (limbs_written <= n), function bigint, file /Users/avery/git/coda/_build/default/src/lib/snarky/src/camlsnark_c/libsnark-caml/depends/libff/libff/algebra/fields/bigint.tcc, line 38.
```

Most of this functionality isn't exposed in develop right now, but wanted to write it up so we don't forget, or in case anyone sees anything familiar in the error.

**Comment by rbkhmrcr** [comment]
this is fixed by building coda with `--profile=medium_curves`, the error is saying that there's a mismatch between the size of the expected and actual public key received

**Comment by Schmavery** [comment]
Thanks, it worked! 

```
coda accounts create-hd -HD-index 1

😄 created HD account with HD-index 1!
Public key: 4vsRCVFikVTkwK2rtvcbFyQ46szc4u8PCimq6XCejdLLvsVauu6YUQS3zboDTBP8fqLt9zDQVz2tA6Fhgh8ta1xMLQLJYAGcFT4wnPo7FZLYd4MmnP6U3BHDR1usJpnLJQySrYGovu2JbGeM
```
