### ISSUE TITLE
Setup Coda Protocol community discord development activity feed 

### ISSUE THREAD

**Issue by 0x0I** [CodaProtocol/coda#4904]
**Overview:**

A member of the Coda community reached out to Christine (*@o1christine*) regarding helping those interested in following Coda's development activity to do so via a familiar medium like Discord.

This issue is meant to serve as a launchpad to an investigation and discussion around how such an activity feed could be developed optimizing on both the accessibility and utility of these notifications by members of the community.

_Example screenshot:_ https://cdn.discordapp.com/attachments/613480455529824286/707681372935815189/unknown.png

**Goals:**
* [x] identify development activities of interest to community  (e.g. pull requests, feature branch merges/creations, etc)
* [x] setup Coda development activity notification pipeline between Discord and Github (based on above)
* [ ] broadcast `development activity notification` channel to community members once *LIVE*

**Comment by 0x0I** [comment]
initial (test) **Discord <=> Github** integration has been setup:

- *Coda github activity* - https://discord.com/api/webhooks/710903666948833373/0v0lC5sHreVEmC7-XGeN6UJ0FoXGWNzWBlVM_sUcNROBTRi5Ge7GakIQ3YQGBTEWRYQ0
- *Discord #github-updates-test* - https://discord.com/channels/484437221055922177/710862216215396434
- configured to expose potentially relevant/interesting activity (subsequent discussion will follow **re:** activity to include -- e.g. involving community poll, team survery )

**Comment by 0x0I** [comment]
**Working Activity Feed List:**
- pull requests
- feature branch merges => *develop*
- Releases

**Comment by yourbuddyconner** [comment]
Criteria looks good

**Comment by aneesharaines** [comment]
Suggestion:  have two separate channels, one of issues (which is how we manage our sprints and tasks) and one for everything else (which focuses on the code changes being made)

**Comment by 0x0I** [comment]
> Suggestion: have two separate channels, one of issues (which is how we manage our sprints and tasks) and one for everything else (which focuses on the code changes being made)

**FYI (..and feel free to tweak):**
-  [github-updates](https://discord.com/channels/484437221055922177/712409916316582019) (code activity feed)
- [github-issues-updates](https://discord.com/channels/484437221055922177/712409693510696961) (issue/process activity feed)

**Comment by 0x0I** [comment]
**[Working] Community Poll Questions:**

*How would you best describe your interest and participation in the Coda protocol community? (select all that apply)*
* [ ] protocol enthusiast and follower
* [ ] testnet participant
* [ ] community content and relations maintainer
* [ ] code contributor

*Of the following, which Coda protocol development notifications would you be most interested in receiving? (select one)*
* [ ] Coda node releases (Docker images & Debian packages)
* [ ] New features in active development
* [ ] Pull requests *(for bug fixes and both source-code & documentation changes)*
* [ ] Issues created and bugs reported

**Comment by 0x0I** [comment]
hey @aneesharaines @yourbuddyconner @o1christine:

Added a few questions above -- feel free to provide thoughts, feedback, suggested questions, whatever feels relevant **re:** above community poll por favor.

**Comment by 0x0I** [comment]
Activity feeds has been active for awhile now. Community poll to be investigated/developed at a later time.
