### ISSUE TITLE
Specify plan for integration testing framework infrastructure interaction

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#4917]
The new integration testing framework requires the ability to configure and deploy test networks in the cloud. Specifically, the following requirements must be met:

- framework is able to create/teardown a network (logical mapping to a kubernetes namespace)
- framework is able to generate necessary artifacts from a network configuration (genesis ledger, genesis runtime constants, etc...)
- framework is able to start nodes on the network
- framework is able to restart in-place nodes on the network
- framework is able to stop nodes on the network (completely remove them)
- framework is able to communicate with nodes on the network over GraphQL (may require the ability to lookup or expose ports externally)

We have discussed some options for implementing this, which I will lay out below:

a) implement this entirely in OCaml by generating Kubernetes YAML configs and using the Kubernetes API (there already exists bindings for this)
b) utilize the `coda-automation` deployment process to configure and deploy networks (this cannot suffice all requirements by itself and would require building out agents to sit in front of daemon processes to enable workflows related to dynamically stopping nodes)
c) utilize the `coda-automation` helm (or dhall) templates to render Kubernetes YAML, but manage the deployment of them in OCaml by communicating to Kubernetes API instead of interacting with terraform/helm

I believe last we spoke as a team (correct me if I'm wrong @bkase or @mrmr1993), we left off leaning towards option c. Option a seems to be too divergent from actual deploys, and option b would also introduce a different kind of divergence in the form of a different process architecture for the containers we run. Option c still sacrifices some divergence in terms of the deployment aspect, but will utilize the same configuration layer as real deployments, and can run the same exact container image we will deploy on real networks. Open question related to this are how we would actually integrate these two together and how much work it would actually be to have OCaml upload the generated YAML configs to Kubernetes.

**Comment by figitaki** [comment]
There might be an opportunity to combine the work we're doing on the Testnet SDK with some of this work. We already plan to integrate with the Kubernetes API in order to upload the keypairs and genesis ledger which will all be OCaml/Reason code in the `coda-automation` repository. https://github.com/CodaProtocol/coda-automation/pull/375
