### ISSUE TITLE
[CRASH]Failed to connect to libp2p_helper process: RPC #2 failed:

### ISSUE THREAD

**Issue by yourbuddyconner** [CodaProtocol/coda#4933]
There have been 46 occurences of this log today in the `bugspray` network: 

```
(monitor.ml.Error
(Failure
"Failed to connect to libp2p_helper process: RPC #2 failed: \"initializing helper error: failed to read value pointer from vlog file: {Fid:74 Len:931 Offset:65168559}: Unable to find log file. Please retry\"")
("Raised at file \"stdlib.ml\", line 33, characters 17-33"
"Called from file \"src/deferred1.ml\", line 17, characters 40-45"
"Called from file \"src/job_queue.ml\" (inlined), line 131, characters 2-5"
"Called from file \"src/job_queue.ml\", line 171, characters 6-47"
"Caught by monitor coda"))
```

Probably related to these old issues: 
#3986, #4254, #4326

**Comment by emberian** [comment]
This error is coming from [badger](https://github.com/dgraph-io/badger), which was also the source of issues on #4254/#4326 but for different reasons. I'm not sure why this would suddenly start happening, though, unless a daemon was restarted in the same pod without the state getting wiped, which I think is not possible in the current infra config? This is concerning. There's a badger upgrade sitting in the pipeline for the next time we can do a libp2p upgrade, which might fix this.

**Comment by yourbuddyconner** [comment]
Haven't seen this bug in a while, closing.
