### ISSUE TITLE
Leaderboard: deploy to "cron"

### ISSUE THREAD

**Issue by aneesharaines** [CodaProtocol/coda#4953]
Not a blocker, can deployed locally if needed.

**Comment by bkase** [comment]
Steps needed:
1. In circle.yml.jinja, make a pipeline that runs the leaderboard js script
1. Add an extra cron line to the bottom of the circle.yml.jinja -- https://crontab-generator.org/ (every day at 1am?)
1. Make sure to add the environment variable for the creds (Martin has access)
