### ISSUE TITLE
Leaderboard: copy over old challenges to new sheet and update spreadsheet links on testnet page

### ISSUE THREAD

**Issue by aneesharaines** [CodaProtocol/coda#4961]

**Comment by MartinMinkov** [comment]
**Update:**

On my end, I have copied over the challenges needed into a new sheet. Currently in discussion with Sherry and Christine on how to move forward with this issue.

**Comment by MartinMinkov** [comment]
After discussing Monday's Product Team Prio, I am unblocked from the discussion above. Avery and Brandon pointed me to the places that can be changed immediately.

**Comment by MartinMinkov** [comment]
The changes for this have been applied to the following PR so I'm closing the issue.

https://github.com/CodaProtocol/coda/pull/4930
