### ISSUE TITLE
Buildkite CI: Cull unnecessary jobs

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4990]
I think we have CI jobs or portions of jobs that we don't need to move over to Buildkite, but can actually just remove entirely.

This issue attempts to justify removing some of them. Please comment if you disagree with removing any of the pipelines here, or think we should remove others.

1. Tracetool -- I think this has been replaced by another tool at this point, but I'm not sure, cc @emberian 
2. The nightly *medium_curves jobs: specifically, test-unit-medium-curves -- I don't think we've been keeping up-to-date checking up on these jobs. For the former, I recall us frequently noticing it breaking but it being unrelated to us actually introducing issues. For the latter, this will be replaced by the network validation system (and new integration tests right?)
3. All existing integration test pipelines (we're replacing with the new integration testing system)
4. The steps within jobs that redundantly upload artifacts to both AWS and Google Cloud -- let's just upload in Google Cloud through the buildkite tool. Existing places that only upload to S3 (including the snark keys/genesis ledger caching logic) can remain.

**Comment by bkase** [comment]
5. Update-branch-protection -- This job looks at test.py and decides which tests are required and then subsequently updates GitHub's required tests. We no longer need this because in the new world, all tests are required. If a test is failing but we want to keep it in our suite, it should be in the quarantine suite which "fails" with a green success instead.

**Comment by emberian** [comment]
tracetool is still necessary.

**Comment by 0x0I** [comment]
@emberian @bkase worth creating a *dhall* job for building and uploading [tracetool](https://github.com/CodaProtocol/coda/blob/develop/.circleci/config.yml#L18) as a GCS artifact?
