### ISSUE TITLE
Buildkite CI: Build a mechanism for quarantining broken tests. Support flakes by retrying relevant jobs.

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4991]
We want to support our new flaky job process, see #4768

Epic: #4762

A small RFC (scoped to no more than half a day) should precede implementation of this.

**Comment by bkase** [comment]
# Small RFC

## Background

Flaky and broken jobs need a space in our CI system as we wish to use this porting opportunity to improve our CI experience. See #4768 for more on the flaky/broken job processes.

## Goals

Support the flaky and broken job process, and do so quickly and efficiently (from an eng perspective).

## Details

### True Flaky Jobs

Add a new field to `Command/Base.dhall`'s config `flaky: Bool`. It defaults to false. When a job is flaky, we set the underlying `retry` field to 3, thus making the test actually fail only after all 3 retries fail (as described in #4768 ).

### Quarantine Suite

The simplest approach here would not technically be a separate "suite", but would still get the job done and be quite a small change to the existing configuration (comments requested if folks think this approach is deemed not sufficient):

Assume `let IssueNumber = Natural`.

Add a `broken: Optional IssueNumber` field (which requires a GitHub issue payload) to a Job's associated `Spec.dhall` -- the place where we specify the regular expression that tells us if we should run this pipeline and the name of the Job.
When `broken = Some IssueNumber`, set the `soft_fail` attribute of all the underlying buildkite commands to always be green https://buildkite.com/docs/pipelines/command-step and append to the name of each step in this pipeline the broken-heart emoji, 💔

We can follow-up with automation that alerts us if too many broken jobs are present.

Though this isn't a suite, it still captures which jobs are broken in a clear concise manner, and forcing an `IssueNumber` to be passed whenever we want to mark a test as broken will make it easy for folks to remember to do so (and easy for code-reviews to catch any mistakes here).

**Comment by mrmr1993** [comment]
On CircleCI, we can use a cache of `_build` per CI job per commit to avoid rebuilding on re-runs of flakes. The changes would be minimal: load cache before attempting to build, store it after.

It's not clear to me whether/how this affects our pricing, however.

**Comment by 0x0I** [comment]
Also seems like we could make use of Buildkite's `soft_fail` and/or `skip` command step properties (https://buildkite.com/docs/pipelines/command-step#command-step-attributes).

I kind of like the idea of [soft_fail](https://buildkite.com/docs/pipelines/command-step#soft-fail-attributes) more due to how the failures are surfaced and made visible to the pipeline summary though can see how both could be used in the context of "flakes" and others - e.g. phasing in/out jobs.

**Comment by 0x0I** [comment]
^^^ handles signaling the *"flakey/cautionary"* state of jobs/tests from a UI (displayed in Github check summary) and programmatic (capable of querying Buildkite's GraphQL API for *X* pipeline-jobs with `soft_fail`s) perspective.

**Comment by 0x0I** [comment]
`skip` would probably be more generally suited if it allowed exit status scoping (as in, `skip` failing build if failed w/ X exit_status). As of now, its value could serve as a way to communicate a Github IssueNumber (+ other details) for tracking the flake/skip. Also, each skip can be visualized in Github's check summary UI though I don't believe they are exposed via GraphQL.
```
- label: "Skipped job"
    command: "broken.sh"
    skip: "#1234: Random CI dependency download failure "
```
