### ISSUE TITLE
Buildkite CI: Remote agents can pull secret env vars

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#4993]
Some of our jobs rely on secret API keys and other sensitive information. Somehow this information needs to be distributed to builders. See https://buildkite.com/docs/pipelines/secrets for docs.

As a bonus, it would be nice if this worked for local agents from core team members as well.

Please edit me with rough implementation details.

**Comment by 0x0I** [comment]
- **[Potential Solution]** *GKE* managed secrets management
  - _requirements:_ kubectl install [agents], kubectl context setting (read from `.kube/config` *only* it seems)
  - **pros:**
       - makes use of existing GKE secrets management infrastructure
       - primary installation method of `kubectl` is currently supported by buildkite-agents
       - `.kube/config` could be rendered as volume-configmap for all agent pods during construction or post-`apply`
       - solution **works for local agent** settings with proper local configuration
   - **cons:**
       - added dependency due to installation of `kubectl` tool (likely requires agent hook or custom Container image)
       - config can not be read as user specific runtime *environment variable*
       - lack of community supported integration with Buildkite as a managed secrets provider

**Comment by 0x0I** [comment]
- **[Potential Solution]** *S3* managed secret Buildkite Summon plugin integration
  - **requirements:**
     - install aws cli [agents]
     - AWS access config setting (ENVVars supported -- see: [docs](https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html))
  - **use:**
     - [secrets.yaml](https://github.com/cyberark/summon#secretsyml-flags) is defined in *src* for pipeline/step
     - install [Summon](https://github.com/cyberark/summon) [agents]
  - **pros:**
       - Buildkite plugin [integration](https://github.com/angaza/summon-buildkite-plugin#prerequisites) 
       - allows per pipeline `secrets.yaml` configuration in repo src (secrets are expressed as paths within S3 buckets within YAML file)
       - AWS S3 access can be configured/updated during cluster construction or post-apply
       - secrets from YAML file exposed within environment for entirety of step
       - solution **works for local agent** settings with proper AWS access configuration and installation of plugin
   - **cons:**
         - added dependencies due to installation of `aws-cli` and `summon` tools (likely requires agent hook or custom Container image)

**Comment by 0x0I** [comment]
- **[Potential Solution]** Scripts rely on Buildkite [environment hooks](https://buildkite.com/docs/pipelines/secrets#storing-secrets-in-environment-hooks)
  - **requirements:**
     - agent cluster provisioned with *environment hook scripts* which expose pipeline secrets (likely via additional *helm* [chart volumes](https://github.com/buildkite/charts/tree/master/stable/agent)) or within source
     - pipeline step keys (or the like) and environment hooks must be coordinated
  - **usage:**
     1. pipeline step executes command or script which references secret ENVVar (exposed via agent environment hook)
  - **pros:**
       - does not require secret management system / no added cost (though could support ANY)
       - no additional tool/package management
       - infrastructure code AND source repos serve as source of truth for secrets exposed within cluster
       - solution **works for local agent** settings with proper agent HOOKs path configuration
   - **cons:**
         - secrets are not (necessarily) maintained in managed secrets service
         - configuration drift is not prevented
         - all pipeline secrets changes require infra or source updates

**Comment by 0x0I** [comment]
**Takeaways:**
- **S3 managed secret Buildkite Summon plugin** is currently *PREFERRED*
    - Buildkite plugin provides integration with several secret managers using consistent *secrets.yaml* technique
    - secrets managed 100% at the application pipeline level
       - no infra changes necessary when adding secrets (other than actual secret creation step)  
   - does NOT require custom *agent* or *pipeline* HOOKs for exposing secrets
   - does require mechanism for installing both *aws-cli* & *summon* tools on agents
   - provides smoothest job secret injection user-experience (in my opinion)

**Comment by yourbuddyconner** [comment]
My preference in general is to use AWS Secrets manager for secrets, mostly because it has lifecycle tooling around secrets (which a tool like S3 lacks). It seems like the summon plugin will work great to this end and we can also use something like [this](https://github.com/godaddy/kubernetes-external-secrets) to enable access to Secrets Manager from the k8s side of things.
