### ISSUE TITLE
Buildkite CI: Figure out a better way to build regular expressions

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#5001]
See https://github.com/CodaProtocol/coda/pull/4914 for an example and more discussion.

**Comment by nholland94** [comment]
One way to solve this could be to have a structured, typed regular expression implementation in dhall. For instance, we could turn

```dhall
"^buildkite/(.*\\.dhall\\\$|Makefile\\\$|scripts/generate-jobs\\.sh\\\$)"
```

into

```dhall
let R = ../Lib/Regexp.dhall in
R.format
  { restrict = R.Beginning -- allows us to configure "^" and "$" at beginning/end of regexp
  , body =
      [ R.Lit "buildkite/"
      , R.Capture
          [ [ R.Star [R.AnyChar]
            , R.Lit ".dhall" ]
		  , [ R.Lit "Makefile" ]
          , [ R.Lit "scripts/generate-jobs.sh" ] ] ] }
```

The formatted regex will be mildly different (though logically equivalent to) the top version. It may end up just being overkill, but I feel like the ability to not have to munge with and reason about multiple levels of escaping makes this a desirable option.

**Comment by bkase** [comment]
Yup -- I like the idea of it; I was considering something similar myself yesterday.

We could make the structure more restricted to file-selection rather than something as powerful as full regular expressions to further simplify usage. Here's an example of what I mean:

```dhall
let S = ../Lib/SelectFiles.dhall in
S.format
   [ S.path [ S.Lit "buildkite/foo/bar/", S.AnyDir, S.AnyFileOfExtension "dhall" ],
     S.path [ S.Lit "Makefile" ]
   ] 
```

The constructors could be named nicer, but hopefully, the idea makes sense.

**Comment by bkase** [comment]
Here's another iteration on the above:

```dhall
let S = ../Lib/SelectFiles.dhall in
S.format
   [ S.AllWhere { dir = Some "buildkite/foo/bar/", ext = Some "py" }
   , S.Path [ S.Lit "buildkite/foo/", S.Glob, S.AllWhere { dir = Some "bar/", ext = Some "dhall" } ]
   , S.Lit "Makefile"
   , S.Lit "scripts/foo.py"
   ]
```

I'm going to go forward with the above if I get a 👍

**Comment by nholland94** [comment]
I like the level of abstraction of this pattern, though now that I'm thinking of it at this layer, seems like we may want to ditch some of the nesting and instead stick to a pattern of two types: `FilePattern` and `PathPattern`. A `FilePattern` is essentially what your `S.AllWhere` is in your examples, except that the input to `S.format` would just be a `List FilePattern` as opposed to an expression language like the prior examples.

```dhall
let FilePattern = { dir: Optional PathPattern, exts: Optional (List Text) }
let PathPattern = < Lit : Text | Any | AnyNested > -- Any == *, AnyNested == **
let exactly = \(dir : Text) -> \(exts : List Text) -> {dir = Some [dir], exts = Optional/ofList exts}
let format : List FilePattern -> Text = ...
```

You could then rewrite your example like so:

```dhall
S.format
   [ { dir = Some [S.Lit "buildkite/foo/bar", S.Any], exts = Some ["py"] }
   , { dir = Some [S.Lit "buildkite/foo", S.Any, S.Lit "bar", S.Any], exts = Some ["dhall"] }
   , S.exactly "Makefile" []
   , S.exactly "scripts/foo" [".py"]
   ]
```

Overall though, I like this approach a lot. Feel free to take or leave the ideas from the above example.
