### ISSUE TITLE
Node startup failure report

### ISSUE THREAD

**Issue by sundafa** [CodaProtocol/coda#5051]
Linux version: ubuntu 18.04
Last info:
```
2020-06-09 23:23:57 UTC [Info] Coda daemon is now doing ledger catchup
2020-06-09 23:25:59 UTC [Fatal] after lock transition, the best tip consensus state is out of sync with the local state -- bug in either required_local_state_sync or frontier_root_transition.
2020-06-09 23:25:59 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error\n  (Failure \"local state desynced after applying diffs to full frontier\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/lib/debug_assert/debug_assert.ml\\\" (inlined), line 1, characters 25-33\"\n    \"Called from file \\\"src/lib/transition_frontier/full_frontier/full_frontier.ml\\\", line 606, characters 4-1023\"\n    \"Called from file \\\"src/lib/transition_frontier/transition_frontier.ml\\\", line 292, characters 4-93\"\n    \"Called from file \\\"src/lib/transition_handler/processor.ml\\\", line 57, characters 10-68\"\n  \"Called from file \\\"src/lib/rose_tree/rose_tree.ml\\\", line 79, characters 18-24\"\n    \"Called from file \\\"src/deferred_or_error.ml\\\", line 101, characters 23-33\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"
2020-06-09 23:25:59 UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
```
[coda_crash_report_2020-06-09_23-26-00.443388.tar.gz](https://github.com/CodaProtocol/coda/files/4755376/coda_crash_report_2020-06-09_23-26-00.443388.tar.gz)

**Comment by cryptovestor21** [comment]
I think I am having the same issue, also ubuntu 18.04

'2020-06-09 23:38:16 UTC [Info] Coda daemon is now doing ledger catchup
2020-06-09 23:39:09 UTC [Fatal] after lock transition, the best tip consensus state is out of sync with the local state -- bug in either required_local_state_sync or frontier_root_transition.
2020-06-09 23:39:09 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
        exn: "(monitor.ml.Error\n  (Failure \"local state desynced after applying diffs to full frontier\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/lib/debug_assert/debug_assert.ml\\\" (inlined), line 1, characters 25-33\"\n    \"Called from file \\\"src/lib/transition_frontier/full_frontier/full_frontier.ml\\\", line 606, characters 4-1023\"\n    \"Called from file \\\"src/lib/transition_frontier/transition_frontier.ml\\\", line 292, characters 4-93\"\n    \"Called from file \\\"src/lib/transition_handler/processor.ml\\\", line 57, characters 10-68\"\n    \"Called from file \\\"src/lib/rose_tree/rose_tree.ml\\\", line 79, characters 18-24\"\n    \"Called from file \\\"src/deferred_or_error.ml\\\", line 101, characters 23-33\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"
2020-06-09 23:39:10 UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"
2020-06-09 23:39:10 UTC [Error] Unconsumed item in cache: $cache
        cache: "cached item was not consumed (cache name = \"Transition_handler__Unprocessed_transition_cache\")"


  ☠  Coda Daemon crashed.
'

[coda_crash_report_2020-06-09_23-39-09.945744.tar.gz](https://github.com/CodaProtocol/coda/files/4755412/coda_crash_report_2020-06-09_23-39-09.945744.tar.gz)

**Comment by NAKsir-melody** [comment]
Linux version: ubuntu 18.04
Same here lol

**Comment by NAKsir-melody** [comment]
.coda_config1, .coda_config2
too big to upload directly.

refer below.
https://drive.google.com/file/d/13SeWGqihQT43Y_Qfdvj5tLiCV1qFGfoL/view?usp=sharing

**Comment by aneesharaines** [comment]
Thanks for reporting! 

Looks to be the same as #5051, which is being tracked.  Closing this one to consolidate!
