### ISSUE TITLE
Usability bug: daemon.json missing

### ISSUE THREAD

**Issue by koen84** [CodaProtocol/coda#5057]
From .coda-config/coda.log : 

`{"timestamp":"2020-06-10 00:26:53.207770Z","level":"Trace","source":{"module":"Coda","location":"File \"src/app/cli/src/coda.ml\", line 429, characters 65-72"},"message":"No daemon.json found at $configpath: $error","metadata":{"configpath":"/home/<username>/.coda-config/daemon.json","error":"(Unix.Unix_error\"No such file or directory\"open\"((filename /home/<username>/.coda-config/daemon.json) (mode (O_RDONLY O_CLOEXEC)) (perm 0o0))\")","pid":12753}}`

**Comment by bkase** [comment]
This is a usability error in logging, the functionality is :+1:

**Comment by psteckler** [comment]
The log entry is marked as `Trace`, so it's not logged as an error. 

I suppose the wording could indicate that some other config info will be used.

**Comment by psteckler** [comment]
@bkase This error message is not in `develop`. The code there is newer, and appear to log genuine errors.
