### ISSUE TITLE
Coda crash: "unconsumed item in cache: Transition_handler__Unprocessed_transition_cache"

### ISSUE THREAD

**Issue by billyharvey** [CodaProtocol/coda#5064]
Trying 3.2b - got a crash with attached report.
[coda_crash_report_2020-06-10_01-35-53.525361.tar.gz](https://github.com/CodaProtocol/coda/files/4755705/coda_crash_report_2020-06-10_01-35-53.525361.tar.gz)

**Comment by yourbuddyconner** [comment]
Thank you for reporting this, closing in favor of issue #5059
