### ISSUE TITLE
Infrastructure Testing: Replace Unstructured Logs with Structured Logs

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#5102]
Part of epic #4735. Now that structured logging is implemented and available, we need to go through and convert most of our logs from unstructured to structured. Doing as much as we can upfront will help reduce iteration when implementing the new integration test framework, since we will already have most of the structured log events available to the implementation of the framework ahead of time.

**Comment by mrmr1993** [comment]
We have a large (>300) number of logs for various error cases and debug dumps that we can probably avoid structuring at this point.

I think that it is most useful to structure at least the following:
```
Block produced: src/lib/block_producer/block_producer.ml:525
Bootstrap complete: src/lib/bootstrap_controller/bootstrap_controller.ml:402
Connecting: src/lib/coda_lib/coda_lib.ml:371
Listening: src/lib/coda_lib/coda_lib.ml:375
Bootstrapping: src/lib/coda_lib/coda_lib.ml:382
Ledger catchup: src/lib/coda_lib/coda_lib.ml:387
Synced: src/lib/coda_lib/coda_lib.ml:391
Rebroadcasting transition: src/lib/coda_lib/coda_lib.ml:1143
Block received: src/lib/coda_networking/coda_networking.ml:1017
Snark work received: src/lib/coda_networking/coda_networking.ml:1033
Transactions received: src/lib/coda_networking/coda_networking.ml:1045
Gossip: src/lib/coda_networking/coda_networking.ml:1114
Merge snark generated: src/lib/snark_worker/functor.ml:85
Base snark generated: src/lib/snark_worker/functor.ml:92
Snarked ledger synced: src/lib/syncable_ledger/syncable_ledger.ml:653
Peer banned: src/lib/trust_system/peer_tust.ml:149
```

Some things that I expected to find logs for but didn't
```
New maximum observed block length:
Not logged, metrics updated at src/lib/transition_router/initial_validator.ml:195
Most recent valid block:
Not logged, src/lib/transition_router/transition_router.ml:411
```

**Comment by nholland94** [comment]
@mrmr1993 

That looks like a solid list. It may also be worth adding an event for `Snark ledger transitioned` (perhaps with a better name that doesn't over transition any more than it already is). It would fire whenever we move the root and take and update the root snarked ledger. This is an event we commonly want to key into, both on testnets and integration tests.
