### ISSUE TITLE
GraphQL bestChain endpoint might return orphan blocks

### ISSUE THREAD

**Issue by sosedoff** [CodaProtocol/coda#5117]
The `bestChain` endpoint is supposed to return only blocks from canonical chain, however i noticed that it might return orphaned blocks. Not sure what causes it, but after a few more calls the graphql api includes the right block for the same height.

**Comment by aneesharaines** [comment]
Thanks for reporting this @sosedoff !

**Comment by sosedoff** [comment]
I think the reason why it might return orphan blocks is because it might not be clear if the last available block is canonical or not. Maybe internally the process should wait to see if the block is canonical and return it if it is. It would also help if `bestChain` offered a filter like `after` that exists on other endpoints.

**Comment by psteckler** [comment]
I think this is the correct behavior.
