### ISSUE TITLE
Buildkite CI (artifacts): Refactor such that there is a distinct step end when the build finishes

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#5142]
This way later jobs can depend on this part of the artifact build

**Comment by 0x0I** [comment]
May make sense to convert [Artifact.dhall](https://github.com/CodaProtocol/coda/blob/develop/buildkite/src/Jobs/Artifact.dhall#L17) into a helper Command (like with libp2p_helper and docker-artifact builds) to be imported and depended on by other jobs (e.g. integration test framework jobs).

**Comment by 0x0I** [comment]
Also as @lk86 pointed out during a discussion artifact builds can already be depended on using the key defined in the job (job end should signal proper readiness of the artifact to consume) and with the provision that `Artifact.dhall` always runs with any change (which it should now). Only downside here is that the artifact steps are needed (build et all) on every change though this could be avoided with short-circuiting logic.

**Comment by 0x0I** [comment]
**Dependency keys:**
- Debian package upload:  `_Artifacts-artifacts-build` (name: *Artifacts*, key: *artifacts-build*)
- Docker artifact build/push: `_DockerArtifact-docker-artifact` (name: *DockerArtifact*, key: *docker-artifact*)
