### ISSUE TITLE
Buildkite CI (artifacts): Build Docker -- build-artifacts-docker

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#5143]
Fifth part of #4806

**Comment by 0x0I** [comment]
[initial thoughts] **re:** [build-artifacts-docker--testnet_postake_medium_curves--coda-daemon](https://github.com/CodaProtocol/coda/blob/develop/.circleci/config.yml#L647) CircleCI job to *Buildkite pipeline* migration initial thoughts:

- create Dhall type for [Buildkite Docker Login plugin](https://github.com/buildkite-plugins/docker-login-buildkite-plugin) (similar to both current [Docker](https://github.com/CodaProtocol/coda/blob/develop/buildkite/src/Command/Docker/Type.dhall) and [Summon](https://github.com/CodaProtocol/coda/blob/develop/buildkite/src/Command/Summon/Type.dhall) plugin types)
  - enables consistent/standard means of providing DockerHub write capabilities within designated jobs (such as with the daemon image deploy job + others) *vs. relying on ad hoc script implementations*
  - default *$DOCKER_LOGIN_USERNAME* will  be set as Dhall plugin type default (override can be specified per job usage)
  - default *$DOCKER_LOGIN_PASSWORD* EnvVar will be provisioned with agent cluster (override can be specified per job usage)
- pipeline meant to be triggered by upstream build/pipeline
  - leverages Buildkite's **$BUILDKITE_TRIGGERED_FROM_BUILD_ID** environment variable to scope source of artifact from [triggering build](https://buildkite.com/docs/pipelines/artifacts#downloading-artifacts)
  - *triggering* build uploads `DOCKER_DEPLOY_ENV` containing active deployment environment specification
  - *triggered* `build-artifacts-docker-*` pipeline downloads `DOCKER_DEPLOY_ENV` (scoped based on previously mentioned EnvVar) and executes [release-docker.sh](https://github.com/CodaProtocol/coda/blob/develop/scripts/release-docker.sh) script

**Comment by 0x0I** [comment]
Docker Login *Dhall Type*:
```
{
    Type = {
        username: Text,
        `password-env`: Text,
        server: Text
    },
    default = {
        username = "coda",
        `password-env` = "DOCKER_LOGIN_PASSWORD",
        server = ""
    }
}
```

replaces something like:

`echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_USERNAME --password-stdin`
