### ISSUE TITLE
Make snark fee fixes in leaderboard automation.

### ISSUE THREAD

**Issue by MartinMinkov** [CodaProtocol/coda#5159]
Addressing the comments in the following PR:
https://github.com/CodaProtocol/coda/pull/5135

**Comment by Schmavery** [comment]
To clarify the comments in #5135, I checked with @bkase and it looks like we should probably do the logic in the leaderboard backend in terms of nanocoda and remove the rounding logic.

**Comment by aneesharaines** [comment]
We should come up with a more maintainable way of freezing points and disabling the cron job.  Also will need a more robust solution for the script.
