### ISSUE TITLE
Make sure genesis block is in archive node

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#5239]
We need this to implement rosetta spec

**Comment by bkase** [comment]
Alternatively, a special endpoint to grab just the genesis block

**Comment by ghost-not-in-the-shell** [comment]
In archive_client, we are transferring every new nodes to the archive node using the `New_breadcrumb` extension. According to the definition of this extension, when we first create the extension, the root of the frontier would be added as the first new breadcrumb. So I believe the genesis block would be automatically included if we start the archive node freshly when we start the network.
