### ISSUE TITLE
Archive node test log is not collected

### ISSUE THREAD

**Issue by ghost-not-in-the-shell** [CodaProtocol/coda#5250]
While port the archive node test. I found that the artifact is not collected and uploaded to CI. There's no logs for this integration test other than the ones in CI page. Also I am a little suspicious about whether it's actually running successfully.

**Comment by aneesharaines** [comment]
Fix this in buildKite, can pull this into Team C work.

**Comment by 0x0I** [comment]
Thinking should be resolved based on this [example BK run](https://buildkite.com/o-1-labs-2/coda/builds/1235#262ed30d-9e7e-4fc3-9b58-144f0b7aef0c) and https://github.com/CodaProtocol/coda/commit/55b84eb918078be7325278b70b23d607ef9c107b cc @ghost-not-in-the-shell

**Comment by 0x0I** [comment]
May have/want to prepend upload paths with something like `$BUILDKITE_JOB_ID` to avoid overwrites and access limitations from the BK UI.
