### ISSUE TITLE
Coinbase issue

### ISSUE THREAD

**Issue by imeckler** [CodaProtocol/coda#528]
In the proposal where we do not enforce delivery of coin bases to the appropriate person, but merely check that weren't more than the length, there is a potential attack which goes as follows:

1. Wait for the queue to fill with `n` coinbases
2. Win a block 
3. Fork at the last time the coinbase count was updated in the SNARK , throw away the old queue, fill it with `n` coin bases to you.

Then, in the next epoch (which is used for the genesis density calculation), you will have more money than you should and might be able to win on a fork. 

Let `c` be the coinbase amount and say the total money so far is `M`. How much percent of the stake would an adversary need to win a fork in this scenario?

**Comment by deepthiskumar** [comment]
Blockchain snark now includes coinbases(both amount and public key) which are yet to be included in a ledger proof (pending coinbases). So, this would not happen anymore
