### ISSUE TITLE
Buildkite CI: Thundering herd problem when Opam config updates

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#5324]
When our opam deps update, opam init misses the cache. We run this in parallel on across all nodes in a build so this leads to a (kind of) thundering herd issue where all jobs do the slow work because they all miss. See https://buildkite.com/o-1-labs-2/coda/builds/483#_ for example.

I imagine we can fix by doing a quick check just to see if the cache will miss and have subsequent jobs depend on that?

**Comment by 0x0I** [comment]
All for solutions to all kinds of thundering herds though still somewhat hard to imagine we've hit such a problem with the past load we've experienced and not seeing similar errors from more recent runs as far as I can tell.

**Comment by 0x0I** [comment]
Looking into creating a simple stress-test to evaluate how opam deps update under *"HIGH"* load.

**Comment by 0x0I** [comment]
Stress Test Results: [opam-init](https://buildkite.com/o-1-labs-2/coda/builds?branch=stress_opam_init)

**summary of stress scenarios:**
- :heavy_check_mark: `warmed (high cluster uptime) cache-hit` [^^ test-runs @ ~3pm PDT 08/19 -- *notice runtimes of ~6-7m*]
- :heavy_check_mark: `cold (low cluster uptime)" cache-hit` [^^ @ ~7pm PDT 08/19 -- *similar as above*]
- :warning: `cache-miss (simultaneous build and upload of `opam-*.tar.gz`)`  [^^ ~5:45am PDT 08/20 -- *notice runtimes of ~25-30m*]
- :heavy_check_mark: `cache-hit (following "warm-up")` [^^ ~6am PDT 08/20 -- *notice decreased runtimes*]

**Comment by 0x0I** [comment]
**Resolving** due to `no repro` for now

**note:** the considerable increase in *opam* init times when cache misses (unable to download artifact from previous GCS upload) occur. Based on how artifact names and signatures are [set](https://github.com/CodaProtocol/coda/blob/develop/buildkite/src/Command/OpamInit.dhall#L9) though, seems like this is a minor concern(?).
