### ISSUE TITLE
Complete from-source docker container for Rosetta

### ISSUE THREAD

**Issue by lk86** [CodaProtocol/coda#5332]
Rosetta expections/requirements here: https://www.rosetta-api.org/docs/node_deployment.html

Initial step is to concretely define a summary of the above requirements and outline what needs to change about the existing set of dockerfiles to build this single complete flow from github source to a docker container full of binaries + minimum configs.

**Comment by lk86** [comment]
Major Requirements derived directly from the rosetta spec:

- [x] Can build in Ubuntu
- [x] Ubuntu-based builder image
- [ ] "Build Anywhere" by pulling all dependencies from publicly released packages
> Instead, any required files must be downloaded from the internet with explicit versioning. If it is not possible to fetch a specific version, the hash of downloaded files must be compared with a constant defined in the Dockerfile.
- [ ] "Build from source" by pulling all source code from public git repositories
- [ ] All components required by rosetta in a single container

A checkmark indicates that the existing workflow already satisfies the given requirement.

Specific proposed changes:

- Suggest using debian-slim images where possible for smaller/simpler containers and therefore faster builds. Any vendor that requires ubuntu should be able to easily adapt the dockerfile to their needs.
- The dockerfile (at least for rosetta) should be a single 3-staged build.
- The first stage installs all required tools and build-time dependencies with the exception of ocaml libraries or other cases where the version of each dependency depends on a file in the git repository. The resulting container here does not depend on our code at all.
- The second stage pulls specifically the raw files from the git repository that are required to download other dependencies (like opam or bazel files). Then all dependencies are downloaded and installed, finally the full repository is cloned and the code is compiled. With some luck, separating these steps can make sure that dependencies are not re-downloaded when they do not change. I'm also tempted to build the .deb package here for ease of copying into the final container.
- The third container installs any runtime dependencies (can we start from a postgres container? They're built from debian buster-slim images) and copies the .deb installer from the 2nd stage. Here we will also have to handle the entrypoint for the container with multiple services running in it, the plan for now is to use systemd services (ideally created already as part of the deb?).

**Comment by 0x0I** [comment]
Creating the systemd units as a part of the *deb* could work, at least for the daemon, but we could also render `systemd` unit/service files via something like a Docker entrypoint script and environment variables at runtime (to avoid static/pre-baked unit config requiring image rebuilds for config changes).

**Comment by 0x0I** [comment]
> * can we start from a postgres container? They're built from debian buster-slim images

Maybe though could make customizing initialization logic a bit tricky and feels like it could be handled pretty easily by an entrypoint script or something along those lines.

I'd vote for basing on a more general slim image and just installing during the multi-stage build.

**Comment by lk86** [comment]
Yeah I mentioned it largely because I would expect something like the coda daemon deb package to at least include an example systemd unit if not a ready-to-use one. You are right though that this is not very 12-factor, where as building the units to fit the docker deployment at the entrypoint is far easier to manage and configure without rebuilding the container.

Additionally, my quick googling suggests that postgres doesn't include a systemd unit out of the box either so regardless the final stage will have to handle setting up some systemd services, in which case the entrypoint script should handle all of them.
