### ISSUE TITLE
Automated Validation - allow statistics to subscribe to other statistics

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#5387]
Working from #5137, the automated validation needs the ability to describe statistics which consume, as inputs, other statistics (in addition to log providers, which are already supported). The code can differentiate between log providers and statistics requested as dependencies by using the [Util.has_behaviour?/2](https://github.com/CodaProtocol/coda/pull/5137/files#diff-e711840166a02d56ea38c7948e962fc8R33) function to see if the specified module implements `Architecture.LogProvider` or `Architecture.Statistic`.

An important detail here is that we should write some function which will perform cycle checking against a provided list of statistics to ensure there are no dependency cycles. Actually calling this function is dependent on #5388, but for now, writing and testing a function with the signature `@spec has_dependency_cycle?([module]) :: bool` will suffice.

**Comment by psteckler** [comment]
Where would `has_dependency_cycle?` live in the code?

Its input is a list of modules implementing `Statistic` (I suppose we could disregard any others)?

**Comment by nholland94** [comment]
`Architecture.Statistic.has_dependency_cycle?` seems like a good place to define it to me. It should take in a list of `module`, with an invariant that each module passed in has the `Architecture.Statistic` behaviour. Probably best to raise an exception if one of the modules doesn't.
