### ISSUE TITLE
Automated Validation - implement block rate validations

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#5389]
#5137 includes a scaffold for how the block production rate validation would work, but there are a couple of additional pieces required to make it fully functional.

https://github.com/CodaProtocol/coda/blob/ec4f7811e32b40955655b29127f38c87d80a2ba3/src/app/validation/lib/coda/validations/block_production_rate.ex

1) Win rate needs to be implemented. Long term, win rate should be dynamically computed from the network's state (to account for changing stake distributions in the ledger). Since this requires a number of other providers and statistics to be fleshed out, we can just provide the expected win rate as a field on `Coda.Resources.BlockProducer`.
2) Necessary parameters, such as slot time, should be split out into some sort of configuration module, so that we have one place where they are all defined. In the future, we can read these network parameters from a file when the application initializes.

Once ready, this can be tested against the live network by modifying the base resources in `Coda.Application` appropriately. You will also need to configure your google cloud credentials, which can be done in a `.gitignore`d file in `src/app/validation/config/local.exs`. For example, mine loads my credentials via a json file set by an env var.

```
import Config

# BIG ISSUE with this method: private key gets fed in as start_link args to goth, so it shows up in sasl logs
# TODO: custom credentials module
config :goth,
  json: System.get_env("GOOGLE_CLOUD_AUTOMATED_VALIDATION_KEYFILE_JSON") |> File.read!()
```

**Comment by psteckler** [comment]
From discord conversation:
```
1) configure your local google cloud credentials (described some on issue)
2) ensure that you have some debug prints (so you can see if the validation fails or succeeds; you can just add something to the validation broker to log results)
3) mix run your application

When you mix run, you should first check your logs to see if the log filter looks correct. Mainly, you'll want to make sure that the log filter it renders is scoped to the correct network (might need to add a config var to set what the network name is, can't recall if I did that already or not). You should be able to see in logs (I believe), whether or not the log providers are getting messages from google cloud. At that point, just let it run for a bit and see what the validators print out.```
