### ISSUE TITLE
Reify cancellation intent into an explicit flag on transactions

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#5406]
Exchanges and other parties that are very careful to keep a ledger of balance transfer changes off-chain desire the property that every transaction deterministically produces the same N balance transfers or fails. If we allow implicit cancellation, then it's harder to understand this. Advisors have also confirmed we _do not_ want implicit cancellation.

We should add a field to txns in the relevant places to opt-in to canceling a txn explicit, and add this to GraphQL and CLI wherever necessary.

**Comment by aneesharaines** [comment]
@aneesharaines  to follow up on what is the new expectation here

**Comment by psteckler** [comment]
The finger trees used to store transactions were meant, if I recall correctly, to guard against DOS attacks, knowing that we do implicit cancellations of transactions in the middle of a sequence.

If we move to explicit cancellations, I believe that the finger tree data structure is no longer needed.

**Comment by bkase** [comment]
🤦 I mixed this up with #5428 . Ignore this, I am silly
