### ISSUE TITLE
Expose hash from pooledUserCommands and add gql query for user command lookup via hash in the mempool

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#5415]
Necessary to unify the interfaces of accessing and manipulating transactions across archive node (the ones in blocks) and API (the ones in mempool)

**Comment by bkase** [comment]
We should store the `hash` with the rest of the usercommand so the `pooledUserCommand` endpoint doesn't have to recompute all the hashes every time it's hit (I imagine this will be too slow)

**Comment by mrmr1993** [comment]
This was done in #5466 and #5467, closing.
