### ISSUE TITLE
Required statuses conflicts with dynamic pipeline

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#5523]
## Problem

If you make a status check required, GitHub will only all the PR to be mergeable if _both_ the status exists and it passes on that PR.

The current Buildkite setup creates a pipeline dynamically based on what files your PR has touched. If you don't touch something that triggers a job, the job won't run.

This is a problem! This means we can't make individual jobs required in this current setup as they may be skipped and GitHub will block the PR forever.

## Potential ideas

1. Always run ever job, but just make the job succeed instantly in the case that "we want to skip it". This will make the status appear on GitHub and will unblock PRs. The upside is we'll still be able to depend on atomic jobs. The downside is we waste some resources having to spin up workers to effectively just clone the repo and exit.

2. Block PRs on the full pipeline completing rather than individual steps. The downside: we can't depend only on the "required" jobs in a pipeline but have to depend on all of them at once, this means optional jobs must artificially pass ✅ . The upside: We mostly don't have to touch our setup as is and won't waste resources. Maybe we can integrate with the flaky system to mitigate this too.

I like (2) actually. Anyone have any other ideas?

**Comment by bkase** [comment]
In the short-term, this means we'd want to make the longer jobs (until we get the bigger instances) or ones we're not confident in (broken or something) _not run_ so we don't slow down peoples' workflows.

**Comment by mrmr1993** [comment]
@bkase the codeowners change I messaged you about yesterday probably falls into scope of this. Is there a good way to 'scope' a test so that it just returns true if it has no impact on some parts of the code.

**Comment by lk86** [comment]
Can we just have a specific buildkite job that is aware of the statuses of whatever jobs we want, and it runs for every pipeline so we can require it in GitHub?

**Comment by 0x0I** [comment]
Possibly though somewhat confused by what you mean by "aware of the statuses of whatever jobs we want" @lk86 (...status of last x number of runs on **develop** or something along those lines?)

**Comment by 0x0I** [comment]
So if a job is “required” in the sense that it should always run regardless of changes in a PR, isn’t that basically saying
that any change in the repo should trigger the job to run?

If so, seems like updating these *required* jobs' `dirtyWhen` [job spec](https://github.com/CodaProtocol/coda/blob/develop/buildkite/src/Pipeline/JobSpec.dhall#L10) property to a file pattern that matches ANY change (i.e. the job config default of [SelectFIles.everything](https://github.com/CodaProtocol/coda/blob/develop/buildkite/src/Lib/SelectFiles.dhall#L32)) could also work here.

**Comment by lk86** [comment]
To elaborate more on my proposed solution:
Instead of using github to decide which parts of the pipeline are required, we can have a specific job that always runs and is always required, and that job can be smart about any other steps/jobs in the same pipeline.

By "be smart" I mean that this meta-job would execute after all required jobs, and only return success if all of the required jobs were either 1) skipped because none of the relevant files are dirty, or 2) ran successfully and have the expected "success" status. This allows us to leverage all of the work that has already been done w/ dirtyWhen to skip jobs, but still allows github to enforce the "required" flag.

I don't know how to query for the status of another job in the same pipeline, but I'm sure its possible somehow, and even if you can't explicitly query for whether a previous job in the pipeline succeeded, I know its possible to block a job on the success of other jobs which is all we really need anyway.

**Comment by 0x0I** [comment]
Got it and cool, makes sense @lk86 - definitely seems worth exploring further though it might be worth investigating [this](https://github.com/uw-ipd/github-checks-buildkite-plugin) Buildkite Github checks plugin to see if we can leverage it, in typical Buildkite fashion thus far, to implement a solution to a likely typical pipeline issue faced by most (or at least opensource repo having, Github using) Buildkite users.

From going through it a bit, seems like we may be able to integrate the plugin's `output_summary` and `output_details` properties into a single job or even all *required* jobs to ensure the right check statuses are surfaced for *required* jobs. Hopefully this might help prevent us from having to implement custom logic on our end.

**Comment by 0x0I** [comment]
Closing for now as the current POR is to *require* pipeline SUCCESS or a pass of all jobs triggered based on submitted changesets -- coupled with the thinking that the Buildkite infrastructure should be capable of executing any triggered job in a reasonable (baseline == CircleCI parity) amount of time.
