### ISSUE TITLE
Simplify Logger via ppx

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#5531]
When we originally built out the new logging system there was a plan to ppx-away the module_ and location parameters of the logger. Manually typing these out is noisy and slow.

I'm sure this is a dupe, but I can't find the original.

**Comment by psteckler** [comment]
Proposed syntax:
```ocaml
[%%log info]
```
which generates the module and location, and uses the `logger` variable in scope.

You write the metadata and format string as we've been doing. This will accomodate the proposed `~tags` argument.
