### ISSUE TITLE
Delete GUI Wallet page from Docs Nav

### ISSUE THREAD

**Issue by aneesharaines** [CodaProtocol/coda#5544]

**Comment by aneesharaines** [comment]
@bijanshahrokhi  -  is this something that we need to do since we aren't actively developing or maintaining the GUI wallet?

**Comment by bijanshahrokhi** [comment]
If we wanted the wallet to continue working in testnet, do we need to update it each time we have a new testnet release? I'm asking because I'm wondering if we can keep this wallet just for testnet

**Comment by bijanshahrokhi** [comment]
Yes go ahead and remove this page https://codaprotocol.com/docs/gui-wallet
