### ISSUE TITLE
specify/override fee key

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#559]
We currently hardcode proposer fees to go to to the high_balance account.

https://github.com/o1-labs/nanobit/blob/master/app/nanobit/src/coda_worker.ml#L141

(rich only get richer)

This should be a run-time option to set the proposer public key to your own key.
(get paid for staking)

**Comment by cmr** [comment]
We do this now, `-propose` takes as an argument a path to a private key.
