### ISSUE TITLE
Update copy on Genesis Landing Page

### ISSUE THREAD

**Issue by sherrylin13** [CodaProtocol/coda#5621]
Update title of page, as well as headers and body copy of the first 2 sections of the Genesis landing page (codaprotocol.com/genesis), to clarify message and drive more action.

Timing: Before launch of testnet release 3.3 (8/25)

Copy updates noted below:

Genesis --> This is Genesis

Become one of 1000 community members to receive a token grant. --> We need your help to launch the world’s lightest blockchain.

You'll complete challenges on testnet, learn how to operate the protocol, receive public recognition on our leaderboard, and help to strengthen the Coda network and community.-->A blockchain is only as strong as it’s community, and here at Coda our community is paramount to our success. We’re looking for new Genesis founding members to join the community to learn how to operate the protocol, take part in challenges on testnet, and help to strengthen the Coda community.
[Apply Now] CTA button stays the same

Become a Genesis Founding Member -->Could you be our next Genesis Founding Member?

Becoming a Genesis founding member is the highest honor in the Coda community. You'll have an opportunity to strengthen and harden the protocol, create tooling and documentation, and build the community. When the protocol launches in mainnet, you will be the backbone of robust, decentralized participation. Together, we will enable the first blockchain that is truly decentralized at scale. -->We’re offering token grants of 66,000 coda for community members who can help us strengthen the Coda Protocol, create tooling and documentation, and build the community. As a validator on Coda, you will be the backbone of a robust, decentralized blockchain and received block rewards for securing the network

**Comment by aneesharaines** [comment]
We will take this next week as any docs and site changes that need to happen as part of the 3.3 release.
