### ISSUE TITLE
Don't download keys from S3 for dev builds

### ISSUE THREAD

**Issue by mrmr1993** [CodaProtocol/coda#5623]
Now that all profiles use the same curves, building dev will attempt to fetch keys from S3 rather than locally generating them.

We should disable this for dev, it causes obscure errors if the download is partial or fails.

**Comment by lk86** [comment]
I would love to see this be a config or cli flag of some sort but the dune profile works too. Maybe a dune profile "no-cache" that explicitly does not cache any values in s3 during builds?
