### ISSUE TITLE
Creating a new token crashes the daemon

### ISSUE THREAD

**Issue by MartinMinkov** [CodaProtocol/coda#5724]
I am using the rosetta container to build a local network to test the new CLI. I am building off the https://github.com/CodaProtocol/coda/pull/5710 branch (it's now been merged.)

To start the network I'm running:
`coda/src/app/rosetta/start.sh CURL`

The daemon crashes when I issue:
`./coda.exe client create-token -sender $CODA_PUBLIC_KEY1`

[coda_crash_report_2020-08-20_22-45-51.056911.tar.gz](https://github.com/CodaProtocol/coda/files/5105837/coda_crash_report_2020-08-20_22-45-51.056911.tar.gz)

**Comment by aneesharaines** [comment]
@MartinMinkov can you recheck this by running the tokens challenge when the new release branch is available?

**Comment by MartinMinkov** [comment]
@aneesharaines I checked the tokens challenge yesterday while writing new token docs and I can confirm that the tokens challenge is successful and works as expected!
