### ISSUE TITLE
Properly calculate network delay parameter

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#583]
The network delay parameter needs to be calculated dynamically from information about the gossip network. See page 32 of the Ouroboros Genesis for more details.

**Comment by enolan** [comment]
If we pick some distribution over inter-node messaging delay, we can come up with an estimate based on how big the network is, which we can estimate based on how full our routing table is. Someone (me) would have to go do the Bayesian math and figure out how good of an estimate we'd get. It's complicated, but possible.
