### ISSUE TITLE
Make rosetta endpoints resilient to crashes

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#5930]
The decode functions in Rosetta can raise exceptions and this would take down the Rosetta server on bad 
 (or malicious) input.

Maybe it makes sense to wrap the endpoints in exception handlers? Perhaps it's better to change the coding functions to return options or results. Either approach seems fine 👍

**Comment by psteckler** [comment]
@bkase Where in the code are the endpoints to be wrapped?
