### ISSUE TITLE
Coda 3.3 is crashed

### ISSUE THREAD

**Issue by StarLI-Trapdoor** [CodaProtocol/coda#5978]
When coda daemon is started, crash happens.
[coda_crash_report_2020-09-17_03-51-11.748691.tar.gz](https://github.com/CodaProtocol/coda/files/5236241/coda_crash_report_2020-09-17_03-51-11.748691.tar.gz)

**Comment by garethtdavies** [comment]
Another `Connection_closed (\"EOF or connection closed\")` error. See also #6001

**Comment by emberian** [comment]
Confirmed :+1: closing as a dupe
