### ISSUE TITLE
Coda daemon crased 

### ISSUE THREAD

**Issue by jiten123321** [CodaProtocol/coda#5981]
When I try to run the CODA daemon, it crashed you can check the crash report /home/jiten/.coda-config/coda_crash_report_2020-09-17_04-48-05.988265.tar.gz

**Comment by garethtdavies** [comment]
@jiten123321 Can you add the crash report to this issue?

**Comment by emberian** [comment]
Probably fixed by #6036, attach the crash report to reopen the issue.
