### ISSUE TITLE
Testnet 3.3 : Coda daemon crash

### ISSUE THREAD

**Issue by bidulemachin** [CodaProtocol/coda#5983]
can not start coda daemon using command " coda daemon -peer $SEED1"
[coda_crash_report_2020-09-17_08-32-39.008848.tar.gz](https://github.com/CodaProtocol/coda/files/5237582/coda_crash_report_2020-09-17_08-32-39.008848.tar.gz)

**Comment by garethtdavies** [comment]
This is `(rpc_error (Connection_closed (\"EOF or connection closed\")` which is #6001

**Comment by emberian** [comment]
Closing as a dupe
