### ISSUE TITLE
Snark Worker Crashed Twice Already

### ISSUE THREAD

**Issue by gaia** [CodaProtocol/coda#5991]
this is the log from the 2nd crash

[coda_crash_report_2020-09-17_15-23-19.640880.tar.gz](https://github.com/CodaProtocol/coda/files/5240771/coda_crash_report_2020-09-17_15-23-19.640880.tar.gz)

**Comment by gaia** [comment]
[coda_crash_report_2020-09-17_19-54-43.917034.tar.gz](https://github.com/CodaProtocol/coda/files/5241710/coda_crash_report_2020-09-17_19-54-43.917034.tar.gz)

another crash

**Comment by gaia** [comment]
can't sell my snarks, bc it crashes, then it takes a while to catch up

**Comment by emberian** [comment]
this might be due to the SNARK bug that was fixed with beta7 hotfix, there was a transaction going around the network that killed every snark worker it touched.
