### ISSUE TITLE
Coda Daemon crashed - Testenet 3.3 Docker Crash Report

### ISSUE THREAD

**Issue by edsphinx** [CodaProtocol/coda#6014]
I sharing the crash report as suggested after the error, I was trying to run with the latest docker image:

docker run -d --name coda -p 8302:8302 -p 8303:8303 --restart always codaprotocol/coda-daemon:0.0.16-beta6 daemon -peer $SEED1

In macOS 10.15.4

[coda_crash_report_2020-09-18_00-26-53.498373.tar.gz](https://github.com/CodaProtocol/coda/files/5242633/coda_crash_report_2020-09-18_00-26-53.498373.tar.gz)

**Comment by garethtdavies** [comment]
```
"Exception":"(monitor.ml.Error\n  ((rpc_error (Connection_closed (\"EOF or connection closed\"))
```

This is the same error as provided in comments of https://github.com/CodaProtocol/coda/issues/6001

**Comment by emberian** [comment]
Closing as a dupe
