### ISSUE TITLE
Node crashed after some minutes and some operations

### ISSUE THREAD

**Issue by crackerli** [CodaProtocol/coda#6046]
How to produce:
1. use coda daemon -background to start the node
2. wait for the synced status
3. import private key
4. send echo transaction
5. set staking address
6. set snark-worker
7. After a while, node crashed

2020-09-19 02:48:59 UTC [Info] Using the compiled constraint constants
2020-09-19 02:48:59 UTC [Info] Ledger file $path does not exist
	path: "/var/lib/coda/genesis_ledger_accounts_e7fd308899bca6956b093b635988ea06630adbf540e13d38dcd2f7ab629da53c_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz"
2020-09-19 02:48:59 UTC [Info] Ledger file $path does not exist
	path: "/usr/local/var/coda/genesis_ledger_accounts_e7fd308899bca6956b093b635988ea06630adbf540e13d38dcd2f7ab629da53c_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz"
2020-09-19 02:48:59 UTC [Info] Ledger file $path does not exist
	path: "/tmp/s3_cache_dir/genesis_ledger_accounts_e7fd308899bca6956b093b635988ea06630adbf540e13d38dcd2f7ab629da53c_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz"
2020-09-19 02:48:59 UTC [Info] Ledger file $path does not exist
	path: "/tmp/coda_cache_dir/genesis_ledger_accounts_e7fd308899bca6956b093b635988ea06630adbf540e13d38dcd2f7ab629da53c_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz"
2020-09-19 02:48:59 UTC [Info] Ledger file $path does not exist
	path: "/var/lib/coda/genesis_ledger_accounts_e7fd308899bca6956b093b635988ea06630adbf540e13d38dcd2f7ab629da53c_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz"
2020-09-19 02:48:59 UTC [Info] Ledger file $path does not exist
	path: "/root/.coda-config/genesis_ledger_accounts_e7fd308899bca6956b093b635988ea06630adbf540e13d38dcd2f7ab629da53c_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz"
2020-09-19 02:49:00 UTC [Info] Could not download genesis ledger from $uri: $error
	uri: "https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/genesis_ledger_accounts_e7fd308899bca6956b093b635988ea06630adbf540e13d38dcd2f7ab629da53c_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz"
	error: "(monitor.ml.Error\n (\"Process.run failed\"\n  ((prog curl)\n   (args\n    (--fail -o\n     /tmp/s3_cache_dir/genesis_ledger_accounts_e7fd308899bca6956b093b635988ea06630adbf540e13d38dcd2f7ab629da53c_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz\n     https://s3-us-west-2.amazonaws.com/snark-keys.o1test.net/genesis_ledger_accounts_e7fd308899bca6956b093b635988ea06630adbf540e13d38dcd2f7ab629da53c_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz))\n   (exit_status (Exit_non_zero 22)) (stdout \"\")\n   (stderr\n    (\"  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current\"\n     \"                                 Dload  Upload   Total   Spent    Left  Speed\"\n     \"\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\\r  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0\"\n     \"curl: (22) The requested URL returned error: 404 Not Found\" \"\"))))\n (\"Raised at file \\\"src/error.ml\\\" (inlined), line 9, characters 14-30\"\n  \"Called from file \\\"src/or_error.ml\\\", line 72, characters 17-32\"\n  \"Called from file \\\"src/deferred1.ml\\\", line 17, characters 40-45\"\n  \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n  \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"))"
2020-09-19 02:49:04 UTC [Info] Creating genesis ledger tar file for $root_hash at $path from database at $dir
	root_hash: "3NLDMBjXomomCVeMu54X8qXYZDuCzKM4QJaezgdUX57yHWqNgjmM"
	path: "/root/.coda-config/genesis_ledger_f1c1b1bae67e1ec8ffdf91121ec34c7c97933fd86b727ebd8a5421b7f12a8ece.tar.gz"
	dir: "/tmp/coda_cache_dir/945bedab-6822-384d-11a0-dd797d393d39"
2020-09-19 02:49:04 UTC [Info] Linking ledger file $tar_path to $named_tar_path
	tar_path: "/root/.coda-config/genesis_ledger_f1c1b1bae67e1ec8ffdf91121ec34c7c97933fd86b727ebd8a5421b7f12a8ece.tar.gz"
	named_tar_path: "/root/.coda-config/genesis_ledger_release_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz"
2020-09-19 02:49:05 UTC [Info] Genesis proof file $path does not exist
	path: "/root/.coda-config/genesis_proof_09652a7d121c7d527f8ff665410f9ed65b362ea401720e8dc076be82caeff68d"
2020-09-19 02:49:05 UTC [Info] Found genesis proof file at $path
	path: "/var/lib/coda/genesis_proof_09652a7d121c7d527f8ff665410f9ed65b362ea401720e8dc076be82caeff68d"
2020-09-19 02:49:05 UTC [Info] Loaded ledger from $ledger_file and genesis proof from $proof_file
	ledger_file: "/root/.coda-config/genesis_ledger_release_f094d0eb814dbbff2f41f3f69c414331566f2c4a884c309944899ea59f101b9a.tar.gz"
	proof_file: "/var/lib/coda/genesis_proof_09652a7d121c7d527f8ff665410f9ed65b362ea401720e8dc076be82caeff68d"
2020-09-19 02:49:07 UTC [Fatal] Unhandled top-level exception: $exn
Generating crash report
	exn: "(monitor.ml.Error (Failure \"no seed or initial peer flags passed\")\n  (\"Raised at file \\\"stdlib.ml\\\", line 33, characters 17-33\"\n    \"Called from file \\\"src/app/cli/src/coda.ml\\\", line 737, characters 11-58\"\n    \"Called from file \\\"src/deferred0.ml\\\", line 56, characters 64-69\"\n    \"Called from file \\\"src/job_queue.ml\\\" (inlined), line 131, characters 2-5\"\n    \"Called from file \\\"src/job_queue.ml\\\", line 171, characters 6-47\"\n    \"Caught by monitor coda\"))"

  ☠  Coda Daemon crashed.
   The Coda Protocol developers would like to know why!

    Please:
      Open an issue:
        <https://github.com/CodaProtocol/coda/issues/new>

      Briefly describe what you were doing and attach the crash report /root/.coda-config/coda_crash_report_2020-09-19_02-49-07.936014.tar.gz

[coda_crash_report_2020-09-19_02-49-07.936014.tar.gz](https://github.com/CodaProtocol/coda/files/5249033/coda_crash_report_2020-09-19_02-49-07.936014.tar.gz)

**Comment by crackerli** [comment]
Re-start the node not helping, still crashed at bootstrap

**Comment by emberian** [comment]
@crackerli like the error message says, you need to pass `-peer` argument.

**Comment by crackerli** [comment]
Of course I did, please see my description to produce, I can even send transactions
