### ISSUE TITLE
Crash Report BP

### ISSUE THREAD

**Issue by gaia** [CodaProtocol/coda#6054]
had been running fine (aside from a couple of synced>catchup>synced), but crashed when I queried `client status` twice in a row

[coda_crash_report_2020-09-20_05-55-05.910545.zip](https://github.com/CodaProtocol/coda/files/5251205/coda_crash_report_2020-09-20_05-55-05.910545.zip)

**Comment by garethtdavies** [comment]
`write to closed pipe` which is #6049
