### ISSUE TITLE
Daemon crashed with corrupted crash report

### ISSUE THREAD

**Issue by dheeraj07** [CodaProtocol/coda#6070]
<img width="1677" alt="Screen Shot 2020-09-21 at 10 53 14 AM" src="https://user-images.githubusercontent.com/22843503/93734914-cb549280-fbf8-11ea-9f72-e0d26a49a400.png">
Not able to open the crash report file because it's corrupted, so attaching the screenshot

**Comment by garethtdavies** [comment]
This is the same as #6071

**Comment by deepthiskumar** [comment]
This is fixed on develop. Basically, we were using epoch-slot in one place and global slot in another causing expired transactions to be included in a block.
