### ISSUE TITLE
You can DoS a client trying to catchup by rapidly alternating between valid, yet different future states

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#672]
The Ledger-builder-controller currently supports only one async job at a time (will be addressed with #671), we eagerly interrupt async jobs when we receive a new transition that is "stronger" than any current transitions we have locked in locally. This currently excludes in progress ones.

**Comment by enolan** [comment]
is this one still valid?

**Comment by cmr** [comment]
It looks like `Ledger_catchup` isn't interruptible anymore. I'm going to close this, @bkase reopen if it's still valid.
