### ISSUE TITLE
Add a command for killing `cli daemon`

### ISSUE THREAD

**Issue by johnwu93** [CodaProtocol/coda#673]
We can now run cli daemon on a background process via command line: https://github.com/o1-labs/nanobit/pull/670

It is not intuitive for the user to kill the daemon. If you run `pkill cli`, it will crash your Linux machine. @o1brad. The best way to kill it on the terminal is by running `pkill -f "cli daemon"`. It would be better to encapsulate this as a command within cli.

**Comment by jkrauska** [comment]
@cmr Could you give this a second look.  For clean testbeds, `coda client stop-daemon` would be very useful.  Regular pkill doesn't reap child parallel-processes cleanly either.

**Comment by cmr** [comment]
@jkrauska with #1202 landed, let me know how it goes. The parallel workers should die of their own accord. I discovered that rpc_parallel maintains a "heartbeat" connection that likely explains that other listening port you saw. In theory the workers die when that connection is closed; in practice, I think (and @imeckler confirmed verbally) that the workers can get blocked in some long computation that means they might not notice the connection is closed for a while.
