### ISSUE TITLE
Proposer should only evaluate VRF once per slot

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#706]
Currently, the proposer interacts with the consensus mechanism via two hooks: `next_proposal`, and `generate_transition`. In `Consensus.Proof_of_stake.next_proposal`, VRFs for slots are evaluated until a winning slot is found, at which point it returns `` `Propose winning_slot_time`` to the proposer. The VRF for this slot is then re-evaluated in `Consensus.Proof_of_stake.generate_transition` at `winning_slot_time`. If possible, we should reuse the VRF evaluation from `Consensus.Proof_of_stake.next_proposal`, most likely by including some sort of value defined by the `Consensus.Mechanism.S` in the `` `Propose`` variant returned by `Consensus.Mechanism.next_proposal`.

**Comment by cmr** [comment]
https://github.com/CodaProtocol/coda/blob/master/src/lib/consensus/proof_of_stake.ml#L1168 boom
