### ISSUE TITLE
Audit public flags and hide bad ones behind internal

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#791]
For example `-txn-capacity` should not be exposed to people since it needs to be the same for the whole testnet.

While we're here, @jkrauska had a good suggestion of making that arg just take an int and round to the nearest power of 2 instead of making people think of logs

**Comment by cmr** [comment]
We've cleaned these up a lot, I think we're done here. We have `coda advanced` now, and all the parameters that are network-invariant are now compile time constants.
