### ISSUE TITLE
Hide network-wide settings

### ISSUE THREAD

**Issue by bkase** [CodaProtocol/coda#816]
The `txn-capacity` and `proposal-interval` arguments to `coda daemon` are network-wide, and generally shouldn't be changed from the defaults. We should somehow hide them behind `internal`.

**Comment by cmr** [comment]
I'm not sure where we should hide them. they need to be present when spawning the daemon. should we add another flag that enables setting these flags? Can `Command` even describe that?

**Comment by jkrauska** [comment]
If sane, we could make them config-file-only options.

Would be nice to distribute stock config files for each testnet release.

**Comment by cmr** [comment]
I like that.

**Comment by cmr** [comment]
These are compile time now!
