### ISSUE TITLE
Change addresses to Base 58 encoding

### ISSUE THREAD

**Issue by o1brad** [CodaProtocol/coda#855]
We currently encode in base 64, which is unique among cryptocurrencies. Bitcoin and Ethereum encode in Base58, which has a number of benefits. From the [Bitcoin wiki](https://en.bitcoin.it/wiki/Base58Check_encoding):

```
// Why base-58 instead of standard base-64 encoding?
// - Don't want 0OIl characters that look the same in some fonts and
//      could be used to create visually identical looking account numbers.
// - A string with non-alphanumeric characters is not as easily accepted as an account number.
// - E-mail usually won't line-break if there's no punctuation to break at.
// - Doubleclicking selects the whole number as one word if it's all alphanumeric.
```

Additionally, it'll be less jarring for people who are used to interacting with Bitcoin and Ethereum.

**Comment by cmr** [comment]
@psteckler implemented this in #2675
