### ISSUE TITLE
Use miniupnpc to open ports and firewalls by default, helpful error message if unsuccessful

### ISSUE THREAD

**Issue by o1brad** [CodaProtocol/coda#860]
For people to join the network, they need to be on a well-connected computer. Currently, we're advising people to reconfigure their routers + firewalls using miniupnpc then trying manually. Can we incorporate miniupnpc into the daemon so it attempts to open the default ports automatically, and if unsuccessful, gives an error message that directs people to the manual instructions?

**Comment by yourbuddyconner** [comment]
This is very important in terms of wallet usability as without UPNP configuration a wallet behind a NAT is not routable.

**Comment by yourbuddyconner** [comment]
Talked to @Schmavery, the `upnpc` client alone should be sufficient to unblock the product team.
