### ISSUE TITLE
Integrate optcomp with more of Coda

### ISSUE THREAD

**Issue by nholland94** [CodaProtocol/coda#913]
Now that we have the basis of profile based compilation, thanks to [optcomp](https://github.com/janestreet/ppx_optcomp) + a dune trick, we should integrate this into our cli. Specifically, we should only compile integration tests into the cli when the `test` profile is selected. There may also be some other constant options that we will want to manipulate using `optcomp`, as necessary. Part of this task should include identifying potential uses `optcomp` + build profiles.

**Comment by cmr** [comment]
done
