### ISSUE TITLE
building on mac

### ISSUE THREAD

**Issue by cmr** [CodaProtocol/coda#962]
I've had [this branch](https://github.com/CodaProtocol/coda/tree/feature/mac-build) kicking around for a while that attempts to get the build working on mac. The libsnark build changes are easy, but there's some strange dune- or ocamlopt-related problem where `camlsnark_c_stubs` isn't being seen by the linker somehow. Haven't been able to figure it out.

**Comment by cmr** [comment]
building on mac currently works, though there are some problems.

**Comment by rahulmutt** [comment]
@cmr What problems have been observed on Mac besides the lack of OpenMP support (which I try to address in #2250)?

**Comment by cmr** [comment]
@rahulmutt the binaries we build aren't portable and can't be distributed.

**Comment by vitaliel** [comment]
If you install project on machine that does not have ocaml, you will need to run `opam init` to add code to .zshrc or .bashrc.

Close terminal and open new one, then you can run `make build`.

**Comment by mimoo** [comment]
Note that there are some issues building `re2` that can be fixed with this: https://github.com/janestreet/re2/issues/31
