### ISSUE TITLE
Don't give out SNARK work for which there is already a proof in the pool with better fee

### ISSUE THREAD

**Issue by imeckler** [CodaProtocol/coda#966]
A daemon has a fee `f` which it asks to be paid for completing a piece of SNARK work. It should thus not give its workers work for which there is already SNARK work in the SNARK pool with this or better fee.

**Comment by cmr** [comment]
Seems like a good candidate for a mentored issue. Do you want to write that up, @imeckler, or should I?

**Comment by johnwu93** [comment]
I am doing this issue right now.

https://github.com/CodaProtocol/coda/pull/1018
