### ISSUE TITLE
Encode hashes before printing them to logs

### ISSUE THREAD

**Issue by jkrauska** [CodaProtocol/coda#984]
Logs are often full of binary data streams.

eg..

```
sok_digest\n      \"x\\244\\197\\168\\152\\177\\170\\168Z\\175\\137\\193[\\011e\\030!gNe\\004\\20
```
or
```
proof\n       \"0x\\180z\\1855\\211\\021
```
or
```
aux_hash\n       \"(\\194\\137[\\233\\176_v\\233 d:IC
```

Ideally we should not be sending this sort of content to a log file stream.

Can we encode these messages at log time and tidy them?

**Comment by cmr** [comment]
We've made a lot of progress on this!
